export const codeDB = {
    1: [
        { q: "Plumbing fixtures shall be made of smooth non-absorbent material, free from concealed fouling surfaces and shall be located in ventilated enclosures.", choices: ["A. Principle No. 1", "B. Principle No. 5", "C. Principle No. 7", "D. Principle No. 9"], a: 2 },
    { q: "What type of cleanout plug shall be installed in places prone to passing personnel or vehicles?", choices: ["A. Raised head cleanout plug", "B. Countersunk cleanout plug", "C. Hubless blind plug", "D. None of these"], a: 1 },
    { q: "A type of septic tank that is prohibited.", choices: ["A. Steel", "B. Wooden", "C. Plastic", "D. Concrete"], a: 1 },
    { q: "Polyethylene pipe is black and is used for cold water and sprinkler system. How is polyethylene pipe represented?", choices: ["A. PPE", "B. PPR", "C. PVC", "D. PE"], a: 3 },
    { q: "Who was the President of the Republic of the Philippines who signed the 'Plumbing Law of the Philippines'?", choices: ["A. Pres. Ramon Magsaysay", "B. Pres. Elpidio Quirino", "C. Pres. Ferdinand Marcos", "D. Pres. Manuel Roxas"], a: 0 },
    { q: "What type of concealed connection of fixtures shall be provided with access panel or utility at least 0.3 meter in its dimension for easy inspection and repair?", choices: ["A. Flanged", "B. Hubless", "C. Slip joint", "D. Ball and socket"], a: 2 },
    { q: "A ______ is a drainage pipe that passes through at least one story as a drain pipe, including any horizontal offsets.", choices: ["A. Sanitary sewer", "B. Soil or waste stack", "C. Spigot", "D. Soil pipe"], a: 1 },
    { q: "A non-watertight lined excavation in the ground which receives the discharge of a sanitary drainage system permitting the liquid to seep through the bottom and sides.", choices: ["A. privy", "B. cesspool", "C. disposal field", "D. seepage pit"], a: 1 },
    { q: "Slaughter houses and packing establishments shall be connected to and shall drain or discharge through a ______ of an approved design.", choices: ["A. drainage system", "B. screening device", "C. grease interceptor", "D. grease trap"], a: 1 },
    { q: "Joints in copper pans or liners shall be ______.", choices: ["A. 6.8 kg asphalt felt", "B. flared or soldered", "C. soldered or brazed", "D. burned"], a: 3 },
    { q: "Septic tank should be at least ______ meters away from any source of water supply wells.", choices: ["A. 10", "B. 15", "C. 20", "D. 30"], a: 1 },
    { q: "Solder and fluxes with lead content which exceeds ______ are prohibited in the piping systems used to conveyed potable water.", choices: ["A. 0.002", "B. 0.005", "C. 0.008", "D. 0.001"], a: 0 },
    { q: "Horizontal drainage lines shall be run in practical alignment and at a uniform slope of not less than ______.", choices: ["A. 1%", "B. 2%", "C. 3%", "D. 4%"], a: 1 },
    { q: "The minimum size of a water service pipe from the street main to the building shall be ______.", choices: ["A. 1/2\"", "B. 3/4\"", "C. 1\"", "D. 1 1/4\""], a: 1 },
    { q: "A vertical pipe which conveys only wastewater or liquid waste free of fecal matter.", choices: ["A. Soil stack", "B. Waste stack", "C. Vent stack", "D. Riser"], a: 1 },
    { q: "What is the minimum age requirement for an applicant for the Master Plumber Board Exam?", choices: ["A. 18", "B. 20", "C. 21", "D. 25"], a: 2 },
    { q: "Every building having a plumbing fixture installed and intended for human habitation shall have a connection to a ______.", choices: ["A. Septic tank", "B. Public sewer", "C. Cesspool", "D. Sump"], a: 1 },
    { q: "The maximum length of a trap arm for a 2-inch pipe is ______.", choices: ["A. 1.5 m", "B. 0.6 m", "C. 1.0 m", "D. 1.8 m"], a: 0 },
    { q: "What is the minimum diameter of a vent pipe?", choices: ["A. 1 1/4\"", "B. 1 1/2\"", "C. 2\"", "D. 1\""], a: 0 },
    { q: "A fitting or device that provides a liquid seal to prevent the emission of sewer gases.", choices: ["A. Vent", "B. Trap", "C. Cleanout", "D. Valve"], a: 1 },
    { q: "What is the standard length of a cast iron soil pipe?", choices: ["A. 1.5 m", "B. 3.0 m", "C. 5.0 ft", "D. Both A and C"], a: 3 },
    { q: "The overflow pipe from a water supply tank shall be provided with a ______.", choices: ["A. Check valve", "B. Screen", "C. Gate valve", "D. Trap"], a: 1 },
    { q: "A device installed in a drainage system to prevent reverse flow.", choices: ["A. Check valve", "B. Backwater valve", "C. Globe valve", "D. Angle valve"], a: 1 },
    { q: "The minimum air gap for a lavatory is ______.", choices: ["A. 1 inch", "B. 2 inches", "C. 1.5 inches", "D. 3 inches"], a: 0 },
    { q: "What type of pipe is prohibited for use in a building's vent system?", choices: ["A. PVC", "B. GI", "C. Lead", "D. CISP"], a: 2 },
    { q: "What is the minimum clearance in front of a water closet?", choices: ["A. 30 cm", "B. 60 cm", "C. 45 cm", "D. 75 cm"], a: 1 },
    { q: "What is the minimum distance between the wall and the center of the water closet?", choices: ["A. 30 cm", "B. 37.5 cm", "C. 45 cm", "D. 50 cm"], a: 1 },
    { q: "The minimum size of a shower drain is ______.", choices: ["A. 1 1/2\"", "B. 2\"", "C. 3\"", "D. 4\""], a: 1 },
    { q: "A water system that provides water for fire protection and domestic use.", choices: ["A. Combined system", "B. Separate system", "C. Direct system", "D. Dual system"], a: 0 },
    { q: "The minimum slope for a 4-inch horizontal drainage pipe.", choices: ["A. 1%", "B. 2%", "C. 3%", "D. 4%"], a: 1 },
    { q: "What is the standard height of a laundry tub from the floor?", choices: ["A. 70 cm", "B. 80 cm", "C. 85 cm", "D. 90 cm"], a: 2 },
    { q: "A vent that serves a single fixture trap.", choices: ["A. Common vent", "B. Individual vent", "C. Circuit vent", "D. Loop vent"], a: 1 },
    { q: "The part of the plumbing system that extends outside the building wall.", choices: ["A. Building drain", "B. Building sewer", "C. Private sewer", "D. Main"], a: 1 },
    { q: "What is the minimum depth of a trap seal?", choices: ["A. 25 mm", "B. 51 mm", "C. 102 mm", "D. 75 mm"], a: 1 },
    { q: "What is the maximum depth of a trap seal?", choices: ["A. 51 mm", "B. 102 mm", "C. 150 mm", "D. 200 mm"], a: 1 },
    { q: "A valve used to control the flow of water in one direction only.", choices: ["A. Gate valve", "B. Globe valve", "C. Check valve", "D. Ball valve"], a: 2 },
    { q: "What is the standard diameter of a flush valve for a urinal?", choices: ["A. 3/4\"", "B. 1/2\"", "C. 1\"", "D. 1 1/4\""], a: 0 },
    { q: "What is the standard diameter of a flush valve for a water closet?", choices: ["A. 3/4\"", "B. 1\"", "C. 1 1/4\"", "D. 1 1/2\""], a: 1 },
    { q: "The minimum distance from the trap to the vent for a 1 1/2 inch pipe.", choices: ["A. 0.6 m", "B. 1.1 m", "C. 1.5 m", "D. 1.8 m"], a: 1 },
    { q: "What is the standard height of a wall-hung urinal?", choices: ["A. 50 cm", "B. 60 cm", "C. 70 cm", "D. 45 cm"], a: 1 },
    { q: "The device used to increase water pressure in a building.", choices: ["A. Booster pump", "B. Sump pump", "C. Ejector pump", "D. Jet pump"], a: 0 },
    { q: "What is the minimum diameter of a cleanout for a 2-inch pipe?", choices: ["A. 1 1/2\"", "B. 2\"", "C. 3\"", "D. 4\""], a: 1 },
    { q: "The vertical distance from the floor to the flood level rim of a lavatory.", choices: ["A. 75 cm", "B. 80 cm", "C. 85 cm", "D. 90 cm"], a: 1 },
    { q: "What is the purpose of a P-trap?", choices: ["A. To prevent odors", "B. To catch debris", "C. To stop backflow", "D. To vent air"], a: 0 },
    { q: "A pipe that carries rainwater from the roof to the ground.", choices: ["A. Soil pipe", "B. Waste pipe", "C. Leader", "D. Vent"], a: 2 },
    { q: "What is the minimum diameter of a roof leader for a small residential house?", choices: ["A. 2\"", "B. 3\"", "C. 4\"", "D. 1 1/2\""], a: 1 },
    { q: "The process of joining two copper pipes using heat and filler metal.", choices: ["A. Welding", "B. Soldering", "C. Brazing", "D. Threading"], a: 1 },
    { q: "What is the standard color for a vent pipe?", choices: ["A. Yellow", "B. Green", "C. Gray", "D. White"], a: 2 },
    { q: "The minimum size of a vent for a septic tank.", choices: ["A. 1 1/2\"", "B. 2\"", "C. 3\"", "D. 4\""], a: 1 },
    { q: "What is the standard height of a water meter from the ground?", choices: ["A. 30 cm", "B. 45 cm", "C. 60 cm", "D. 15 cm"], a: 0 },
    { q: "A tank used to store water for fire protection.", choices: ["A. Cistern", "B. Reservoir", "C. Fire tank", "D. Standpipe"], a: 0 },
    { q: "What is the minimum diameter of a water main for a subdivision?", choices: ["A. 4\"", "B. 6\"", "C. 8\"", "D. 10\""], a: 1 },
    { q: "The device used to prevent water from entering a building from a flooded sewer.", choices: ["A. Check valve", "B. Backwater valve", "C. Gate valve", "D. Ball valve"], a: 1 },
    { q: "What is the standard diameter of a kitchen sink waste pipe?", choices: ["A. 1 1/2\"", "B. 2\"", "C. 3\"", "D. 1 1/4\""], a: 0 },
    { q: "The minimum distance between two cleanouts on a straight horizontal line.", choices: ["A. 15 m", "B. 30 m", "C. 45 m", "D. 10 m"], a: 1 },
    { q: "What is the standard height of a bidet from the floor?", choices: ["A. 35 cm", "B. 40 cm", "C. 45 cm", "D. 50 cm"], a: 1 },
    { q: "The device used to mix hot and cold water in a shower.", choices: ["A. Mixing valve", "B. Diverter", "C. Faucet", "D. Aerator"], a: 0 },
    { q: "What is the minimum diameter of a soil stack for a 5-story building?", choices: ["A. 3\"", "B. 4\"", "C. 5\"", "D. 6\""], a: 1 },
    { q: "The process of testing a plumbing system with air pressure.", choices: ["A. Water test", "B. Air test", "C. Smoke test", "D. Peppermint test"], a: 1 },
    { q: "What is the minimum size of a vent for a kitchen sink?", choices: ["A. 1 1/4\"", "B. 1 1/2\"", "C. 2\"", "D. 1\""], a: 1 },
    { q: "The part of the trap that holds the water seal.", choices: ["A. Dip", "B. Crown weir", "C. Trap arm", "D. Inlet"], a: 0 },
    { q: "What is the standard height of a toilet seat from the floor?", choices: ["A. 40 cm", "B. 45 cm", "C. 50 cm", "D. 35 cm"], a: 0 },
    { q: "A pipe that carries water to a single fixture.", choices: ["A. Branch", "B. Riser", "C. Main", "D. Fixture supply"], a: 3 },
    { q: "What is the minimum diameter of a bathtub waste pipe?", choices: ["A. 1 1/2\"", "B. 2\"", "C. 1 1/4\"", "D. 3\""], a: 0 },
    { q: "The process of removing air from a water pipe.", choices: ["A. Bleeding", "B. Venting", "C. Purging", "D. Flushing"], a: 0 },
    { q: "What is the standard height of a drinking fountain for children?", choices: ["A. 60 cm", "B. 75 cm", "C. 90 cm", "D. 50 cm"], a: 1 },
    { q: "A valve used to control the volume of water flow.", choices: ["A. Gate valve", "B. Globe valve", "C. Ball valve", "D. Butterfly valve"], a: 1 },
    { q: "What is the minimum size of a vent for a shower?", choices: ["A. 1 1/2\"", "B. 2\"", "C. 1 1/4\"", "D. 3\""], a: 0 },
    { q: "The part of the plumbing system that collects rainwater from the ground.", choices: ["A. Storm drain", "B. Sewer", "C. Catch basin", "D. French drain"], a: 0 },
    { q: "What is the standard length of a galvanized iron pipe?", choices: ["A. 6.0 m", "B. 3.0 m", "C. 5.0 m", "D. 4.0 m"], a: 0 },
    { q: "The device used to protect a water heater from excessive temperature.", choices: ["A. Pressure relief valve", "B. Temperature relief valve", "C. T&P valve", "D. Check valve"], a: 2 },
    { q: "What is the minimum diameter of a vent for a water closet?", choices: ["A. 2\"", "B. 1 1/2\"", "C. 3\"", "D. 4\""], a: 0 },
    { q: "The process of joining two plastic pipes using a chemical solvent.", choices: ["A. Welding", "B. Brazing", "C. Solvent welding", "D. Gluing"], a: 2 },
    { q: "What is the standard height of a garden bibb from the ground?", choices: ["A. 30 cm", "B. 45 cm", "C. 60 cm", "D. 15 cm"], a: 1 },
    { q: "A tank used to store rainwater for domestic use.", choices: ["A. Cistern", "B. Septic tank", "C. Sump", "D. Reservoir"], a: 0 },
    { q: "What is the minimum size of a house sewer for a large building?", choices: ["A. 4\"", "B. 6\"", "C. 8\"", "D. 10\""], a: 1 },
    { q: "The part of the trap that prevents water from being siphoned out.", choices: ["A. Vent", "B. Dip", "C. Crown weir", "D. Trap arm"], a: 0 },
    { q: "What is the standard height of a sink faucet from the floor?", choices: ["A. 90 cm", "B. 100 cm", "C. 110 cm", "D. 120 cm"], a: 1 },
    { q: "A pipe that carries steam from a boiler.", choices: ["A. Steam line", "B. Condensate line", "C. Riser", "D. Main"], a: 0 },
    { q: "What is the minimum diameter of a vent for a bathtub?", choices: ["A. 1 1/4\"", "B. 1 1/2\"", "C. 2\"", "D. 3\""], a: 1 },
    { q: "The process of testing a plumbing system with water pressure.", choices: ["A. Water test", "B. Air test", "C. Smoke test", "D. Peppermint test"], a: 0 },
    { q: "What is the standard height of a mop sink from the floor?", choices: ["A. 15 cm", "B. 30 cm", "C. 45 cm", "D. 0 cm"], a: 0 },
    { q: "A valve used to divert water from a tub to a shower head.", choices: ["A. Diverter", "B. Mixing valve", "C. Gate valve", "D. Globe valve"], a: 0 },
    { q: "What is the minimum size of a vent for a bidet?", choices: ["A. 1 1/4\"", "B. 1 1/2\"", "C. 2\"", "D. 3\""], a: 0 },
    { q: "The part of the plumbing system that carries waste to a septic tank.", choices: ["A. Building sewer", "B. Building drain", "C. Main", "D. Branch"], a: 0 },
    { q: "What is the standard height of a urinal flush valve handle?", choices: ["A. 100 cm", "B. 110 cm", "C. 120 cm", "D. 90 cm"], a: 1 },
    { q: "A pipe that carries hot water from a heater to fixtures.", choices: ["A. Hot water line", "B. Cold water line", "C. Riser", "D. Main"], a: 0 },
    { q: "What is the minimum diameter of a vent for a floor drain?", choices: ["A. 1 1/2\"", "B. 2\"", "C. 3\"", "D. 4\""], a: 1 },
    { q: "The process of removing scale from a water pipe.", choices: ["A. Descaling", "B. Flushing", "C. Purging", "D. Cleaning"], a: 0 },
    { q: "What is the standard height of a kitchen countertop?", choices: ["A. 80 cm", "B. 85 cm", "C. 90 cm", "D. 95 cm"], a: 2 },
    { q: "A valve used to control the flow of gas.", choices: ["A. Gas cock", "B. Gate valve", "C. Ball valve", "D. Globe valve"], a: 0 },
    { q: "What is the minimum size of a vent for a laundry tub?", choices: ["A. 1 1/4\"", "B. 1 1/2\"", "C. 2\"", "D. 3\""], a: 1 },
    { q: "The part of the plumbing system that carries waste to a public sewer.", choices: ["A. House sewer", "B. House drain", "C. Main", "D. Lateral"], a: 0 },
    { q: "What is the standard height of a shower head for tall people?", choices: ["A. 200 cm", "B. 210 cm", "C. 220 cm", "D. 190 cm"], a: 1 },
    { q: "A pipe that carries compressed air.", choices: ["A. Air line", "B. Vent", "C. Stack", "D. Riser"], a: 0 },
    { q: "What is the minimum diameter of a vent for a slop sink?", choices: ["A. 1 1/2\"", "B. 2\"", "C. 3\"", "D. 4\""], a: 1 },
    { q: "The process of insulating a water pipe to prevent freezing.", choices: ["A. Lagging", "B. Wrapping", "C. Coating", "D. Covering"], a: 0 },
    { q: "What is the standard height of a bathroom vanity?", choices: ["A. 75 cm", "B. 80 cm", "C. 85 cm", "D. 90 cm"], a: 1 },
    { q: "A valve used to control the flow of oil.", choices: ["A. Gate valve", "B. Globe valve", "C. Needle valve", "D. Ball valve"], a: 2 },
    { q: "What is the minimum size of a vent for a urinal?", choices: ["A. 1 1/2\"", "B. 2\"", "C. 1 1/4\"", "D. 3\""], a: 0 }
        
    ],
    2: [
        { q: "Plumbing fixtures shall be made of smooth non-absorbent material, free from concealed fouling surfaces and shall be located in ventilated enclosures.", choices: ["A. Principle No. 1", "B. Principle No. 5", "C. Principle No. 7", "D. Principle No. 9"], a: 0 },
    { q: "What type of cleanout plug shall be installed in places prone to passing personnel or vehicles?", choices: ["A. Raised head cleanout plug", "B. Countersunk cleanout plug", "C. Hubless blind plug", "D. None of these"], a: 1 },
    { q: "A type of septic tank that is prohibited.", choices: ["A. Steel", "B. Wooden", "C. Plastic", "D. Concrete"], a: 1 },
    { q: "Polyetylene pipe is black and is used for cold water and sprinkler system. Diameter sizes range from 1/2 to 2\". How is polyethylene pipe represented?", choices: ["A. PPE", "B. PPR", "C. PVC", "D. PE"], a: 3 },
    { q: "Who was the President of the Republic of the Philippines who signed the 'Plumbing Law of the Philippines'?", choices: ["A. Pres. Ramon Magsaysay", "B. Pres. Elpidio Quirino", "C. Pres. Ferdinand Marcos", "D. Pres. Diosdado Macapagal"], a: 0 },
    { q: "If it is impractical to install horizontal drainage piping at the minimum slope, what is the least required slope allowed?", choices: ["A. 0.5%", "B. 1.0%", "C. 1.5%", "D. 2.0%"], a: 1 },
    { q: "What do you call the sum of the quotients of the individual sewers and their velocity when flowing full?", choices: ["A. Inlet time", "B. Elapsed time", "C. Time of concentration", "D. Running time"], a: 2 },
    { q: "What tube is plastic, colored black, oval shaped, and used as water service connection from the main to the meter?", choices: ["A. Polybutylene pipe", "B. Polyethylene pipe", "C. ABS pipe", "D. PVC pipe"], a: 1 },
    { q: "What is the fixture that is directly connected to drainage system?", choices: ["A. Water closet", "B. Drinking fountain", "C. Soda fountain", "D. Lavatory"], a: 0 },
    { q: "Who is the present designated chairman of unification and integration of MASTER PLUMBING profession?", choices: ["A. Engr. Camilet", "B. Engr. Mangila", "C. Engr. Simbulan", "D. Arch. Abellano"], a: 1 },
    { q: "A connection to the public sewer, or private sewage disposal system, is required for:", choices: ["A. Buildings with plumbing fixture", "B. Buildings with or without plumbing fixtures", "C. Buildings with emergency drain system", "D. Buildings with storm drain system"], a: 0 },
    { q: "How many equivalent water supply fixtures units has flush tank type of water closet that is for private use?", choices: ["A. 2", "B. 3", "C. 4", "D. 5"], a: 1 },
    { q: "What type of concealed connection of fixtures shall be provided with access panel at least 0.3m for easy inspection?", choices: ["A. Ball and socket", "B. Hubless", "C. Slip joint", "D. Flanged"], a: 2 },
    { q: "Fee for one unit of plumbing in plumbing permit application.", choices: ["A. P 5.00", "B. P 15.00", "C. P 12.00", "D. P 10.00"], a: 0 },
    { q: "Number of years of experience required to become an appointed member of the board of Master Plumber.", choices: ["A. 2", "B. 3", "C. 5", "D. 10"], a: 3 },
    { q: "Minimum supply pipe for lavatory using PPR PN16 is:", choices: ["A. 25mmф", "B. 20 mm", "C. 19 mm", "D. 15 mm"], a: 3 },
    { q: "First school to offer Plumbing Engineering course.", choices: ["A. University of the Philippines", "B. University of Santo Tomas", "C. Feati University", "D. Adamson University"], a: 2 },
    { q: "Upon issuance of plumbing permit, plumbing installation should commence within how many days?", choices: ["A. 30", "B. 60", "C. 120", "D. 365"], a: 3 },
    { q: "What is the maximum vertical support of plastic pipes?", choices: ["A. 1.0 m", "B. 1.2 m", "C. 1.5 m", "D. 2.0 m"], a: 0 },
    { q: "B & S as pipe ends stands for:", choices: ["A. Brown and Sharpe", "B. Ball and Seal", "C. Bell and Spigot", "D. Branch and Socket"], a: 2 },
    { q: "Faucets and diverters shall be connected so that the cold water supply is located at:", choices: ["A. Left side", "B. Right side", "C. Either side", "D. Both sides"], a: 1 },
    { q: "Which of the following shall not be installed inside the public toilet rooms?", choices: ["A. Bidet", "B. Waterless urinal", "C. Lavatory", "D. Drinking fountain"], a: 3 },
    { q: "What is the color code for drain pipes manufactured with toxic components?", choices: ["A. Orange, gray and white", "B. Gray, orange and brown", "C. Gray, blue and green", "D. Brown, green and yellow"], a: 1 },
    { q: "For a vertical drainage line, what is the allowed degree of the branch to be used?", choices: ["A. 60", "B. 45", "C. 30", "D. 10"], a: 1 },
    { q: "What is the minimum diameter of pump discharge from a sump having a water closet connected thereto?", choices: ["A. 54.8mm", "B. 56.8mm", "C. 52.8mm", "D. 50.8mm"], a: 3 },
    { q: "Except for repairs, which joints are prohibited on new building sewers?", choices: ["A. Bell and spigot", "B. Cement mortar joints", "C. PVC coupling", "D. Teflon tape"], a: 1 },
    { q: "What sewage includes waste from metal and chemical plants, oil refineries, and breweries?", choices: ["A. Residential", "B. Institutional", "C. Industrial", "D. Commercial"], a: 2 },
    { q: "Minimum trap and trap arm size for lavatory as per plumbing code.", choices: ["A. 63mm", "B. 51mm", "C. 38mmφ", "D. 32mm"], a: 3 },
    { q: "The drain sizing approach, when assigning DFU values, begins with:", choices: ["A. The building drain", "B. The building drainage", "C. The most upstream fixtures", "D. The building sewer"], a: 2 },
    { q: "Before offsetting horizontally to join the vent, vent shall rise vertically at least 152 mm above the:", choices: ["A. Fixture drain", "B. Tailpiece", "C. Trap weir", "D. Flood level rim"], a: 3 },
    { q: "Modern plumbing requires coordination between Master Plumbers, Architects, and Engineers to be:", choices: ["A. Sufficient", "B. Resilient", "C. Efficient and economical", "D. Advanced"], a: 2 },
    { q: "All water supply, drainage, venting system and all fixtures and their traps.", choices: ["A. Plumbing system", "B. Piping system", "C. Sewer system", "D. Sanitary system"], a: 0 },
    { q: "Injuring falsely the reputation of another Registered Master Plumber is a violation of:", choices: ["A. Code of Ethics No. 2", "B. Code of Ethics No. 3", "C. Code of Ethics No. 5", "D. Code of Ethics No. 7"], a: 3 },
    { q: "What is the Plumbing Law of the Philippines?", choices: ["A. RA 1364", "B. RA 9514", "C. RA 1096", "D. RA 1378"], a: 3 },
    { q: "Minimum height of trap water seal.", choices: ["A. 25 mm", "B. 51 mm", "C. 76 mm", "D. 102 mm"], a: 1 },
    { q: "Requirement for at least one water closet and one kitchen sink in a dwelling unit.", choices: ["A. Principle No. 5", "B. Principle No. 6", "C. Principle No. 7", "D. Principle No. 8"], a: 1 },
    { q: "Any change/addition/modification in construction or occupancy.", choices: ["A. Alteration", "B. Repair", "C. Renovation", "D. Change"], a: 0 },
    { q: "Depositing ashes, cinders, or flammable liquids into plumbing fixtures is prohibited by:", choices: ["A. Section 1202.1", "B. Section 1202.2", "C. Section 1202.3", "D. Section 1202.4"], a: 0 },
    { q: "A vertical vent that is a continuation of the drain to which it connects.", choices: ["A. Branch vent", "B. Relief vent", "C. Vent stack through roof", "D. Continuous vent"], a: 3 },
    { q: "Plumbing fixtures shall be supplied with water in sufficient volume and pressure.", choices: ["A. Principle No. 1", "B. Principle No. 2", "C. Principle No. 3", "D. Principle No. 4"], a: 2 },
    { q: "Who is allowed to acquire a plumbing permit?", choices: ["A. Architect", "B. Master Plumber", "C. Owner", "D. Contractor"], a: 2 },
    { q: "Required type of water closet used for public spaces.", choices: ["A. Elongated type", "B. Round type", "C. Wall hung", "D. Squat type"], a: 0 },
    { q: "Minimum age of a Master Plumber to qualify as a member of the board.", choices: ["A. 21", "B. 25", "C. 30", "D. 35"], a: 2 },
    { q: "Plumbing plans for all types of occupancy must be signed and sealed by a Master Plumber.", choices: ["A. Up to 20 units", "B. Up to 20 plumbing units", "C. Up to 3-storeys", "D. Without limitations"], a: 3 },
    { q: "Premises must be provided with pure and wholesome water, free from backflow hazards.", choices: ["A. Principle No. 1", "B. Principle No. 2", "C. Principle No. 3", "D. Principle No. 4"], a: 1 },
    { q: "Cast Iron fittings up to 51 mm used for potable water shall be:", choices: ["A. Threaded", "B. Hubless", "C. Galvanized", "D. Bitumastic coated"], a: 2 },
    { q: "Adjustable tubing connection with compression nut, friction ring, and washer.", choices: ["A. Male adaptor", "B. Coupling", "C. Slip joint", "D. Plug"], a: 2 },
    { q: "Two or more similar adjacent fixtures discharging into a common horizontal branch.", choices: ["A. Set of fixtures", "B. Battery of fixtures", "C. Group of fixtures", "D. Unit of fixtures"], a: 1 },
    { q: "All materials used in plumbing shall be properly marked at the factory by the:", choices: ["A. Administrative Authority", "B. Supplier", "C. Manufacturer", "D. Master Plumber"], a: 2 },
    { q: "Temporary workingmen facilities require one water closet and one urinal for each:", choices: ["A. 10 workmen", "B. 20 workmen", "C. 30 workmen", "D. 40 workmen"], a: 2 },
    { q: "Test to determine absorption rate of soil for septic drain fields.", choices: ["A. Percolation test", "B. Drain field test", "C. Leaching test", "D. Absorption test"], a: 0 },
    { q: "How many items are enumerated in the Master Plumber's Code of Ethics?", choices: ["A. 5", "B. 6", "C. 7", "D. 8"], a: 2 },
    { q: "Soil or waste system where all piping are of threaded pipe and recessed drainage fittings.", choices: ["A. Drainage system", "B. Plumbing system", "C. Piping system", "D. Durham system"], a: 3 },
    { q: "Minimum trench bottom area in sqm for each system of disposal field.", choices: ["A. 10", "B. 12", "C. 14", "D. 16"], a: 2 },
    { q: "A 2\" x 4\" wood wall stud is actually:", choices: ["A. 1 1/2\" x 4\"", "B. 1 1/2\" x 3 1/2\"", "C. 2\" x 4\"", "D. 2\" x 3 1/2\""], a: 1 },
    { q: "Which fixture may NOT be indirectly connected to a drainage system?", choices: ["A. Drinking fountain", "B. Commercial dishwasher", "C. Water softener backwash", "D. Sterilizer"], a: 1 },
    { q: "Vents that serve a single fixture are called:", choices: ["A. Only four", "B. Only three", "C. Only two", "D. Individual vents"], a: 3 },
    { q: "Minimum requirement for the slope of horizontal drainage pipes between manholes.", choices: ["A. 4%", "B. 3%", "C. 2%", "D. 1%"], a: 2 },
    { q: "Section stating no manual flushometer shall flush more than one urinal.", choices: ["A. Sec 401", "B. Sec 408", "C. Sec 305", "D. Sec 314"], a: 1 },
    { q: "Rainwater drains from roofs shall discharge to the gutter or:", choices: ["A. Drainage system", "B. STP", "C. Outside the building", "D. Inside the building"], a: 2 },
    { q: "Cleanouts may be omitted on short horizontal drainage pipe at a slope of:", choices: ["A. 135 deg", "B. 72 deg", "C. 45 deg", "D. 60 deg"], a: 1 },
    { q: "Valve installed on the cold water supply pipe to each water heater.", choices: ["A. Check globe valve", "B. Fullway gate valve", "C. Butterfly valve", "D. Angle valve"], a: 1 },
    { q: "If applying air test to the entire system, all openings are closed except the:", choices: ["A. Lowest", "B. Highest", "C. Successive lowest", "D. Successive highest"], a: 1 },
    { q: "Indirect waste pipes longer than 4.1 meters must be:", choices: ["A. Vented", "B. Trapped and vented", "C. Water sealed", "D. Not vented"], a: 0 },
    { q: "Trenches shall be back-filled in thin layers of ____ above the top of pipes.", choices: ["A. 600 mm", "B. 300 mm", "C. 900 mm", "D. 1200 mm"], a: 1 },
    { q: "All wet-vented fixtures shall be:", choices: ["A. On every 5th floor", "B. On the same floor level", "C. In every fixture", "D. Dry vented"], a: 1 },
    { q: "Galvanized steel pipe used above ground shall be kept at least:", choices: ["A. 75 mm", "B. 102 mm", "C. 125 mm", "D. 152 mm"], a: 3 },
    { q: "Drains shall have a total net inlet area not less than ___ times the outlet pipe area.", choices: ["A. One half", "B. One", "C. Two", "D. Three"], a: 2 },
    { q: "Gutter has a ____ bottom.", choices: ["A. Circular", "B. Semi-circular", "C. Great circle", "D. Big circle"], a: 1 },
    { q: "In fixture supply pipings, ____ are exposed for faculty in maintenance.", choices: ["A. Expansion joints", "B. Slip joints", "C. Unions", "D. Cleanouts"], a: 1 },
    { q: "Cast-iron pipe stacks shall be supported at:", choices: ["A. Base and each floor", "B. Every other storey", "C. Interval of 10 ft", "D. Interval of 5 ft"], a: 0 },
    { q: "Maximum trap loading for 2\" shall be:", choices: ["A. 2 FU", "B. 3 FU", "C. 4 FU", "D. 6 FU"], a: 2 },
    { q: "Waste of holy water at church altar (sacrarium) must be disposed:", choices: ["A. Into indirect waste", "B. Directly into the ground", "C. Into toxic waste", "D. Into acid waste"], a: 1 },
    { q: "Interceptors for sand shall have a water seal of not less than:", choices: ["A. 51 mm", "B. 76 mm", "C. 102 mm", "D. 152 mm"], a: 3 },
    { q: "The minimum size of gas piping supply to a mobile home is:", choices: ["A. 3/4\"", "B. 1/2\"", "C. 1\"", "D. 2\""], a: 0 },
    { q: "All necessary requirements including plans should be submitted in ___ sets.", choices: ["A. 2", "B. 3", "C. 5", "D. 6"], a: 2 },
    { q: "Plumbing permit nullifies if work is suspended/abandoned for ___ days.", choices: ["A. 120", "B. 150", "C. 180", "D. 365"], a: 2 },
    { q: "A device installed in a drainage system to prevent reverse flow.", choices: ["A. Backwater valve", "B. Backvent valve", "C. Back siphonage valve", "D. Backflow valve"], a: 0 },
    { q: "Minimum finished interior area of shower compartments.", choices: ["A. 0.8 sqm", "B. 0.6 sqm", "C. 1.2 sqm", "D. 1.4 sqm"], a: 1 },
    { q: "Which code was the RNPCP derived from?", choices: ["A. ASPE", "B. NPC", "C. IPC", "D. UPC"], a: 3 },
    { q: "Valves up to 51 mm in size shall be:", choices: ["A. Cast iron", "B. Brass", "C. Galvanized", "D. Plastic"], a: 1 },
    { q: "Maximum trap loading having 6 FU shall be:", choices: ["A. 51 mm", "B. 63 mm", "C. 76 mm", "D. 106 mm"], a: 2 },
    { q: "The bottom of trenches deeper than footing of adjacent building must be at least ___ therefrom.", choices: ["A. 60 deg", "B. 30 deg", "C. 45 deg", "D. 90 deg"], a: 2 },
    { q: "Tee with three connections each measuring 2\" is a:", choices: ["A. 2\" trap", "B. 2\" x 2\" tee", "C. 2\" x 2\" x 2\" tee", "D. 2\" tee"], a: 3 },
    { q: "A saw used to productively cut threaded rod is a:", choices: ["A. Demolition saw", "B. Portable band saw", "C. Jig saw", "D. Reciprocating saw"], a: 1 },
    { q: "Minimum horizontal offset permitted in a 3\" soil stack serving as a wet vent.", choices: ["A. 1.80 m", "B. 1.20 m", "C. 2.50 m", "D. 3.50 m"], a: 1 },
    { q: "No seepage pit shall be installed where percolation rate is less than 2.54 cm in:", choices: ["A. 30 minutes", "B. 60 minutes", "C. 15 minutes", "D. 45 minutes"], a: 0 },
    { q: "Access panel dimension for concealed connections for inspection and repair.", choices: ["A. 0.3 m", "B. 0.5 m", "C. 1.0 m", "D. 3.0 m"], a: 0 },
    { q: "A drainage pipe that passes through at least one story as a drain pipe.", choices: ["A. Sanitary sewer", "B. Soil or waste stack", "C. Spigot", "D. Soil pipe"], a: 1 },
    { q: "Non-watertight lined excavation permitting liquid to seep through bottom and sides.", choices: ["A. Privy", "B. Cesspool", "C. Disposal field", "D. Seepage pit"], a: 1 },
    { q: "Slaughter houses shall drain into a grease interceptor through a:", choices: ["A. Drainage system", "B. Screening device", "C. Either A or B", "D. None"], a: 1 },
    { q: "Joints in copper pans or liners shall be:", choices: ["A. 6.8 kg asphalt felt", "B. Flared or soldered", "C. Soldered or brazed", "D. Burned"], a: 3 },
    { q: "Septic tank should be at least ___ meters away from water supply wells.", choices: ["A. 10", "B. 15", "C. 20", "D. 30"], a: 1 },
    { q: "Solder and fluxes with lead content exceeding ___ are prohibited for potable water.", choices: ["A. 0.001", "B. 0.002", "C. 0.005", "D. 0.008"], a: 1 },
    { q: "What do CS and PS mean?", choices: ["A. Commercial Specification and Product Specification", "B. Commercial Standards and Product Standards", "C. Commercial Systems and Product Systems", "D. Commercial Sizes and Product Size"], a: 1 },
    { q: "What is AVB in backflow prevention devices?", choices: ["A. Atmospheric Volume Breaker", "B. Atmospheric Vacuum Breaker", "C. Atmospheric Velocity Breaker", "D. Atmospheric Valve Breaker"], a: 1 },
    { q: "Part of plumbing system from 4-5 feet from foundation to junction with another sewer.", choices: ["A. House sewer", "B. Storm sewer", "C. Sanitary sewer", "D. House drain"], a: 0 },
    { q: "The measure of inertia forces to viscous forces describing flow type.", choices: ["A. Reynolds number", "B. Froude number", "C. Moody number", "D. Weber number"], a: 0 },
    { q: "It consists of 180 degree bends with inside and outside threads.", choices: ["A. Return bend", "B. Offset", "C. Double offset bend", "D. U shaped"], a: 0 },
    { q: "Type of joint used for cast iron soil pipe with bell and spigot ends.", choices: ["A. Caulked joint", "B. Threaded joint", "C. Soldered joint", "D. Solvent joint"], a: 0 }
    ],
    3: [
        {
    q: "All premises intended for human habitation, occupancy or use shall be provided with a supply of pure and wholesome water, neither connected with unsafe water supplies nor subject to hazards of backflow or back-siphonage.",
    choices: ["A. Principle No. 1", "B. Principle No. 2", "C. Principle No. 4", "D. Principle No. 22"],
    a: 0
  },
  {
    q: "The individual water supply shall be adequate to provide and maintain at all times a supply of water sufficient in volume and pressure to enable the fixtures to function satisfactorily.",
    choices: ["A. Principle No. 1", "B. Principle No. 2", "C. Principle No. 3", "D. Principle No. 8"],
    a: 1
  },
  {
    q: "Devices for heating and storing water shall be so designed and installed as to prevent dangers from explosion through overheating.",
    choices: ["A. Principle No. 2", "B. Principle No. 3", "C. Principle No. 6", "D. Principle No. 13"],
    a: 1
  },
  {
    q: "Every building having plumbing fixtures and installed on a lot abutting a street, alley, or easement in which there is a public sewer shall be connected to the public sewer system.",
    choices: ["A. Principle No. 4", "B. Principle No. 5", "C. Principle No. 16", "D. Principle No. 21"],
    a: 0
  },
  {
    q: "Each family dwelling unit on premises abutting on a sewer or with a private sewage-disposal system shall have at least one water closet and one kitchen-type sink.",
    choices: ["A. Principle No. 4", "B. Principle No. 5", "C. Principle No. 6", "D. Principle No. 19"],
    a: 1
  },
  {
    q: "Plumbing fixtures shall be made of smooth non-absorbent material, free from concealed fouling surfaces and shall be located in ventilated enclosures.",
    choices: ["A. Principle No. 5", "B. Principle No. 6", "C. Principle No. 15", "D. Principle No. 19"],
    a: 1
  },
  {
    q: "The drainage system shall be designed, constructed and maintained to guard against fouling, deposit of solids and clogging, and with adequate cleanouts so arranged that the pipes may be readily cleaned.",
    choices: ["A. Principle No. 7", "B. Principle No. 8", "C. Principle No. 10", "D. Principle No. 13"],
    a: 0
  },
  {
    q: "The piping of the plumbing system shall be of durable material, free from defective workmanship and so designed and constructed as to give satisfactory service for its reasonable expected life.",
    choices: ["A. Principle No. 7", "B. Principle No. 8", "C. Principle No. 20", "D. Principle No. 22"],
    a: 1
  },
  {
    q: "Each fixture directly connected to the drainage system shall be equipped with a water-sealed trap.",
    choices: ["A. Principle No. 9", "B. Principle No. 10", "C. Principle No. 11", "D. Principle No. 17"],
    a: 0
  },
  {
    q: "The drainage system shall be designed to provide an adequate circulation of air in all pipes with no danger of siphonage, aspiration, or forcing of trap seals under conditions of ordinary use.",
    choices: ["A. Principle No. 9", "B. Principle No. 10", "C. Principle No. 11", "D. Principle No. 22"],
    a: 1
  },
  {
    q: "Each vent terminal shall extend to the outer air and be so installed as to preclude the possibility of clogging and the return of foul air to the building.",
    choices: ["A. Principle No. 10", "B. Principle No. 11", "C. Principle No. 12", "D. Principle No. 15"],
    a: 1
  },
  {
    q: "The plumbing system shall be subjected to such tests as will effectively disclose all defects and leaks in the work.",
    choices: ["A. Principle No. 8", "B. Principle No. 12", "C. Principle No. 18", "D. Principle No. 20"],
    a: 1
  },
  {
    q: "No substance which will clog or damage the pipes, produce explosive mixtures, or clog the pipes shall be allowed to enter the building drainage system.",
    choices: ["A. Principle No. 7", "B. Principle No. 13", "C. Principle No. 21", "D. Principle No. 22"],
    a: 1
  },
  {
    q: "Proper protection shall be provided to prevent contamination of food, water, sterile goods and similar materials by backflow of sewage. When necessary, the fixture, device or appliance shall be connected indirectly with the building drainage system.",
    choices: ["A. Principle No. 1", "B. Principle No. 14", "C. Principle No. 17", "D. Principle No. 22"],
    a: 1
  },
  {
    q: "No water closet or urinal shall be located in a room or compartment which is not properly lighted and ventilated.",
    choices: ["A. Principle No. 6", "B. Principle No. 15", "C. Principle No. 18", "D. Principle No. 19"],
    a: 1
  },
  {
    q: "If water closets or other plumbing fixtures are installed in buildings where there is no sewer within a reasonable distance, suitable provision shall be made for disposing of the building sewage by some accepted method of septic treatment.",
    choices: ["A. Principle No. 4", "B. Principle No. 16", "C. Principle No. 17", "D. Principle No. 21"],
    a: 1
  },
  {
    q: "Where a plumbing drainage system may be subject to backflow of sewage, suitable provision shall be made to prevent its overflow in the building.",
    choices: ["A. Principle No. 14", "B. Principle No. 17", "C. Principle No. 21", "D. Principle No. 22"],
    a: 1
  },
  {
    q: "All plumbing systems shall be maintained in a sanitary condition by Registered Master Plumbers.",
    choices: ["A. Principle No. 18", "B. Principle No. 19", "C. Principle No. 20", "D. Principle No. 22"],
    a: 0
  },
  {
    q: "All plumbing fixtures shall be installed with regard to spacing as to be accessible for their intended use.",
    choices: ["A. Principle No. 15", "B. Principle No. 19", "C. Principle No. 20", "D. Principle No. 22"],
    a: 1
  },
  {
    q: "Plumbing shall be installed by Registered Master Plumbers with due regard to the preservation of the strength of structural members and prevention of damage to walls and other surfaces through fixture usage.",
    choices: ["A. Principle No. 8", "B. Principle No. 18", "C. Principle No. 19", "D. Principle No. 20"],
    a: 3
  },
  {
    q: "Sewage or other waste from a plumbing system which may be deleterious to surface or subsurface waters shall not be discharged into the ground or into any waterway unless it has first been rendered innocuous through subjection to some acceptable form of treatment.",
    choices: ["A. Principle No. 4", "B. Principle No. 13", "C. Principle No. 16", "D. Principle No. 21"],
    a: 3
  },
  {
    q: "All plumbing fixtures shall be designed and installed to prevent the backflow of polluted water into the water supply system.",
    choices: ["A. Principle No. 1", "B. Principle No. 14", "C. Principle No. 17", "D. Principle No. 22"],
    a: 3
  }
    ],
    4: [
        { q: "All premises intended for human habitation... shall be provided with a supply of pure and wholesome water.", choices: ["A. Principle 1", "B. Principle 2", "C. Principle 3", "D. Principle 4"], a: 0 },
    { q: "The individual water supply shall be adequate to provide... sufficient volume and pressure.", choices: ["A. Principle 1", "B. Principle 2", "C. Principle 5", "D. Principle 10"], a: 1 },
    { q: "Devices for heating and storing water shall be designed... to prevent dangers from explosion through overheating.", choices: ["A. Principle 2", "B. Principle 3", "C. Principle 8", "D. Principle 13"], a: 1 },
    { q: "Every building having plumbing fixtures... on a lot abutting a street with a public sewer shall be connected to the public sewer system.", choices: ["A. Principle 4", "B. Principle 5", "C. Principle 16", "D. Principle 17"], a: 0 },
    { q: "Each family dwelling unit... shall have at least one water closet and one kitchen-type sink.", choices: ["A. Principle 4", "B. Principle 5", "C. Principle 15", "D. Principle 19"], a: 1 },
    { q: "Plumbing fixtures shall be made of smooth non-absorbent material, free from concealed fouling surfaces.", choices: ["A. Principle 5", "B. Principle 6", "C. Principle 10", "D. Principle 20"], a: 1 },
    { q: "The drainage system shall be designed... to guard against fouling, deposit of solids and clogging.", choices: ["A. Principle 7", "B. Principle 8", "C. Principle 9", "D. Principle 13"], a: 0 },
    { q: "The piping... shall be of durable material, free from defective workmanship.", choices: ["A. Principle 6", "B. Principle 7", "C. Principle 8", "D. Principle 12"], a: 2 },
    { q: "Each fixture directly connected to the drainage system shall be equipped with a water-sealed trap.", choices: ["A. Principle 9", "B. Principle 10", "C. Principle 11", "D. Principle 22"], a: 0 },
    { q: "The drainage system shall be designed to provide an adequate circulation of air in all pipes.", choices: ["A. Principle 9", "B. Principle 10", "C. Principle 11", "D. Principle 22"], a: 1 },
    { q: "Each vent terminal shall extend to the outer air... to preclude the possibility of clogging.", choices: ["A. Principle 10", "B. Principle 11", "C. Principle 12", "D. Principle 15"], a: 1 },
    { q: "The plumbing system shall be subjected to such tests as will effectively disclose all defects and leaks.", choices: ["A. Principle 8", "B. Principle 12", "C. Principle 18", "D. Principle 20"], a: 1 },
    { q: "No substance which will clog or damage the pipes... shall be allowed to enter the building drainage system.", choices: ["A. Principle 7", "B. Principle 13", "C. Principle 14", "D. Principle 21"], a: 1 },
    { q: "Proper protection shall be provided to prevent contamination of food, water, sterile goods... by backflow of sewage.", choices: ["A. Principle 1", "B. Principle 14", "C. Principle 17", "D. Principle 22"], a: 1 },
    { q: "No water closet or urinal shall be located in a room or compartment which is not properly lighted and ventilated.", choices: ["A. Principle 6", "B. Principle 15", "C. Principle 18", "D. Principle 19"], a: 1 },
    { q: "If there is no sewer within a reasonable distance, suitable provision shall be made for... accepted method of septic treatment.", choices: ["A. Principle 4", "B. Principle 16", "C. Principle 17", "D. Principle 21"], a: 1 },
    { q: "Where a plumbing drainage system may be subject to backflow... provision shall be made to prevent its overflow in the building.", choices: ["A. Principle 14", "B. Principle 17", "C. Principle 21", "D. Principle 22"], a: 1 },
    { q: "All plumbing systems shall be maintained in a sanitary condition by Registered Master Plumbers.", choices: ["A. Principle 18", "B. Principle 19", "C. Principle 20", "D. Principle 22"], a: 0 },
    { q: "All plumbing fixtures shall be installed with regard to spacing as to be accessible for their intended use.", choices: ["A. Principle 15", "B. Principle 19", "C. Principle 20", "D. Principle 21"], a: 1 },
    { q: "Plumbing shall be installed... with due regard to the preservation of the strength of structural members.", choices: ["A. Principle 8", "B. Principle 18", "C. Principle 20", "D. Principle 22"], a: 2 },
    { q: "Sewage... shall not be discharged into the ground or any waterway unless it has first been rendered innocuous.", choices: ["A. Principle 13", "B. Principle 16", "C. Principle 21", "D. Principle 22"], a: 2 },
    { q: "All plumbing fixtures shall be designed and installed to prevent the backflow of polluted water into the water supply system.", choices: ["A. Principle 1", "B. Principle 14", "C. Principle 17", "D. Principle 22"], a: 3 },
    { q: "The Filipino plumbers assigned to maintain systems in 'pueblos' during the 18th/19th centuries were called by the elite group to act as consultants. This elite group was known as:", choices: ["A. Thomasites", "B. Ilustrados", "C. Friar Engineers", "D. Insulares"], a: 1 },
    { q: "In 1902, who was the first Chief of the Division of Plumbing Construction and Inspection in Manila?", choices: ["A. John F. Hass", "B. Gregorio Feliciano", "C. Francisco Geronimo", "D. Tomas Geronimo"], a: 0 },
    { q: "NAMPAP was organized and registered with the SEC in what year?", choices: ["A. 1902", "B. 1935", "C. 1954", "D. 1999"], a: 1 },
    { q: "Who was the President of the Philippines who signed RA 1378 into law?", choices: ["A. Ferdinand Marcos", "B. Ramon Magsaysay", "C. Diosdado Macapagal", "D. Manuel Quezon"], a: 1 },
    { q: "What is the complete name of RA 1378?", choices: ["A. The National Building Code", "B. The Plumbing Law of the Philippines", "C. The Sanitary Code", "D. The Water Act"], a: 1 },
    { q: "In 1996, NAMPAP President Jaime M. Cabase spearheaded the updating of the Revised National Plumbing Code under whose administration?", choices: ["A. Corazon Aquino", "B. Fidel V. Ramos", "C. Joseph Estrada", "D. Gloria Arroyo"], a: 1 },
    { q: "The first 'Walled City' established by Spaniards that incorporated European plumbing standards was:", choices: ["A. Vigan", "B. Cebu", "C. Intramuros", "D. Zamboanga"], a: 2 },
    { q: "Which government body approved the 'Revised National Plumbing Code of 1999'?", choices: ["A. PRC", "B. DPWH", "C. DOH", "D. DENR"], a: 0 },
    { q: "On what specific date did President Joseph Estrada approve the 1999 Code?", choices: ["A. June 18, 1955", "B. December 21, 1999", "C. January 28, 1959", "D. November 28, 1967"], a: 1 },
    { q: "The plumbing profession took a leap in the 20th century due to the arrival of American soldiers, doctors, and teachers known as:", choices: ["A. Friars", "B. Thomasites", "C. Conquistadors", "D. Missionaries"], a: 1 },
    { q: "Who was the NAMPAP President when the Code of Ethics was first adopted?", choices: ["A. John F. Hass", "B. Gregorio Feliciano", "C. Jaime Cabase", "D. Francisco Geronimo"], a: 1 },
    { q: "The Board of Examiners for Master Plumbers was created under which act?", choices: ["A. RA 1378", "B. RA 544", "C. RA 9266", "D. RA 1080"], a: 0 },
    { q: "The first NAMPAP President was:", choices: ["A. Francisco Geronimo", "B. Mariano de Jesus", "C. John F. Hass", "D. Jaime Cabase"], a: 0 },
    { q: "Which city served as the model community for plumbing trade recognition in 1902?", choices: ["A. Quezon City", "B. Manila", "C. Baguio", "D. Davao"], a: 1 },
    { q: "Before RA 1378, what was the basis for plumbing practices in Manila?", choices: ["A. Spanish Law", "B. City Ordinance 4122", "C. The US Plumbing Code", "D. The Building Code"], a: 1 },
    { q: "The 22 Basic Principles are otherwise known as:", choices: ["A. Code of Ethics", "B. Plumbing Law", "C. International Plumbing Foundation", "D. Basic Principles of Plumbing"], a: 3 },
    { q: "The 'Friar Engineers' who built government buildings in the 17th century came from which country?", choices: ["A. USA", "B. Spain", "C. Portugal", "D. Mexico"], a: 1 },
    { q: "NAMPAP stands for:", choices: ["A. National Association of Master Plumbers of the Philippines", "B. National Master Plumbers Association of the Philippines", "C. Nationwide Allied Master Plumbers Association of the Philippines", "D. Northern Allied Master Plumbers Association of the Philippines"], a: 0 },
    { q: "The officer charged with the administration and enforcement of the Plumbing Code is the:", choices: ["A. Building Official", "B. Administrative Authority", "C. City Engineer", "D. Registered Master Plumber"], a: 1 },
    { q: "A plumbing permit is not required for the clearance of stoppages or stopping of leaks, provided that the work does not involve:", choices: ["A. Replacing valves", "B. Replacing fixtures", "C. Rearranging pipes", "D. Using a plunger"], a: 2 },
    { q: "Application for a permit shall be made on forms furnished by the:", choices: ["A. PRC", "B. NAMPAP", "C. Administrative Authority", "D. DOH"], a: 2 },
    { q: "How many sets of plans and specifications are required for a permit application?", choices: ["A. 2", "B. 4", "C. 6", "D. 8"], a: 2 },
    { q: "Who must sign and seal the plumbing plans and specifications?", choices: ["A. Civil Engineer", "B. Architect", "C. Registered and Licensed Master Plumber", "D. Contractor"], a: 2 },
    { q: "What is the validity period (in years) of a plumbing permit from the date of issuance?", choices: ["A. 6 months", "B. 1 year", "C. 2 years", "D. 5 years"], a: 1 },
    { q: "A permit expires if work is suspended or abandoned for a period of how many days?", choices: ["A. 30 days", "B. 60 days", "C. 90 days", "D. 120 days"], a: 3 },
    { q: "When a permit is expired, the fee to renew it (if work has not started) is what percentage of the original permit fee?", choices: ["A. 25%", "B. 50%", "C. 75%", "D. 100%"], a: 1 },
    { q: "Who is responsible for notifying the Administrative Authority that work is ready for inspection?", choices: ["A. The Owner", "B. The Master Plumber", "C. The Helper", "D. The Architect"], a: 1 },
    { q: "The Administrative Authority must be notified at least how many hours before an inspection is desired?", choices: ["A. 24 hours", "B. 48 hours", "C. 72 hours", "D. 1 week"], a: 0 },
    { q: "If an inspection is requested and the work is not ready, what kind of fee may be charged?", choices: ["A. Renewal fee", "B. Re-inspection fee", "C. Violation fee", "D. Surcharge"], a: 1 },
    { q: "A 'Notice of Correction' is issued when work is found to be:", choices: ["A. Completed early", "B. Defective or in violation of the code", "C. Using plastic pipes", "D. Over budget"], a: 1 },
    { q: "All plumbing systems must be tested and approved before they are:", choices: ["A. Painted", "B. Concealed or covered", "C. Sold", "D. Photographed"], a: 1 },
    { q: "If a plumbing system is found to be dangerous or unsanitary, it is classified as:", choices: ["A. A minor repair", "B. A public nuisance", "C. An aesthetic issue", "D. A structural defect"], a: 1 },
    { q: "The Administrative Authority may require the 'Uncovering' of work if it was:", choices: ["A. Covered before inspection", "B. Painted the wrong color", "C. Installed by a helper", "D. Too expensive"], a: 0 },
    { q: "What is the minimum scale for plumbing plans as per Section 102.2?", choices: ["A. 1:50", "B. 1:100", "C. No specific scale required", "D. 1:200"], a: 1 },
    { q: "The 'Administrative Authority' refers to the Building Official or the ______?", choices: ["A. Mayor", "B. Health Officer", "C. Fire Marshall", "D. Police Chief"], a: 1 },
    { q: "Changes or modifications to approved plans require:", choices: ["A. Verbal consent", "B. Written approval of the Administrative Authority", "C. No approval if small", "D. A new contract"], a: 1 },
    { q: "Which of the following does NOT require a plumbing permit?", choices: ["A. Installing a new water heater", "B. Adding a kitchen island sink", "C. Repairing a leak in a faucet", "D. Moving a floor drain"], a: 2 },
    { q: "Plumbing work must be performed under the 'direct supervision' of a:", choices: ["A. Foreman", "B. Registered and Licensed Master Plumber", "C. Building Owner", "D. Civil Engineer"], a: 1 },
    { q: "What happens to the permit if the work is not started within 1 year?", choices: ["A. It is automatically extended", "B. It becomes null and void", "C. It remains valid forever", "D. It requires a 10% fee"], a: 1 },
    { q: "The 'Plumbing Code' covers the installation of which of the following?", choices: ["A. Storm drainage", "B. Fuel gas piping", "C. Water supply", "D. All of the above"], a: 3 },
    { q: "Testing of the drainage system usually involves which substance?", choices: ["A. Air or Water", "B. Oil", "C. Smoke only", "D. Gas"], a: 0 },
    { q: "The Administrative Authority has the right to enter a building at 'reasonable times' to:", choices: ["A. Collect taxes", "B. Inspect plumbing", "C. Deliver mail", "D. Evict tenants"], a: 1 },
    { q: "A 'Certificate of Final Inspection' is issued after:", choices: ["A. The permit is paid", "B. The work is completed and passes all tests", "C. The house is sold", "D. The water is turned on"], a: 1 },
    { q: "What is the penalty for violating the Plumbing Code?", choices: ["A. There is no penalty", "B. Fine and/or imprisonment", "C. Community service", "D. Loss of citizenship"], a: 1 },
    { q: "Who provides the testing equipment for an inspection?", choices: ["A. The Administrative Authority", "B. The Master Plumber or Permit Holder", "C. The Water District", "D. The City Council"], a: 1 },
    { q: "If a person continues to work after a 'Stop Work Order' is issued, they are subject to:", choices: ["A. A promotion", "B. Additional fines/penalties", "C. A handshake", "D. Verbal warning only"], a: 1 },
    { q: "'Connection to the water supply' is prohibited until:", choices: ["A. The owner pays the bill", "B. The Administrative Authority issues an approval", "C. The pipes are painted", "D. The furniture is moved in"], a: 1 },
    { q: "When using the 'Water Test' for a drainage system, the water must be kept in the system for at least how many minutes?", choices: ["A. 5 minutes", "B. 15 minutes", "C. 30 minutes", "D. 1 hour"], a: 1 },
    { q: "Which Section of Chapter 1 discusses 'Violations and Penalties'?", choices: ["A. 101", "B. 104", "C. 107", "D. 108"], a: 3 },
    { q: "What is the requirement for 'Existing Construction' regarding plumbing?", choices: ["A. It must be demolished", "B. It can remain if not a nuisance", "C. It must be upgraded every year", "D. It requires a new permit daily"], a: 1 },
    { q: "In Section 102.1, a permit is required for any 'addition, alteration, or ______'?", choices: ["A. Cleaning", "B. Repair", "C. Painting", "D. Landscaping"], a: 1 },
    { q: "The 'Permit Fee' is typically based on the number of:", choices: ["A. Windows", "B. Fixtures", "C. Occupants", "D. Square meters"], a: 1 },
    { q: "What is 'Illegal Plumbing'?", choices: ["A. Plumbing done without a permit", "B. Plumbing using PVC", "C. Plumbing in a tall building", "D. Plumbing that is too cheap"], a: 0 },
    { q: "The Administrative Authority may 'Revoke' a permit if it was issued:", choices: ["A. To a friend", "B. Based on incorrect information or in error", "C. Too quickly", "D. On a Friday"], a: 1 },
    { q: "Which principle mentions that 'Air circulation' is necessary?", choices: ["A. Principle 5", "B. Principle 10", "C. Principle 15", "D. Principle 20"], a: 1 },
    { q: "Principle 22 focuses on preventing the backflow of ______?", choices: ["A. Rainwater", "B. Polluted water", "C. Hot water", "D. Pure water"], a: 1 },
    { q: "What must be done to sewage that is 'deleterious' to the environment?", choices: ["A. Dilute it", "B. Render it innocuous through treatment", "C. Bury it deep", "D. Send it to a landfill"], a: 1 },
    { q: "Who is the 'Authorized Agent' of the Administrative Authority?", choices: ["A. The Homeowner", "B. A Plumbing Inspector", "C. The Contractor", "D. The Mayor"], a: 1 },
    { q: "Can a Master Plumber be the 'Administrative Authority'?", choices: ["A. Yes, if appointed by the government", "B. No, never", "C. Only in private companies", "D. Only for their own house"], a: 0 },
    { q: "'Adequate cleanouts' are required by which principle?", choices: ["A. Principle 1", "B. Principle 4", "C. Principle 7", "D. Principle 11"], a: 2 },
    { q: "If a building is moved from one location to another, what is required?", choices: ["A. A new plumbing permit", "B. No permit is needed", "C. Only a verbal notice", "D. A photo of the old site"], a: 0 },
    { q: "Section 102.2 requires a 'Plan and Specification' for all projects except:", choices: ["A. High-rise buildings", "B. Hospitals", "C. Minor repairs and small additions", "D. Schools"], a: 2 },
    { q: "'Dangerous Plumbing' is defined as a system that is a ______?", choices: ["A. High cost", "B. Health hazard", "C. Ugly design", "D. Noisy system"], a: 1 },
    { q: "A 'Re-inspection' is required if:", choices: ["A. The work passes the first time", "B. The previous work was rejected", "C. The owner wants to see the work", "D. The inspector is bored"], a: 1 },
    { q: "What happens if a permit is revoked?", choices: ["A. All work must stop", "B. Work can continue if done quickly", "C. The permit fee is doubled", "D. The owner gets a refund"], a: 0 },
    { q: "What is the purpose of the 'Testing' phase?", choices: ["A. To waste water", "B. To check for leaks and defects", "C. To increase the project duration", "D. To train new plumbers"], a: 1 },
    { q: "The 'Plumbing System' includes:", choices: ["A. Water supply pipes", "B. Fixtures and traps", "C. Soil, waste and vent pipes", "D. All of the above"], a: 3 },
    { q: "Can the Administrative Authority waive the requirement for a plan?", choices: ["A. Yes, for simple work", "B. No, never", "C. Only if the owner is an engineer", "D. Only for government buildings"], a: 0 },
    { q: "What is the 'Sewer Connection' requirement for buildings on lots not abutting a public sewer?", choices: ["A. No plumbing allowed", "B. Private sewage disposal system (Septic Tank)", "C. Discharge to the street", "D. Storage in barrels"], a: 1 },
    { q: "Section 107.1 deals with what kind of maintenance?", choices: ["A. Financial", "B. Sanitary", "C. Aesthetic", "D. Structural"], a: 1 },
    { q: "When an inspector finds a violation, what document do they leave at the site?", choices: ["A. A bill", "B. A Notice of Correction", "C. A thank you note", "D. A business card"], a: 1 },
    { q: "Why is Principle 20 (Structural Integrity) important?", choices: ["A. To save money", "B. To prevent damage to walls and floors during installation", "C. To make the pipes look better", "D. To speed up the work"], a: 1 },
    { q: "'Cross-connection' is forbidden because it leads to:", choices: ["A. Lower pressure", "B. Contamination of the water supply", "C. Expensive pipes", "D. Noisy fixtures"], a: 1 },
    { q: "In the Master Plumber's Code of Ethics, a plumber should 'report any ______'?", choices: ["A. Late workers", "B. Violations of the code", "C. Expensive parts", "D. New tools"], a: 1 },
    { q: "According to the Code of Ethics, a plumber's price should be:", choices: ["A. The highest possible", "B. Just and reasonable", "C. Free", "D. Fixed by the government"], a: 1 },
    { q: "A Master Plumber should not 'injure the ______ of another fellow plumber.'", choices: ["A. Tools", "B. Reputation", "C. Vehicle", "D. House"], a: 1 },
    { q: "Which principle requires 'Smooth non-absorbent material'?", choices: ["A. Principle 1", "B. Principle 6", "C. Principle 12", "D. Principle 18"], a: 1 },
    { q: "The ultimate goal of the National Plumbing Code is to protect:", choices: ["A. The Master Plumbers", "B. The Government", "C. Public Health and Safety", "D. The environment only"], a: 2 }
    ],
    5: [
        { 
            q: "A tank measures 4m long, 2m wide, and 3m high. What is the maximum volume in liters?", 
            choices: ["240 liters", "2,400 liters", "24,000 liters", "240,000 liters"], 
            a: 2 
        },
        { 
            q: "If a sewer line has a total fall of 24 inches over 120 feet, what is the slope per foot?", 
            choices: ["0.01", "0.02", "0.03", "0.04"], 
            a: 1 
        },
        { 
            q: "How many 2-inch pipes are needed to equal the volume capacity of one 6-inch pipe?", 
            choices: ["3", "6", "9", "12"], 
            a: 2 // Calculation: (6/2)^2 = 9
        }
    ],
6: [
        { q: "Shannel’s birthday is 7 weeks and 5 days away. How many days away is her birthday?", choices: ["24 days", "54 days", "65 days", "75 days"], a: 1 },
        { q: "What is the next term of the given sequence of numbers: 1, 2, 6, 24, 120, ...?", choices: ["360", "480", "560", "720"], a: 3 }
    ],
    7: [
        { q: "A sedimentation basin is 60 feet in diameter. What is the surface area?", choices: ["2830 sq. ft", "1200 sq. ft", "1542 sq. ft", "2480 sq. ft"], a: 0 },
        { q: "Which of the following numbers can be divided evenly by 19?", choices: ["54", "63", "76", "82"], a: 2 }
    ],
    8: [
        { q: "Jenny has finished reading 30% of a 340-page novel. How many pages has she read?", choices: ["102", "106", "110", "120"], a: 0 },
        { q: "33 is 12% of what number?", choices: ["410", "330", "275", "910"], a: 2 }
    ],
    9: [
        { q: "What refers to the product of the force and the time during which a force acts?", choices: ["Impulse", "Momentum", "Power", "Energy"], a: 0 },
        { q: "Momentum is the product of:", choices: ["mass and time", "velocity and mass", "force and time", "force and mass"], a: 1 }
    ],
    10: [
        { q: "What is the unit of luminous flux?", choices: ["Candela", "Lumen", "Lux", "Footcandle"], a: 1 },
        { q: "Which of the following is equivalent to the unit 'candela'?", choices: ["lumen/m2", "foot-candle/steradian", "lux/steradian", "lumen/steradian"], a: 3 }
    ],
    11: [
        { q: "Land, buildings, plants and machinery are examples of:", choices: ["Current assets", "Trade investments", "Fixed assets", "Intangible assets"], a: 2 },
        { q: "A currency traded in a foreign exchange market for which the demand is consistently high.", choices: ["Money market", "Hard currency", "Treasury bill", "Certificate of deposit"], a: 1 }
    ],
    12: [
        { q: "What is the eccentricity of a circle?", choices: ["A. 1", "B. 0", "C. <1", "D. >1"], a: 1 },
        { q: "What is the air pressure exerted by 1 meter of water?", choices: ["A. 7.48 kPa", "B. 9.81 kPa", "C. 13.6 kPa", "D. 32.2 kPa"], a: 1 }
    ],
    13: [
        { q: "Additional information issued to prospective bidders prior to bidding date?", choices: ["Depict", "Escalate", "Assessment", "Bid bulletin"], a: 3 },
        { q: "Reduction in national income accompanied by a fall in general price levels?", choices: ["Devaluation", "Deflation", "Inflation", "Depreciation"], a: 1 }
    ],
    14: [
        { q: "This is a point where the concavity of a curve changes.", choices: ["Maximum point", "Minimum point", "Point of inflection", "Darsho's point"], a: 2 },
        { q: "Factoring is the process of expressing a polynomial as a:", choices: ["Rationalization", "Decomposition", "Product", "Darshon"], a: 2 }
    ],
    15: [
        { q: "The paper currency issued by the Central Bank.", choices: ["T-bills", "Bank note", "Check", "Coupon"], a: 1 },
        { q: "A repair job can be done by 7 people in 8.5 hours. How long for 4 people?", choices: ["4 hr 30 min", "14 hr 9 min", "4 hr 51 min", "14 hr 53 min"], a: 3 }
    ]
};




