export const designDB = {
    1: [
        { q: "A pipe support used for single run of pipe vertical position.", choices: ["A. Bracket", "B. Clamp", "C. Corbel", "D. Hanger"], a: 1 },
    { q: "A pipe support used for multiple runs of pipe horizontal position.", choices: ["A. Bracket", "B. Clamp", "C. Corbel", "D. Hanger"], a: 0 },
    { q: "A type of backflow prevention device approved for back pressure and back siphonage.", choices: ["A. Pressure Vacuum Breaker", "B. Reduced Pressure Principle Backflow", "C. Double check valve", "D. AVB"], a: 2 },
    { q: "The noisiest type of water closet flushing.", choices: ["A. reverse trap", "B. blowout", "C. washdown", "D. siphon jet"], a: 2 },
    { q: "Maximum length of a nipple.", choices: ["A. 30\"", "B. 12\"", "C. 10\"", "D. 5\""], a: 1 },
    { q: "Color code for pipeline used for electrical services.", choices: ["A. orange", "B. white", "C. black", "D. green"], a: 0 },
    { q: "Minimum weight of copper allowed to use for underground and above drainage and vent piping.", choices: ["A. Type DWV", "B. Type K", "C. Type L", "D. Type M"], a: 0 },
    { q: "Size of dry standpipe for buildings in which the highest outlet is 23m or less above the fire service connection.", choices: ["A. 38 mm", "B. 102 mm", "C. 64 mm", "D. 150 mm"], a: 1 },
    { q: "CISPI stands for __________.", choices: ["A. Case Iron Soil Piping Institute", "B. Cast-Iron and Soil Pipe Institute", "C. Casting Iron Soil Pipe Institute", "D. Cast Iron Soil Pipe Institute"], a: 3 },
    { q: "A nipple fitting is a short piece of pipe with __________.", choices: ["A. Male thread at each end", "B. Female thread at each end", "C. Male and female threads at ends", "D. None of the above"], a: 0 },
    // Items 11-22 missing from source images; answers 11.B to 22.B per key
    { q: "An airtight receptacle used to expedite the decomposition of elements contained in raw sewage...", choices: ["A. privy", "B. sewage treatment plant", "C. septic tank", "D. None of the above"], a: 2 },
    { q: "It is defined as the settling down or separation of solid matter suspended in a liquid.", choices: ["A. Evaporation", "B. flocculation", "C. sedimentation", "D. settlement"], a: 2 },
    { q: "Minimum slope or grade (in %) permitted with 100mm (4\") pipes.", choices: ["A. 2%", "B. 1%", "C. 1.5%", "D. 4%"], a: 0 },
    { q: "The lighter organic solid particles found in sewage, cesspools and septic tanks, found floating on the liquid.", choices: ["A. Sludge", "B. Septic", "C. Scum", "D. None of the above"], a: 2 },
    { q: "It is defined as the organic particles that have settled down in septic tanks, cesspools or sewage.", choices: ["A. Sludge", "B. Septic", "C. Scum", "D. None of the above"], a: 0 },
    { q: "Minimum width of a septic tank for residential dwellings.", choices: ["A. 0.9 m", "B. 1.2 m", "C. 1.0 m", "D. 1.5 m"], a: 0 },
    { q: "Minimum length of a septic tank for residential dwellings.", choices: ["A. 0.9 m", "B. 1.2 m", "C. 1.0 m", "D. 1.5 m"], a: 3 },
    { q: "Minimum depth of a septic tank for residential dwellings.", choices: ["A. 0.6 m", "B. 1.2 m", "C. 1.0 m", "D. 1.5 m"], a: 0 },
    { q: "Type of valve found in the service main... control of the water service and shut off valve.", choices: ["A. corporation Stop", "B. curb stop", "C. meter stop", "D. gate valve"], a: 0 },
    { q: "Type of valve used to prevent backflow or reversal of flow of water, usually found after the water meter.", choices: ["A. gate valve", "B. globe valve", "C. butterfly valve", "D. check valve"], a: 3 },
    { q: "Fitting used to describe the connection of the service pipe and water meter.", choices: ["A. coupling", "B. pipe", "C. nipple", "D. union patente"], a: 3 },
    { q: "Type of piping system that is characterized by threading and connecting cast iron pipes.", choices: ["A. Durham System", "B. Sovent System", "C. Sewage System", "D. All of the above"], a: 0 },
    { q: "Type of pump used to distribute water... when an upfeed system cannot provide adequate pressure.", choices: ["A. pneumatic pump", "B. fire pump", "C. water pump", "D. submersible pump"], a: 0 },
    { q: "Type of flushing valve used in commercial water closets... expels air pressure and water.", choices: ["A. flush tank", "B. angle valve", "C. flushometer valve", "D. gate valve"], a: 2 },
    { q: "Type of vent used in an island counter type kitchen sink.", choices: ["A. circuit vent", "B. loop vent", "C. looped vent", "D. individual vent"], a: 2 },
    { q: "Maximum vertical depth of liquid that a trap can contain.", choices: ["A. water seal", "B. trap seal", "C. vulcaseal", "D. air gap"], a: 1 },
    { q: "Vertical pipe that is used for the storage of water... used for fire suppression.", choices: ["A. standpipe", "B. fire hose", "C. stack", "D. run"], a: 0 },
    { q: "Type of pipe with a 180 degree bend.", choices: ["A. elbow", "B. return bend", "C. sweep", "D. wye"], a: 1 },
    { q: "Water supply fixture unit of a bath tub in a residential setting.", choices: ["A. 1", "B. 2", "C. 3", "D. 4"], a: 1 },
    { q: "Water supply fixture unit of a shower in a resort.", choices: ["A. 1", "B. 2", "C. 3", "D. 4"], a: 3 },
    { q: "A concrete sealed vault with a wooden shelter constructed for the collection of raw sewage.", choices: ["A. privy", "B. sewage treatment plant", "C. septic tank", "D. cesspool"], a: 0 },
    { q: "Hole in the ground... to allow raw contaminated sewage to leach into the ground.", choices: ["A. privy", "B. sewage treatment plant", "C. septic tank", "D. cesspool"], a: 3 },
    { q: "A common problem in traps due to inadequate ventilation.", choices: ["A. leaks", "B. foul odor", "C. trap seal loss", "D. ponding"], a: 2 },
    { q: "Type of vent that connects a battery of fixtures to a stack vent.", choices: ["A. circuit vent", "B. unit vent", "C. wet vent", "D. looped vent"], a: 0 },
    { q: "Type of vent that is shared by two fixtures of the same type.", choices: ["A. circuit vent", "B. unit vent", "C. wet vent", "D. looped vent"], a: 1 },
    { q: "Type of connection found in a looped vent, connecting the looped vent pipe to the waste pipe.", choices: ["A. bleeder", "B. joint", "C. leader", "D. none of the above"], a: 0 },
    { q: "Type of system... that eliminates the vent stack, relying on downward pressure and suction.", choices: ["A. Durham System", "B. Solvent System", "C. Sovent System", "D. All of the above"], a: 2 },
    { q: "Formula for detention time of a tank.", choices: ["A. volume/flow rate", "B. area*velocity", "C. volume/area", "D. none of the above"], a: 0 },
    { q: "NAMPAP stands for:", choices: ["A. national master plumbers' association of the philippines", "B. national master plumbers associations of the philippines", "C. national master plumbers association of the philippines", "D. national masters plumbers association of the philippines"], a: 2 },
    { q: "Type of detention pit usually found in basements... discharge waste water.", choices: ["A. pit", "B. sump pit", "C. well", "D. elevator pit"], a: 1 },
    { q: "A gate valve normally used to shut off flow of water from supply pipe.", choices: ["A. shut off valve", "B. cock", "C. flush valve", "D. relief valve"], a: 0 },
    { q: "A faucet normally turned 90 degrees to open or close.", choices: ["A. key cock", "B. compression cock", "C. ball faucet", "D. hose bibb"], a: 0 },
    { q: "Overhead tank water distribution system is a ______ system.", choices: ["A. direct", "B. indirect", "C. overhead", "D. gravity"], a: 1 },
    { q: "Things to consider when sizing the hot water tank.", choices: ["A. building design", "B. occupants", "C. heating capacity", "D. all of the above"], a: 1 },
    { q: "Minimum house sewer diameter.", choices: ["A. 3\"", "B. 4\"", "C. 5\"", "D. 6\""], a: 3 },
    { q: "Maximum distance in ft a 2 in trap from its vent.", choices: ["A. 1", "B. 2", "C. 4", "D. 5\""], a: 3 },
    { q: "Minimum clearance in front of a cleanout for a 2-inch drainage pipe.", choices: ["A. 10'", "B. 12'", "C. 16'", "D. 18'"], a: 1 },
    { q: "Minimum clearance from a terminal and a window opening in a building.", choices: ["A. 10'", "B. 12'", "C. 16'", "D. 18'"], a: 0 },
    { q: "Class 1 type occupancy water supply.", choices: ["A. residence", "B. restricted use", "C. unrestricted use", "D. none of the above"], a: 0 },
    { q: "Class 2 type occupancy water supply.", choices: ["A. residence", "B. restricted use", "C. unrestricted use", "D. none of the above"], a: 1 },
    { q: "Class 3 type occupancy water supply.", choices: ["A. residence", "B. restricted use", "C. unrestricted use", "D. none of the above"], a: 2 },
    { q: "Cause of objectionable tastes and odor of water.", choices: ["A. bacteria", "B. algae", "C. virus", "D. pathogens"], a: 1 },
    { q: "Pipe from the street water main to the building served.", choices: ["A. service pipe", "B. building supply", "C. building pipe", "D. fixture supply"], a: 0 },
    { q: "Pipe carrying potable water from the water meter to a building...", choices: ["A. service pipe", "B. building supply", "C. building pipe", "D. fixture supply"], a: 1 },
    { q: "Water supply pipe connecting the fixture with the fixture branch.", choices: ["A. service pipe", "B. building supply", "C. building pipe", "D. fixture supply"], a: 3 },
    { q: "Vent installed so that one vent pipe serves two traps.", choices: ["A. circuit vent", "B. unit vent", "C. wet vent", "D. looped vent"], a: 1 },
    { q: "A group vent which starts in front of the extreme fixture connection on a horizontal branch.", choices: ["A. circuit vent", "B. unit vent", "C. wet vent", "D. looped vent"], a: 0 },
    { q: "Vent used for islands and lavatories away from the wall and vent branch.", choices: ["A. circuit vent", "B. unit vent", "C. wet vent", "D. looped vent"], a: 3 },
    { q: "System used to produce a more efficient circulation of hot water to upper floors.", choices: ["A. Upfeed and Gravity Return System", "B. Pump Circuit System", "C. Downfeed and Gravity Return System", "D. None of the above"], a: 1 },
    { q: "System where hot water rises on the highest point... travels to the fixture via gravity.", choices: ["A. Upfeed and Gravity Return System", "B. Pump Circuit System", "C. Downfeed and Gravity Return System", "D. None of the above"], a: 2 },
    { q: "Circulation of hot water by means of mechanical device.", choices: ["A. Upfeed and Gravity Return System", "B. Pump Circuit System", "C. Downfeed and Gravity Return System", "D. None of the above"], a: 1 },
    { q: "A vent to relieve the pressure ahead of moving effluent in a horizontal fixture branch.", choices: ["A. yoke vent", "B. stack vent", "C. unit vent", "D. relief vent"], a: 3 },
    { q: "A pipe connecting upward from a soil or waste stack to a vent stack... preventing pressure changes.", choices: ["A. yoke vent", "B. stack vent", "C. unit vent", "D. relief vent"], a: 0 },
    { q: "Yoke vent is required for every ____ floors.", choices: ["A. 3", "B. 5", "C. 10", "D. 6"], a: 1 },
    { q: "House sewer extends ____ m from the foundation of the wall of the building.", choices: ["A. 0.6", "B. 0.3", "C. 0.4", "D. 0.1"], a: 0 },
    { q: "Lowest part of the inside face of any pipe.", choices: ["A. convert", "B. invert", "C. crown", "D. head"], a: 1 },
    { q: "Highest part of the inside face of any pipe.", choices: ["A. spring line", "B. invert", "C. crown", "D. head"], a: 2 },
    { q: "The midpoint level of a pipe.", choices: ["A. spring line", "B. invert", "C. crown", "D. center"], a: 0 },
    { q: "Order of valves for water connection.", choices: ["A. check valve, water meter, gate valve", "B. globe valve, water meter, gate valve", "C. gate valve, water meter, check valve", "D. check valve, water meter, globe valve"], a: 2 },
    { q: "Underground system portion which cannot drain by gravity into the building sewer.", choices: ["A. building subdrain", "B. subsoil drain", "C. storm drain", "D. French drain"], a: 0 },
    { q: "Underground drainpipe that receives only sub-surface or seepage water... to a sump.", choices: ["A. building subdrain", "B. subsoil drain", "C. storm drain", "D. French drain"], a: 1 },
    { q: "A covering for trench normally used for provincial cities using the curb and gutter.", choices: ["A. building subdrain", "B. subsoil drain", "C. storm drain", "D. French drain"], a: 3 },
    { q: "Designed to allow quick and convenient disconnection of pipes for maintenance.", choices: ["A. onion", "B. coupling", "C. flange", "D. union"], a: 3 },
    { q: "Used on CIPs using a compression joint.", choices: ["A. Teflon tape", "B. neoprene rubber compression gasket", "C. o-ring", "D. none of the above"], a: 1 },
    { q: "Used on CIPs with hubless joint.", choices: ["A. Teflon tape", "B. neoprene rubber compression gasket", "C. o-ring", "D. none of the above"], a: 2 },
    { q: "Joinery used for galvanized iron, steel, and plastic pipes.", choices: ["A. bell and spigots", "B. female threads", "C. male threads", "D. threaded joints"], a: 3 },
    { q: "Pipe joint material should be applied on:", choices: ["A. bell and spigots", "B. female threads", "C. male threads", "D. threaded joints"], a: 2 },
    { q: "Joinery used in concrete pipes.", choices: ["A. bell and spigots", "B. cement mortar joint", "C. burned lead joint", "D. threaded joints"], a: 1 },
    { q: "Used for lead joinery.", choices: ["A. bell and spigots", "B. cement mortar joint", "C. burned lead joint", "D. threaded joints"], a: 2 },
    { q: "Joint consisting of 2 companion flanges bolted together and made leak proof by a gasket.", choices: ["A. bell and spigots", "B. flange joint", "C. burned lead joint", "D. heat fusion joint"], a: 1 },
    { q: "Joint used on thermoplastic pipes where pieces are heat and pressed together.", choices: ["A. bell and spigots", "B. flange joint", "C. burned lead joint", "D. heat fusion joint"], a: 3 },
    { q: "Symbol representing a flange joint.", choices: ["A. -|N|-", "B. -N-", "C. --x N x--", "D. --o N o--"], a: 0 },
    { q: "Symbol representing a welded joint.", choices: ["A. -|N|-", "B. -N-", "C. --x N x--", "D. --o N o--"], a: 1 },
    { q: "Symbol representing a screwed joint.", choices: ["A. -|N|-", "B. -N-", "C. --x N x--", "D. --o N o--"], a: 2 },
    { q: "Symbol representing a soldered joint.", choices: ["A. -|N|-", "B. -N-", "C. --x N x--", "D. --o N o--"], a: 3 },
    { q: "Maximum number of water closets for one vertical 3\" soil pipe.", choices: ["A. 2", "B. 3", "C. 4", "D. 6"], a: 2 },
    { q: "Maximum number of water closets for one horizontal 3\" soil pipe.", choices: ["A. 2", "B. 3", "C. 4", "D. 6"], a: 1 },
    { q: "Minimum depth of floor drain outlet to crown of drain pipe.", choices: ["A. 1\"", "B. 1.5\"", "C. 2\"", "D. 4\""], a: 2 }
    ],
    2: [
        { q: "A device screwed into the end of a faucet spout that mixes air into flowing water and controls flow to reduce splashing.", choices: ["A. aerator", "B. deaerator", "C. vent", "D. hydrator"], a: 0 },
    { q: "The unobstructed vertical distance between the lowest opening of a faucet which supplies a plumbing fixture and the level at which the fixture will overflow.", choices: ["A. air break", "B. air gap", "C. break up", "D. air gap"], a: 3 },
    { q: "A physical separation, which may be a low inlet into the indirect waste receptor from the fixture, appliance or device indirectly connected.", choices: ["A. air break", "B. air gap", "C. break up", "D. air gap"], a: 0 },
    { q: "A fitting, screwed or caulked over the end of a pipe for closing the pipe end.", choices: ["A. plug", "B. flange", "C. cap", "D. dead end"], a: 2 },
    { q: "A pipe, which carries ground and surface waters, storm water or wastewater into a building drainage system.", choices: ["A. drain", "B. drainage system", "C. sub drain", "D. none of the above"], a: 0 },
    { q: "It includes all the piping within public or private premises which convey sewage or other liquid wastes to a legal point of disposal.", choices: ["A. drain", "B. drainage system", "C. sub drain", "D. none of the above"], a: 1 },
    { q: "That part of the lowest horizontal piping of a drainage system which receives the discharge inside the walls and conveys it to the building sewer.", choices: ["A. building sewer", "B. building drain", "C. building subdrain", "D. building supply"], a: 1 },
    { q: "That portion of an underground system, which cannot drain by gravity into the building sewer.", choices: ["A. building sewer", "B. building drain", "C. building subdrain", "D. building supply"], a: 2 },
    { q: "Out of all the water on earth, which of the following is the approximate amount percentage of freshwater that is immediately available to humans?", choices: ["A. < 1%", "B. 2%", "C. 10%", "D. 20%"], a: 0 },
    { q: "The pipe carrying potable water from the water meter or other source of water supply to a building or other point of use.", choices: ["A. building sewer", "B. building drain", "C. building subdrain", "D. building supply"], a: 3 },
    { q: "Chlorine may be added to water in a continuous, slug, and/or the ______ method to initially disinfect a pipeline?", choices: ["A. segmented", "B. tablet", "C. low dose", "D. air injection"], a: 1 },
    { q: "Eighty parts per billion (80 ppb) is equal to which of the following?", choices: ["A. 8 ppm", "B. 0.08 mg/L", "C. 0.8 mg/L", "D. 80 mg/L"], a: 1 },
    { q: "What is the main difference between surface and groundwater contamination?", choices: ["A. Groundwater takes longer to recover", "B. Groundwater is less susceptible", "C. Surface waters take longer", "D. Surface waters are harder"], a: 0 },
    { q: "What constitutes a cross-connection?", choices: ["A. Connection between approved and unapproved supply", "B. Unprotected connection to drinking water", "C. Connection to non-potable supplies", "D. All of the above"], a: 0 },
    { q: "What type of meter is used when the water flow widely fluctuates?", choices: ["A. Nutating-disc meters", "B. Compound meters", "C. Proportional meters", "D. Venturi meters"], a: 1 },
    { q: "Which of the following is an advantage in using centrifugal pumps?", choices: ["A. Air leaks on suction", "B. Limited suction lift", "C. Cannot self prime", "D. Easy to repair"], a: 3 },
    { q: "When residential water meters become worn, they have the tendency to:", choices: ["A. over-register all flows", "B. under-register all flows", "C. under-register small flows", "D. create high pressure drops"], a: 1 },
    { q: "Which of the following is the approximate amount of ocean surface on earth?", choices: ["A. 18.5 %", "B. 25 %", "C. 30 %", "D. 75 %"], a: 3 },
    { q: "That part of the horizontal piping starts from the end of the building drain and conveys it to a public sewer or individual disposal system.", choices: ["A. building sewer", "B. building drain", "C. building subdrain", "D. building supply"], a: 0 },
    { q: "The term associated with water that evaporates from living plants.", choices: ["A. evapotranspiration", "B. condensation", "C. precipitation", "D. transpiration"], a: 3 },
    { q: "Of all the water on earth, which of the following percentages represent the amount of saltwater on earth?", choices: ["A. 25%", "B. 75%", "C. 90%", "D. 97%"], a: 3 },
    { q: "When sampling for bacteria, the bottle is prepared with which chemical inside before it is sterilized?", choices: ["A. copper sulfate", "B. chlorine tablets", "C. sodium thiosulfate", "D. hydrochloric acid"], a: 2 },
    { q: "The primary purpose of disinfection of water mains is to:", choices: ["A. Kill disease causing organisms", "B. Sterilize the main", "C. Create chlorine taste", "D. Keep the inside clean"], a: 0 },
    { q: "Chlorine gas is ______ times heavier than breathing air.", choices: ["A. 2.5", "B. 6.0", "C. 20", "D. 70"], a: 0 },
    { q: "Chlorine gas is 100% pure, bleach is ~5.25%, while HTH dry powder chlorine is set at ______ % purity.", choices: ["A. 20%", "B. 45%", "C. 65%", "D. 80%"], a: 2 },
    { q: "When chlorine gas is added to water the pH goes down due to:", choices: ["A. producing caustic substances", "B. two base materials", "C. two acids that form", "D. caustic soda forming"], a: 2 },
    { q: "Water with a pH of 7.9 is considered to be:", choices: ["A. acidic", "B. basic or alkaline", "C. neutral", "D. undrinkable"], a: 1 },
    { q: "Horsepower is defined as ______ ft-lbs per minute or 746 watts.", choices: ["A. 8.34", "B. 0.785", "C. 33,000", "D. 43,560"], a: 2 },
    { q: "The rated flow of a water meter, as stated by the manufacturer, is based upon which type of flow?", choices: ["A. max capacity at peak", "B. short-time peak", "C. continuous", "D. intermittent"], a: 2 },
    { q: "Below ground storage tanks are vulnerable in having which of the following?", choices: ["A. high pressures", "B. insects and root damage", "C. light penetration", "D. high liquid solid content"], a: 1 },
    { q: "The hydrologic cycle is composed of all the following terms, except:", choices: ["A. condensation", "B. evaporation", "C. adsorption", "D. percolation"], a: 2 },
    { q: "The acidity or alkalinity of water is determined through:", choices: ["A. pH value", "B. pH meter", "C. color meter", "D. taste"], a: 0 },
    { q: "It is the volume of a liquid passing through a cross section of a stream in a unit time.", choices: ["A. Steady flow", "B. Uniform flow", "C. Continuous flow", "D. Discharge"], a: 3 },
    { q: "A type of valve which should be used only wide open or fully closed.", choices: ["A. Butterfly valve", "B. Gate valve", "C. Globe valve", "D. Check valve"], a: 1 },
    { q: "It is a throttling valve.", choices: ["A. Butterfly valve", "B. Gate valve", "C. Globe valve", "D. Check valve"], a: 2 },
    { q: "The pipe that is remarkable for hot water installation.", choices: ["A. brass pipe", "B. copper pipe", "C. stainless pipe", "D. GI pipe"], a: 1 },
    { q: "The rate of flow of liquid measured per unit of time, usually gpm or lps.", choices: ["A. Capacity", "B. Flow rate", "C. Pump rate", "D. Heart rate"], a: 1 },
    { q: "Characteristic of a pump in series.", choices: ["A. Different gpm", "B. Same gpm", "C. Same horsepower", "D. Different horsepower"], a: 1 },
    { q: "The bacteria in sewage are mostly:", choices: ["A. aerobic", "B. anaerobic", "C. pathogens", "D. parasitic"], a: 1 },
    { q: "Which of these is an instrument used in measuring the water flow?", choices: ["A. Pressure gauge", "B. Dynamometer", "C. Barometer", "D. Venturi meter"], a: 3 },
    { q: "Primary purpose of disinfection is to remove:", choices: ["A. color", "B. bacteria", "C. odor", "D. algae"], a: 1 },
    { q: "Four index (Horsepower) is equal to how many foot lbs per minutes?", choices: ["A. 30,000", "B. 33,000", "C. 33,333", "D. 30,033"], a: 1 },
    { q: "The term associated with the flow of water caused by gravity.", choices: ["A. static head", "B. pressure", "C. friction", "D. velocity"], a: 0 },
    { q: "The non-soluble materials which is the end product after biological action of bacteria in sewage waste.", choices: ["A. Scum", "B. Sledge", "C. Smudge", "D. Sludge"], a: 3 },
    { q: "A state of complete physical mental and social well-being.", choices: ["A. Wellbeing", "B. Fitness", "C. Health", "D. Happiness"], a: 2 },
    { q: "Recommended kind of fitting used in changing vertical to horizontal direction of drainage pipes.", choices: ["A. short sweep bend", "B. long sweep bend", "C. tee", "D. all of the above"], a: 1 },
    { q: "A fire class involves ordinary combustible materials wood, cloth, rubber and plastic.", choices: ["A. Class A", "B. Class B", "C. Class C", "D. Class D"], a: 0 },
    { q: "A fire class involving combustible materials such as sodium, magnesium, and potassium.", choices: ["A. Class A", "B. Class B", "C. Class C", "D. Class D"], a: 3 },
    { q: "A fire class that identifies as energized electrical equipment.", choices: ["A. Class K", "B. Class B", "C. Class C", "D. Class D"], a: 2 },
    { q: "A fire class that identifies as flammable liquids and gases.", choices: ["A. Class K", "B. Class B", "C. Class C", "D. Class D"], a: 1 },
    { q: "A fire class classifying fires in cooking appliances.", choices: ["A. Class K", "B. Class B", "C. Class C", "D. Class D"], a: 2 },
    { q: "Wall designed to prevent the spread of fire.", choices: ["A. fire protection", "B. shear wall", "C. farewell", "D. fire wall"], a: 3 },
    { q: "The act known as the 'Revised Fire Code of the Philippines of 2008'.", choices: ["A. RA 9154", "B. RA 9541", "C. RA 5941", "D. RA 9514"], a: 3 },
    { q: "It is temperature at which water vapor forms above liquid fuel.", choices: ["A. Fire point", "B. Flush point", "C. Flash point", "D. Boiling point"], a: 2 },
    { q: "A septic tank is a watertight receptacle where sewage is digested mainly by microorganism called:", choices: ["A. Facultative bacteria", "B. Aerobic bacteria", "C. Anaerobic bacteria", "D. Algae"], a: 2 },
    { q: "It includes the discharge from latrine, urinals, bathrooms, kitchens, and stables.", choices: ["A. Refuse", "B. Sewage", "C. Wastewater", "D. Dirt"], a: 1 },
    { q: "Applied to a specific disease when it normally prevails in locality.", choices: ["A. Endemic", "B. Pandemic", "C. Epidemic", "D. Sporadic"], a: 0 },
    { q: "It is when the disease affects large number of people at the same time and transcends community boundaries.", choices: ["A. Endemic", "B. Pandemic", "C. Epidemic", "D. Sporadic"], a: 1 },
    { q: "Occurrence of few scattered cases of the disease without relationship to other cases.", choices: ["A. Endemic", "B. Pandemic", "C. Epidemic", "D. Sporadic"], a: 3 },
    { q: "Communicable diseaserecognized statistically as being well beyond the normal expectancy in a community.", choices: ["A. Endemic", "B. Pandemic", "C. Epidemic", "D. Sporadic"], a: 2 },
    { q: "The means by which infectious agents are transported thereby causing disease.", choices: ["A. Vehicle of inspection", "B. Carrier", "C. Vectors", "D. Vehicle of infection"], a: 3 },
    { q: "Arthropods or animals which transmit infection by inoculation or deposit of infective materials.", choices: ["A. Incubation period", "B. Carrier", "C. Vectors", "D. Vehicle of infection"], a: 2 },
    { q: "The time elapsing between the entrance of an infectious agent and appearance of symptoms.", choices: ["A. Incubation period", "B. Carrier", "C. Vectors", "D. Vehicle of infection"], a: 0 },
    { q: "An infected person without apparent disease but is a potential source of infection.", choices: ["A. Incubation period", "B. Carrier", "C. Vectors", "D. Vehicle of infection"], a: 1 },
    { q: "The physical characteristic of sewage includes:", choices: ["A. Turbidity", "B. Color", "C. Odor", "D. All of the above"], a: 3 },
    { q: "The portion of a fixture drain between a trap and the vent.", choices: ["A. crown weir", "B. trap seal", "C. developed length", "D. trap arm"], a: 3 },
    { q: "The top cover of a septic tank usually extends ______ above the surface to overcome infiltration.", choices: ["A. 5 cm", "B. 10 cm", "C. 15 cm", "D. 20 cm"], a: 2 },
    { q: "1 psi is equivalent to a water head of ______.", choices: ["A. 2.21 ft", "B. 2.31 ft", "C. 3.51 ft", "D. 2.12 ft"], a: 1 },
    { q: "The combination of sanitary sewerage and storm water.", choices: ["A. sewage", "B. waste", "C. septic", "D. combined sewage"], a: 3 },
    { q: "The property of a fluid wherein its own molecules are attracted to each other.", choices: ["A. absorption", "B. adsorption", "C. cohesion", "D. adhesion"], a: 2 },
    { q: "The study of the distribution of the disease or condition in a population.", choices: ["A. Environmental Sanitation", "B. Environmental Health", "C. Epidemiology", "D. Public Health"], a: 2 },
    { q: "The science and art of preventing disease, prolonging life and promoting health.", choices: ["A. Environmental Sanitation", "B. Environmental Health", "C. Epidemiology", "D. Public Health"], a: 3 },
    { q: "The body of hygienic knowledge.", choices: ["A. Environmental Sanitation", "B. Environmental Health", "C. Sanitary Science", "D. Public Health"], a: 2 },
    { q: "Principles of health reservation, embracing hygiene on an individual and communal level.", choices: ["A. Environmental Sanitation", "B. Environmental Health", "C. Sanitary Science", "D. Public Health"], a: 1 },
    { q: "Methods and processes by which the applications of the principles of sanitary science are affected.", choices: ["A. Environmental Sanitation", "B. Environmental Health", "C. Sanitary Science", "D. Sanitary Art"], a: 0 },
    { q: "What is that fittings so installed to prevent passage of air, gas and vermin through the pipe?", choices: ["A. tarp", "B. valve", "C. trap", "D. stopper"], a: 2 },
    { q: "Construction of septic tank should be located at a distance ______ away from water supply wells.", choices: ["A. 5 m", "B. 10 m", "C. 15 m", "D. 20 m"], a: 2 },
    { q: "The compartment in the septic tank that occupies 2/3 of the total volume.", choices: ["A. leaking chamber", "B. digestive chamber", "C. sewage chamber", "D. leaching chamber"], a: 1 },
    { q: "In term of discharge, one fixture unit is approximately:", choices: ["A. 1 gpm", "B. 1 fps", "C. 28.3 L/min", "D. 1 cu.m/min"], a: 2 },
    { q: "The retention period for which suspended matters in septic tank would settle and stabilize.", choices: ["A. 12 h", "B. 16 h", "C. 24 h", "D. 48 h"], a: 2 },
    { q: "Which sources of water supply that was not used in the older days?", choices: ["A. rain", "B. wells", "C. springs", "D. bottled mineral"], a: 3 },
    { q: "The pipe suitable for underground installation but never recommended for human consumption because it is poisonous.", choices: ["A. plastic pipe", "B. copper pipe", "C. GI pipe", "D. lead pipe"], a: 3 },
    { q: "The vertical distance between the dip and crown weir of the trap.", choices: ["A. trap seal", "B. crown", "C. trap arm", "D. basil"], a: 0 },
    { q: "The movement of water through the surface of a soil and into the soil below the surface.", choices: ["A. absorption", "B. intersection", "C. infiltration", "D. evaporation"], a: 2 },
    { q: "The process by which water changes from a liquid to a gas or vapor.", choices: ["A. condensation", "B. deposition", "C. sublimation", "D. evaporation"], a: 3 },
    { q: "The process wherein the water vapor changes directly into ice.", choices: ["A. condensation", "B. deposition", "C. sublimation", "D. evaporation"], a: 1 },
    { q: "The process by which the water vapor in the air is changed into liquid water.", choices: ["A. condensation", "B. deposition", "C. sublimation", "D. evaporation"], a: 0 },
    { q: "The process by which the water changes from solid state directly into gaseous phase.", choices: ["A. condensation", "B. deposition", "C. sublimation", "D. evaporation"], a: 2 },
    { q: "Unit of heat energy required to raise the temperature of 1 lb. of water 1 degree Fahrenheit.", choices: ["A. Calories", "B. hp", "C. BTU", "D. kW"], a: 2 },
    { q: "The size of the supply piping outlet for any gas appliance shall not be less than:", choices: ["A. the smallest pipe", "B. the inlet connection of that appliance", "C. 3/4\"", "D. 1\""], a: 1 },
    { q: "A community of 25,000 people uses 15 gallons of water per day per capita. Required motor capacity to raise it 150 ft?", choices: ["A. 9 hp", "B. 10 hp", "C. 12 hp", "D. 14 hp"], a: 1 },
    { q: "A pump having a plunger that moves back and forth within a cylinder equipped with check valves.", choices: ["A. centrifugal pump", "B. reciprocating pump", "C. piston pump", "D. plunger pump"], a: 1 },
    { q: "A pump that utilizes the centrifugal force.", choices: ["A. centrifugal pump", "B. reciprocating pump", "C. piston pump", "D. plunger pump"], a: 0 },
    { q: "A positive displacement reciprocating pump in which a plunger is driven backwards and forwards.", choices: ["A. centrifugal pump", "B. reciprocating pump", "C. piston pump", "D. plunger pump"], a: 3 },
    { q: "A reciprocating pump where the packing is on the stationary casing instead of the moving piston.", choices: ["A. centrifugal pump", "B. reciprocating pump", "C. piston pump", "D. plunger pump"], a: 3 },
    { q: "A displacement pump that delivers a steady flow by the action of two members in rotational contact.", choices: ["A. sump pump", "B. submersible pump", "C. rotary pump", "D. jet pump"], a: 2 },
    { q: "A pump used to remove water from a sump pit where the pumping end is immersed in the liquid.", choices: ["A. sump pump", "B. submersible pump", "C. rotary pump", "D. jet pump"], a: 0 },
    { q: "A pump positioned under water in a suitable bored hole that delivers the water to the surface.", choices: ["A. sump pump", "B. submersible pump", "C. rotary pump", "D. jet pump"], a: 1 },
    { q: "A pump typically used for drawing water up from a well.", choices: ["A. sump pump", "B. booster pump", "C. rotary pump", "D. jet pump"], a: 3 },
    { q: "A pump used to increase the pressure in a water supply line.", choices: ["A. sump pump", "B. booster pump", "C. rotary pump", "D. jet pump"], a: 1 }
    ],
    3: [
        { q: "By code definition, a stack is always _______.", choices: ["A. horizontal", "B. straight", "C. diagonal", "D. vertical"], a: 3 },
    { q: "A room equipped with a shower or bathtub is a _______.", choices: ["A. toilet room", "B. bathroom", "C. shower room", "D. washroom"], a: 1 },
    { q: "A horizontal drain sized to provide free movement of air above the flow line of the drain.", choices: ["A. continuous waste", "B. durham system", "C. combination waste and vent", "D. solvent system"], a: 2 },
    { q: "The length along the centerline of the pipe and fittings is the _______.", choices: ["A. diagonal length", "B. diameter length", "C. circumference", "D. developed length"], a: 3 },
    { q: "A device in an air accumulator vessel designed to discharge water for flushing.", choices: ["A. expansion tank", "B. day tank", "C. surge tank", "D. flushometer tank"], a: 3 },
    { q: "Fittings used to make an offset that is considered a vertical pipe.", choices: ["A. 1-90° and 1-45°", "B. 2-90° and 1-45°", "C. 1-45° and 1-60°", "D. 1-45° and 1-45°"], a: 3 },
    { q: "Water satisfactory for drinking, culinary, and domestic purposes.", choices: ["A. potable water", "B. soft water", "C. hard water", "D. industrial water"], a: 0 },
    { q: "Fixture connections requiring removal of an access panel for servicing are _______.", choices: ["A. exposed", "B. not accessible", "C. accessible", "D. readily accessible"], a: 2 },
    { q: "When residential water meters become worn, they have the tendency to _______.", choices: ["A. register trap seal", "B. over-register", "C. under-register", "D. stop entirely"], a: 2 },
    { q: "A vent that also serves as a drain.", choices: ["A. vent stack", "B. wet vent", "C. island vent", "D. loop vent"], a: 1 },
    { q: "A pipe which makes an angle of 45 degrees or less with the vertical.", choices: ["A. horizontal", "B. sloping", "C. diagonal", "D. vertical"], a: 3 },
    { q: "The restroom facilities in a private day care center are classified as public use.", choices: ["A. True", "B. False"], a: 0 },
    { q: "The discharge from clinical sinks conveyed to the building drain is defined as a waste pipe.", choices: ["A. True", "B. False"], a: 1 },
    { q: "A mixing valve that compensates for fluctuations in incoming hot or cold water.", choices: ["A. thermostatic valve", "B. pressure balance valve", "C. gate valve", "D. check valve"], a: 0 },
    { q: "PEX is defined as _______.", choices: ["A. polyethylene extension", "B. cross-linked polyethylene", "C. plastic extruded", "D. polymerized ethylene"], a: 1 },
    { q: "Lowest piping of a drainage system receiving discharge from soil/waste pipes inside walls.", choices: ["A. building sewer", "B. building main", "C. building drain", "D. building sub-drain"], a: 2 },
    { q: "A vertical vent that is a continuation of the drain to which it connects.", choices: ["A. stack vent", "B. relief vent", "C. common vent", "D. continuous vent"], a: 3 },
    { q: "A combination building sewer is a _______.", choices: ["A. storm sewer", "B. sanitary sewer", "C. combination of all piping", "D. industrial sewer"], a: 2 },
    { q: "The lowest portion of the inside of a horizontal pipe is called the _______.", choices: ["A. crown", "B. dip", "C. bottom", "D. invert"], a: 3 },
    { q: "A standard that is an extensive compilation of provisions covering broad subject matter.", choices: ["A. law", "B. regulation", "C. manual", "D. code"], a: 3 },
    { q: "Static pressure is pressure existing without any flow.", choices: ["A. True", "B. False"], a: 0 },
    { q: "A device and system of piping that maintains a water seal in a remote trap.", choices: ["A. trap seal", "B. trap primer", "C. backwater valve", "D. air gap"], a: 1 },
    { q: "The principal artery of the venting system to which branches may be connected.", choices: ["A. branch vent", "B. stack vent", "C. relief vent", "D. main vent"], a: 3 },
    { q: "The organization responsible for enforcing the requirements of a code.", choices: ["A. building owner", "B. administrative authority", "C. contractor", "D. engineer"], a: 1 },
    { q: "Portion of a drainage system that does not drain by gravity into the building sewer.", choices: ["A. building sewer", "B. building drain", "C. building subdrain", "D. storm drain"], a: 2 },
    { q: "Pipe inside a building conveying storm water from the roof to a storm drain.", choices: ["A. building drain", "B. building storm drain", "C. building sewer", "D. building main"], a: 1 },
    { q: "An outlet on a boiler to permit emptying or discharging of sediment.", choices: ["A. relief valve", "B. drain cock", "C. gate valve", "D. boiler blowoff"], a: 3 },
    { q: "Device designed to provide protection against hydraulic shock.", choices: ["A. check valve", "B. water hammer arrestor", "C. regulator", "D. surge tank"], a: 1 },
    { q: "A device installed in a drainage system to prevent reverse flow.", choices: ["A. check valve", "B. gate valve", "C. backwater valve", "D. relief valve"], a: 2 },
    { q: "Any pressure less than that exerted by atmosphere.", choices: ["A. atmospheric", "B. negative pressure", "C. positive pressure", "D. flow pressure"], a: 1 },
    { q: "Any pressure greater than that exerted by atmosphere.", choices: ["A. atmospheric", "B. negative pressure", "C. static pressure", "D. positive pressure"], a: 3 },
    { q: "The service valve serves _______.", choices: ["A. main meter", "B. horizontal piping from riser to station", "C. water heater", "D. fire sprinkler"], a: 1 },
    { q: "A document containing mandatory provisions using 'shall' to indicate requirements.", choices: ["A. standard", "B. code", "C. manual", "D. guide"], a: 0 },
    { q: "Unsanitary and insanitary share the same meaning.", choices: ["A. True", "B. False"], a: 0 },
    { q: "Critical level marking on backflow device if not marked.", choices: ["A. top", "B. bottom", "C. inlet", "D. outlet"], a: 1 },
    { q: "The pipe from the source of supply to a building or structure.", choices: ["A. water main", "B. building supply", "C. fixture branch", "D. riser"], a: 1 },
    { q: "Any pressure equal to that exerted by atmosphere.", choices: ["A. atmospheric pressure", "B. negative", "C. static", "D. positive"], a: 0 },
    { q: "The T rating limits maximum temperature rise above initial temperature by _______.", choices: ["A. 250 F", "B. 300 F", "C. 325 F", "D. 400 F"], a: 2 },
    { q: "Gray water definition includes untreated wastewater from _______.", choices: ["A. bathtubs/showers", "B. lavatories", "C. clothes washers", "D. all of the above"], a: 3 },
    { q: "Reclaimed water systems are defined as _______.", choices: ["A. recycled rain", "B. tertiary treated non-potable", "C. groundwater", "D. distilled"], a: 1 },
    { q: "Portion of a venting system connecting a water heater to a vent.", choices: ["A. flue", "B. vent connector", "C. chimney", "D. draft hood"], a: 1 },
    { q: "Device at bottom of tank for flushing water closets.", choices: ["A. ballcock", "B. float valve", "C. flush valve", "D. gate valve"], a: 2 },
    { q: "The overflow pipe from a fixture shall be connected on the _______.", choices: ["A. inlet side of trap", "B. outlet side of trap", "C. vent stack", "D. building drain"], a: 0 },
    { q: "Physical separation: low inlet into indirect waste receptor from fixtures.", choices: ["A. airbreak", "B. air gap", "C. backflow", "D. cross connection"], a: 0 },
    { q: "A pipe making an angle of 45 degrees or less with the vertical.", choices: ["A. vertical", "B. horizontal", "C. sloping", "D. diagonal"], a: 0 },
    { q: "The definition for the word 'Stack' does not include _______.", choices: ["A. soil piping", "B. waste piping", "C. vent piping", "D. water piping"], a: 3 },
    { q: "Mechanical device, other than an ejector, for removing waste from a sump.", choices: ["A. sewage pump", "B. lift pump", "C. siphon", "D. ejector"], a: 0 },
    { q: "Screws or bolts for securing floor-mounted fixtures shall be _______.", choices: ["A. copper alloy", "B. galvanized steel", "C. aluminum", "D. plastic"], a: 0 },
    { q: "Fixtures having concealed slip joint connections shall be provided with _______.", choices: ["A. access panel", "B. vent stack", "C. check valve", "D. cleanout"], a: 0 },
    { q: "Gray water is wastewater that has not come into contact with waste from _______.", choices: ["A. bathtubs", "B. showers", "C. toilets", "D. laundry tubs"], a: 2 },
    { q: "Diameter of waste outlet/tailpiece for a bathtub shall not be less than _______.", choices: ["A. 1-1/4\"", "B. 1-3/8\"", "C. 1-1/2\"", "D. 2\""], a: 2 },
    { q: "Connecting a dishwasher drain directly to the continuous waste is a code violation.", choices: ["A. True", "B. False"], a: 0 },
    { q: "Minimum distance from a side wall to the center of a water closet.", choices: ["A. 12\"", "B. 15\"", "C. 18\"", "D. 24\""], a: 1 },
    { q: "The distance between the center of two urinals cannot be less than _______.", choices: ["A. 24\"", "B. 28\"", "C. 30\"", "D. 36\""], a: 2 },
    { q: "Manually controlled flushometer valves shall flush not more than _______ urinal(s).", choices: ["A. 1", "B. 2", "C. 3", "D. 4"], a: 0 },
    { q: "Water supply to a urinal shall be protected by an approved _______.", choices: ["A. gate valve", "B. check valve", "C. vacuum breaker", "D. air gap"], a: 2 },
    { q: "Trough urinals shall be _______.", choices: ["A. encouraged", "B. permitted", "C. prohibited", "D. required"], a: 2 },
    { q: "Shower compartments shall be capable of encompassing a _______ diameter circle.", choices: ["A. 24\"", "B. 30\"", "C. 32\"", "D. 36\""], a: 1 },
    { q: "Curb/threshold of a shower may be eliminated for accessibility _______.", choices: ["A. residential", "B. gang showers", "C. ADA compliance", "D. never"], a: 1 },
    { q: "A dam or threshold depth measured to top of drain: min/max inches.", choices: ["A. 1, 6", "B. 2, 8", "C. 3, 10", "D. 2, 9"], a: 3 },
    { q: "Joints in copper shower pan liners shall be _______.", choices: ["A. glued", "B. soldered/brazed", "C. threaded", "D. compression"], a: 1 },
    { q: "Drinking fountains shall not be installed in _______.", choices: ["A. public toilet rooms", "B. hallways", "C. gyms", "D. offices"], a: 0 },
    { q: "Water closets set side by side shall be no closer than _______ center to center.", choices: ["A. 15\"", "B. 24\"", "C. 28\"", "D. 30\""], a: 3 },
    { q: "Tanks flushing more than one urinal shall be _______.", choices: ["A. automatic", "B. manual", "C. electric", "D. pressure-assisted"], a: 0 },
    { q: "Automatically controlled flushometer valves may be substituted for _______.", choices: ["A. flush tanks", "B. gate valves", "C. check valves", "D. air gaps"], a: 0 },
    { q: "Joint of a wall-hung lavatory in contact with the wall shall be _______.", choices: ["A. left open", "B. taped", "C. bolted", "D. made watertight"], a: 3 },
    { q: "Pitch to 'weep holes' for on-site built-up shower receptors: _______ inch/foot.", choices: ["A. 1/8", "B. 1/4", "C. 1/2", "D. 1"], a: 1 },
    { q: "Wall-hung lavatories shall be supported by _______.", choices: ["A. drywall", "B. metal members", "C. wood blocks", "D. adhesive"], a: 1 },
    { q: "The tailpiece diameter for lavatories shall not be less than _______.", choices: ["A. 1-1/4\"", "B. 1-1/2\"", "C. 1-3/4\"", "D. 2\""], a: 0 },
    { q: "Gutters in public shower rooms shall be sloped not less than _______.", choices: ["A. 2%", "B. 3%", "C. 4%", "D. 5%"], a: 0 },
    { q: "Strainers having waterway areas equivalent to tailpiece are required for _______.", choices: ["A. 1/8", "B. 1/4", "C. 1/2", "D. 1"], a: 1 },
    { q: "Showers shall be provided with individual control valves of the _______.", choices: ["A. pressure balance", "B. thermostatic", "C. gate valve", "D. both A & B"], a: 3 },
    { q: "Clear space in front of any water closet or bidet shall not be less than _______.", choices: ["A. 12\"", "B. 18\"", "C. 24\"", "D. 30\""], a: 2 },
    { q: "Maximum hot water temperature discharging from a bidet shall be _______ °F.", choices: ["A. 100", "B. 105", "C. 110", "D. 120"], a: 2 },
    { q: "Closet bends/stubs shall be cut off even with the _______.", choices: ["A. floor joist", "B. top of closet ring", "C. flange", "D. wall surface"], a: 1 },
    { q: "Wall-mounted water closets shall be securely bolted to _______.", choices: ["A. drywall", "B. the carrier", "C. floor", "D. ceiling"], a: 1 },
    { q: "Connections between drainage pipes and water closets shall be made with _______.", choices: ["A. putty", "B. tape", "C. flanges", "D. slip joints"], a: 2 },
    { q: "A domestic dishwasher shall discharge indirectly through an air gap into a _______.", choices: ["A. wye branch", "B. receptor", "C. disposer", "D. all of the above"], a: 3 },
    { q: "Water supply to bathtub/whirlpool filler valve protected by _______.", choices: ["A. check valve", "B. air gap", "C. gate valve", "D. relief valve"], a: 1 },
    { q: "Path of travel to an emergency eyewash shall be _______.", choices: ["A. around obstacles", "B. straight line", "C. locked door", "D. upstairs"], a: 1 },
    { q: "Non-water urinals _______.", choices: ["A. prohibited", "B. no vent", "C. rough-in water", "D. use oil only"], a: 2 },
    { q: "Sheet steel for restaurant dish-washing sinks: min _______ U.S. gauge.", choices: ["A. 16", "B. 18", "C. 20", "D. 22"], a: 0 },
    { q: "Dry or chemical toilets require approval by the _______.", choices: ["A. plumber", "B. contractor", "C. owner", "D. health officer"], a: 3 },
    { q: "Wye/directional fittings installed to continuous wastes for food waste disposer.", choices: ["A. True", "B. False"], a: 0 },
    { q: "Maximum fixture unit loading allowed on a 2-inch waste stack.", choices: ["A. 4", "B. 8", "C. 10", "D. 12"], a: 1 },
    { q: "Three-inch horizontal drainage pipe shall have a grade of not less than _______.", choices: ["A. 1/8\"", "B. 1/4\"", "C. 1/2\"", "D. 1\""], a: 1 },
    { q: "The maximum trap loading for a 3-inch trap is _______ unit(s).", choices: ["A. 3", "B. 4", "C. 5", "D. 6"], a: 3 },
    { q: "Minimum sizes of vertical/horizontal drainage determined from _______.", choices: ["A. building height", "B. occupancy", "C. material", "D. fixture units"], a: 3 },
    { q: "Discharge from an ejector shall be provided with a backwater valve _______.", choices: ["A. or check/gate valve", "B. relief valve", "C. air gap", "D. trap primer"], a: 0 },
    { q: "Max discharge for intermittent flow for 1 fixture unit is _______ gpm.", choices: ["A. 7.5", "B. 10", "C. 15", "D. 20"], a: 0 },
    { q: "Minimum size drain line for a wall-hung urinal is _______ inches.", choices: ["A. 2", "B. 3", "C. 4", "D. 1.5"], a: 0 },
    { q: "Acceptable fitting for connecting horizontal drain line with another horizontal.", choices: ["A. sanitary tee", "B. wye and 1/8 bend", "C. straight tee", "D. cross"], a: 1 },
    { q: "Clearance required in front of a 2-inch cleanout shall not be less than _______.", choices: ["A. 12\"", "B. 18\"", "C. 24\"", "D. 30\""], a: 0 },
    { q: "Minimum size trap and trap arm for a bathtub.", choices: ["A. 1.5\"", "B. 2\"", "C. 3\"", "D. 1.25\""], a: 0 },
    { q: "Min size discharge pipe from ejector in single dwelling with water closet.", choices: ["A. 1.5\"", "B. 2\"", "C. 3\"", "D. 4\""], a: 0 },
    { q: "Adding 60 gpm ejector (1 gpm = 2 FU) to 30 FU line: total _______ FU.", choices: ["A. 90", "B. 120", "C. 150", "D. 180"], a: 2 },
    { q: "Stacks 3+ stories serving _______ are considered suds-producing.", choices: ["A. kitchen sinks", "B. lavatories", "C. water closets", "D. bidets"], a: 0 },
    { q: "Drainage connections within _______ ft of change in direction for suds stacks.", choices: ["A. 2", "B. 4", "C. 8", "D. 10"], a: 1 },
    { q: "Max fixture units on 4-inch horizontal drain at 1/8\" per foot slope.", choices: ["A. 150", "B. 160", "C. 170", "D. 173"], a: 3 },
    { q: "Straight run of building sewer requires clean-outs at intervals not exceeding _______.", choices: ["A. 50'", "B. 100'", "C. 150'", "D. 200'"], a: 1 }
    ],
    4: [
        { q: "By code definition, a stack is always _______.", choices: ["A. horizontal", "B. straight", "C. diagonal", "D. vertical"], a: 3 },
    { q: "A room equipped with a shower or bathtub is a _______.", choices: ["A. toilet room", "B. bathroom", "C. shower room", "D. washroom"], a: 1 },
    { q: "A horizontal drain sized to provide free movement of air above the flow line of the drain.", choices: ["A. continuous waste", "B. durham system", "C. combination waste and vent", "D. solvent system"], a: 2 },
    { q: "The length along the centerline of the pipe and fittings is the _______.", choices: ["A. diagonal length", "B. diameter length", "C. circumference", "D. developed length"], a: 3 },
    { q: "A device in an air accumulator vessel designed to discharge water for flushing.", choices: ["A. expansion tank", "B. day tank", "C. surge tank", "D. flushometer tank"], a: 3 },
    { q: "Fittings used to make an offset that is considered a vertical pipe.", choices: ["A. 1-90° and 1-45°", "B. 2-90° and 1-45°", "C. 1-45° and 1-60°", "D. 1-45° and 1-45°"], a: 3 },
    { q: "Water satisfactory for drinking, culinary, and domestic purposes.", choices: ["A. potable water", "B. soft water", "C. hard water", "D. industrial water"], a: 0 },
    { q: "Fixture connections requiring removal of an access panel for servicing are _______.", choices: ["A. exposed", "B. not accessible", "C. accessible", "D. readily accessible"], a: 2 },
    { q: "When residential water meters become worn, they have the tendency to _______.", choices: ["A. register trap seal", "B. over-register", "C. under-register", "D. stop entirely"], a: 2 },
    { q: "A vent that also serves as a drain.", choices: ["A. vent stack", "B. wet vent", "C. island vent", "D. loop vent"], a: 1 },
    { q: "A pipe which makes an angle of 45 degrees or less with the vertical.", choices: ["A. horizontal", "B. sloping", "C. diagonal", "D. vertical"], a: 3 },
    { q: "The restroom facilities in a private day care center are classified as public use.", choices: ["A. True", "B. False"], a: 0 },
    { q: "The discharge from clinical sinks conveyed to the building drain is defined as a waste pipe.", choices: ["A. True", "B. False"], a: 1 },
    { q: "A mixing valve that compensates for fluctuations in incoming hot or cold water.", choices: ["A. thermostatic valve", "B. pressure balance valve", "C. gate valve", "D. check valve"], a: 0 },
    { q: "PEX is defined as _______.", choices: ["A. polyethylene extension", "B. cross-linked polyethylene", "C. plastic extruded", "D. polymerized ethylene"], a: 1 },
    { q: "Lowest piping of a drainage system receiving discharge from soil/waste pipes inside walls.", choices: ["A. building sewer", "B. building main", "C. building drain", "D. building sub-drain"], a: 2 },
    { q: "A vertical vent that is a continuation of the drain to which it connects.", choices: ["A. stack vent", "B. relief vent", "C. common vent", "D. continuous vent"], a: 3 },
    { q: "A combination building sewer is a _______.", choices: ["A. storm sewer", "B. sanitary sewer", "C. combination of all piping", "D. industrial sewer"], a: 2 },
    { q: "The lowest portion of the inside of a horizontal pipe is called the _______.", choices: ["A. crown", "B. dip", "C. bottom", "D. invert"], a: 3 },
    { q: "A standard that is an extensive compilation of provisions covering broad subject matter.", choices: ["A. law", "B. regulation", "C. manual", "D. code"], a: 3 },
    { q: "Static pressure is pressure existing without any flow.", choices: ["A. True", "B. False"], a: 0 },
    { q: "A device and system of piping that maintains a water seal in a remote trap.", choices: ["A. trap seal", "B. trap primer", "C. backwater valve", "D. air gap"], a: 1 },
    { q: "The principal artery of the venting system to which branches may be connected.", choices: ["A. branch vent", "B. stack vent", "C. relief vent", "D. main vent"], a: 3 },
    { q: "The organization responsible for enforcing the requirements of a code.", choices: ["A. building owner", "B. administrative authority", "C. contractor", "D. engineer"], a: 1 },
    { q: "Portion of a drainage system that does not drain by gravity into the building sewer.", choices: ["A. building sewer", "B. building drain", "C. building subdrain", "D. storm drain"], a: 2 },
    { q: "Pipe inside a building conveying storm water from the roof to a storm drain.", choices: ["A. building drain", "B. building storm drain", "C. building sewer", "D. building main"], a: 1 },
    { q: "An outlet on a boiler to permit emptying or discharging of sediment.", choices: ["A. relief valve", "B. drain cock", "C. gate valve", "D. boiler blowoff"], a: 3 },
    { q: "Device designed to provide protection against hydraulic shock.", choices: ["A. check valve", "B. water hammer arrestor", "C. regulator", "D. surge tank"], a: 1 },
    { q: "A device installed in a drainage system to prevent reverse flow.", choices: ["A. check valve", "B. gate valve", "C. backwater valve", "D. relief valve"], a: 2 },
    { q: "Any pressure less than that exerted by atmosphere.", choices: ["A. atmospheric", "B. negative pressure", "C. positive pressure", "D. flow pressure"], a: 1 },
    { q: "Any pressure greater than that exerted by atmosphere.", choices: ["A. atmospheric", "B. negative pressure", "C. static pressure", "D. positive pressure"], a: 3 },
    { q: "The service valve serves _______.", choices: ["A. main meter", "B. horizontal piping from riser to station", "C. water heater", "D. fire sprinkler"], a: 1 },
    { q: "A document containing mandatory provisions using 'shall' to indicate requirements.", choices: ["A. standard", "B. code", "C. manual", "D. guide"], a: 0 },
    { q: "Unsanitary and insanitary share the same meaning.", choices: ["A. True", "B. False"], a: 0 },
    { q: "Critical level marking on backflow device if not marked.", choices: ["A. top", "B. bottom", "C. inlet", "D. outlet"], a: 1 },
    { q: "The pipe from the source of supply to a building or structure.", choices: ["A. water main", "B. building supply", "C. fixture branch", "D. riser"], a: 1 },
    { q: "Any pressure equal to that exerted by atmosphere.", choices: ["A. atmospheric pressure", "B. negative", "C. static", "D. positive"], a: 0 },
    { q: "The T rating limits maximum temperature rise above initial temperature by _______.", choices: ["A. 250 F", "B. 300 F", "C. 325 F", "D. 400 F"], a: 2 },
    { q: "Gray water definition includes untreated wastewater from _______.", choices: ["A. bathtubs/showers", "B. lavatories", "C. clothes washers", "D. all of the above"], a: 3 },
    { q: "Reclaimed water systems are defined as _______.", choices: ["A. recycled rain", "B. tertiary treated non-potable", "C. groundwater", "D. distilled"], a: 1 },
    { q: "Portion of a venting system connecting a water heater to a vent.", choices: ["A. flue", "B. vent connector", "C. chimney", "D. draft hood"], a: 1 },
    { q: "Device at bottom of tank for flushing water closets.", choices: ["A. ballcock", "B. float valve", "C. flush valve", "D. gate valve"], a: 2 },
    { q: "The overflow pipe from a fixture shall be connected on the _______.", choices: ["A. inlet side of trap", "B. outlet side of trap", "C. vent stack", "D. building drain"], a: 0 },
    { q: "Physical separation: low inlet into indirect waste receptor from fixtures.", choices: ["A. airbreak", "B. air gap", "C. backflow", "D. cross connection"], a: 0 },
    { q: "A pipe making an angle of 45 degrees or less with the vertical.", choices: ["A. vertical", "B. horizontal", "C. sloping", "D. diagonal"], a: 0 },
    { q: "The definition for the word 'Stack' does not include _______.", choices: ["A. soil piping", "B. waste piping", "C. vent piping", "D. water piping"], a: 3 },
    { q: "Mechanical device, other than an ejector, for removing waste from a sump.", choices: ["A. sewage pump", "B. lift pump", "C. siphon", "D. ejector"], a: 0 },
    { q: "Screws or bolts for securing floor-mounted fixtures shall be _______.", choices: ["A. copper alloy", "B. galvanized steel", "C. aluminum", "D. plastic"], a: 0 },
    { q: "Fixtures having concealed slip joint connections shall be provided with _______.", choices: ["A. access panel", "B. vent stack", "C. check valve", "D. cleanout"], a: 0 },
    { q: "Gray water is wastewater that has not come into contact with waste from _______.", choices: ["A. bathtubs", "B. showers", "C. toilets", "D. laundry tubs"], a: 2 },
    { q: "Diameter of waste outlet/tailpiece for a bathtub shall not be less than _______.", choices: ["A. 1-1/4\"", "B. 1-3/8\"", "C. 1-1/2\"", "D. 2\""], a: 2 },
    { q: "Connecting a dishwasher drain directly to the continuous waste is a code violation.", choices: ["A. True", "B. False"], a: 0 },
    { q: "Minimum distance from a side wall to the center of a water closet.", choices: ["A. 12\"", "B. 15\"", "C. 18\"", "D. 24\""], a: 1 },
    { q: "The distance between the center of two urinals cannot be less than _______.", choices: ["A. 24\"", "B. 28\"", "C. 30\"", "D. 36\""], a: 2 },
    { q: "Manually controlled flushometer valves shall flush not more than _______ urinal(s).", choices: ["A. 1", "B. 2", "C. 3", "D. 4"], a: 0 },
    { q: "Water supply to a urinal shall be protected by an approved _______.", choices: ["A. gate valve", "B. check valve", "C. vacuum breaker", "D. air gap"], a: 2 },
    { q: "Trough urinals shall be _______.", choices: ["A. encouraged", "B. permitted", "C. prohibited", "D. required"], a: 2 },
    { q: "Shower compartments shall be capable of encompassing a _______ diameter circle.", choices: ["A. 24\"", "B. 30\"", "C. 32\"", "D. 36\""], a: 1 },
    { q: "Curb/threshold of a shower may be eliminated for accessibility _______.", choices: ["A. residential", "B. gang showers", "C. ADA compliance", "D. never"], a: 1 },
    { q: "A dam or threshold depth measured to top of drain: min/max inches.", choices: ["A. 1, 6", "B. 2, 8", "C. 3, 10", "D. 2, 9"], a: 3 },
    { q: "Joints in copper shower pan liners shall be _______.", choices: ["A. glued", "B. soldered/brazed", "C. threaded", "D. compression"], a: 1 },
    { q: "Drinking fountains shall not be installed in _______.", choices: ["A. public toilet rooms", "B. hallways", "C. gyms", "D. offices"], a: 0 },
    { q: "Water closets set side by side shall be no closer than _______ center to center.", choices: ["A. 15\"", "B. 24\"", "C. 28\"", "D. 30\""], a: 3 },
    { q: "Tanks flushing more than one urinal shall be _______.", choices: ["A. automatic", "B. manual", "C. electric", "D. pressure-assisted"], a: 0 },
    { q: "Automatically controlled flushometer valves may be substituted for _______.", choices: ["A. flush tanks", "B. gate valves", "C. check valves", "D. air gaps"], a: 0 },
    { q: "Joint of a wall-hung lavatory in contact with the wall shall be _______.", choices: ["A. left open", "B. taped", "C. bolted", "D. made watertight"], a: 3 },
    { q: "Pitch to 'weep holes' for on-site built-up shower receptors: _______ inch/foot.", choices: ["A. 1/8", "B. 1/4", "C. 1/2", "D. 1"], a: 1 },
    { q: "Wall-hung lavatories shall be supported by _______.", choices: ["A. drywall", "B. metal members", "C. wood blocks", "D. adhesive"], a: 1 },
    { q: "The tailpiece diameter for lavatories shall not be less than _______.", choices: ["A. 1-1/4\"", "B. 1-1/2\"", "C. 1-3/4\"", "D. 2\""], a: 0 },
    { q: "Gutters in public shower rooms shall be sloped not less than _______.", choices: ["A. 2%", "B. 3%", "C. 4%", "D. 5%"], a: 0 },
    { q: "Strainers having waterway areas equivalent to tailpiece are required for _______.", choices: ["A. 1/8", "B. 1/4", "C. 1/2", "D. 1"], a: 1 },
    { q: "Showers shall be provided with individual control valves of the _______.", choices: ["A. pressure balance", "B. thermostatic", "C. gate valve", "D. both A & B"], a: 3 },
    { q: "Clear space in front of any water closet or bidet shall not be less than _______.", choices: ["A. 12\"", "B. 18\"", "C. 24\"", "D. 30\""], a: 2 },
    { q: "Maximum hot water temperature discharging from a bidet shall be _______ °F.", choices: ["A. 100", "B. 105", "C. 110", "D. 120"], a: 2 },
    { q: "Closet bends/stubs shall be cut off even with the _______.", choices: ["A. floor joist", "B. top of closet ring", "C. flange", "D. wall surface"], a: 1 },
    { q: "Wall-mounted water closets shall be securely bolted to _______.", choices: ["A. drywall", "B. the carrier", "C. floor", "D. ceiling"], a: 1 },
    { q: "Connections between drainage pipes and water closets shall be made with _______.", choices: ["A. putty", "B. tape", "C. flanges", "D. slip joints"], a: 2 },
    { q: "A domestic dishwasher shall discharge indirectly through an air gap into a _______.", choices: ["A. wye branch", "B. receptor", "C. disposer", "D. all of the above"], a: 3 },
    { q: "Water supply to bathtub/whirlpool filler valve protected by _______.", choices: ["A. check valve", "B. air gap", "C. gate valve", "D. relief valve"], a: 1 },
    { q: "Path of travel to an emergency eyewash shall be _______.", choices: ["A. around obstacles", "B. straight line", "C. locked door", "D. upstairs"], a: 1 },
    { q: "Non-water urinals _______.", choices: ["A. prohibited", "B. no vent", "C. rough-in water", "D. use oil only"], a: 2 },
    { q: "Sheet steel for restaurant dish-washing sinks: min _______ U.S. gauge.", choices: ["A. 16", "B. 18", "C. 20", "D. 22"], a: 0 },
    { q: "Dry or chemical toilets require approval by the _______.", choices: ["A. plumber", "B. contractor", "C. owner", "D. health officer"], a: 3 },
    { q: "Wye/directional fittings installed to continuous wastes for food waste disposer.", choices: ["A. True", "B. False"], a: 0 },
    { q: "Maximum fixture unit loading allowed on a 2-inch waste stack.", choices: ["A. 4", "B. 8", "C. 10", "D. 12"], a: 1 },
    { q: "Three-inch horizontal drainage pipe shall have a grade of not less than _______.", choices: ["A. 1/8\"", "B. 1/4\"", "C. 1/2\"", "D. 1\""], a: 1 },
    { q: "The maximum trap loading for a 3-inch trap is _______ unit(s).", choices: ["A. 3", "B. 4", "C. 5", "D. 6"], a: 3 },
    { q: "Minimum sizes of vertical/horizontal drainage determined from _______.", choices: ["A. building height", "B. occupancy", "C. material", "D. fixture units"], a: 3 },
    { q: "Discharge from an ejector shall be provided with a backwater valve _______.", choices: ["A. or check/gate valve", "B. relief valve", "C. air gap", "D. trap primer"], a: 0 },
    { q: "Max discharge for intermittent flow for 1 fixture unit is _______ gpm.", choices: ["A. 7.5", "B. 10", "C. 15", "D. 20"], a: 0 },
    { q: "Minimum size drain line for a wall-hung urinal is _______ inches.", choices: ["A. 2", "B. 3", "C. 4", "D. 1.5"], a: 0 },
    { q: "Acceptable fitting for connecting horizontal drain line with another horizontal.", choices: ["A. sanitary tee", "B. wye and 1/8 bend", "C. straight tee", "D. cross"], a: 1 },
    { q: "Clearance required in front of a 2-inch cleanout shall not be less than _______.", choices: ["A. 12\"", "B. 18\"", "C. 24\"", "D. 30\""], a: 0 },
    { q: "Minimum size trap and trap arm for a bathtub.", choices: ["A. 1.5\"", "B. 2\"", "C. 3\"", "D. 1.25\""], a: 0 },
    { q: "Min size discharge pipe from ejector in single dwelling with water closet.", choices: ["A. 1.5\"", "B. 2\"", "C. 3\"", "D. 4\""], a: 0 },
    { q: "Adding 60 gpm ejector (1 gpm = 2 FU) to 30 FU line: total _______ FU.", choices: ["A. 90", "B. 120", "C. 150", "D. 180"], a: 2 },
    { q: "Stacks 3+ stories serving _______ are considered suds-producing.", choices: ["A. kitchen sinks", "B. lavatories", "C. water closets", "D. bidets"], a: 0 },
    { q: "Drainage connections within _______ ft of change in direction for suds stacks.", choices: ["A. 2", "B. 4", "C. 8", "D. 10"], a: 1 },
    { q: "Max fixture units on 4-inch horizontal drain at 1/8\" per foot slope.", choices: ["A. 150", "B. 160", "C. 170", "D. 173"], a: 3 },
    { q: "Straight run of building sewer requires clean-outs at intervals not exceeding _______.", choices: ["A. 50'", "B. 100'", "C. 150'", "D. 200'"], a: 1 }
    ],
    5: [
        { q: "It carries wastes other than fecal matter.", choices: ["A. Waste Drainage System", "B. Sanitary Drainage System", "C. Sovent Drainage System", "D. All of the above"], a: 0 },
    { q: "Which of the following is suitable for Type III Level of Water Supply?", choices: ["A. factory", "B. office", "C. condominium", "D. all of these"], a: 3 },
    { q: "Which fitting is recommended for vertical to horizontal change?", choices: ["A. sanitary tee", "B. combination wye and 1/8 bend", "C. 22 1/2° bend", "D. 60° wye branch"], a: 1 },
    { q: "Which is measured on its outside diameter?", choices: ["A. PPR", "B. PE", "C. PB", "D. PEX"], a: 0 },
    { q: "It checks or prevents reversal of flow.", choices: ["A. angle valve", "B. gate valve", "C. check valve", "D. relief valve"], a: 2 },
    { q: "The following are the types of Water Distribution: I. Direct Pressure, II. Indirect Pressure, III. Gravity, IV. Pneumatic.", choices: ["A. I & II", "B. II & IV", "C. II & III", "D. III & IV"], a: 0 },
    { q: "According to PNSDW, what is the recommended pH range of drinking water?", choices: ["A. 0-7", "B. 6-8", "C. 7-14", "D. 10-14"], a: 1 },
    { q: "What is the commercial length of G.I. pipe?", choices: ["A. 3 m", "B. 4 m", "C. 6 m", "D. 12 m"], a: 2 },
    { q: "What is the minimum needed supply pressure for flushometer?", choices: ["A. 8 psi", "B. 10 psi", "C. 15 psi", "D. 20 psi"], a: 2 },
    { q: "What is the size of cleanout for a 4\" diameter pipe?", choices: ["A. 1 1/2 in", "B. 2 1/2 in", "C. 3 1/2 in", "D. 4 in"], a: 2 },
    { q: "What is the size of cleanout for a 3\" diameter pipe?", choices: ["A. 1 1/2 in", "B. 2 1/2 in", "C. 3 1/2 in", "D. 4 in"], a: 1 },
    { q: "What is the size of cleanout for a 6\" diameter pipe?", choices: ["A. 1 1/2 in", "B. 2 1/2 in", "C. 3 1/2 in", "D. 4 in"], a: 3 },
    { q: "What is the size of cleanout for a 2\" diameter pipe?", choices: ["A. 1 1/2 in", "B. 2 1/2 in", "C. 3 1/2 in", "D. 4 in"], a: 0 },
    { q: "What is the minimum distance of water supply well to building sewer?", choices: ["A. 6 m", "B. 30.5 m", "C. 15.2 m", "D. 45.7 m"], a: 2 },
    { q: "What is the minimum distance of water supply well to septic tank?", choices: ["A. 6 m", "B. 30.5 m", "C. 15.2 m", "D. 45.7 m"], a: 2 },
    { q: "What is the minimum distance of water supply well to seepage pit?", choices: ["A. 6 m", "B. 30.5 m", "C. 15.2 m", "D. 45.7 m"], a: 1 },
    { q: "What is the minimum distance of water supply well to disposal field?", choices: ["A. 6 m", "B. 30.5 m", "C. 15.2 m", "D. 45.7 m"], a: 3 },
    { q: "What is the distance of the urinal outlet from the floor level?", choices: ["A. 15 in", "B. 21 in", "C. 24 in", "D. 36 in"], a: 1 },
    { q: "What is the size of the pipe carrying refrigeration waste that is capable of serving 2.8 m³ refrigeration space?", choices: ["A. 25 mm", "B. 32 mm", "C. 51 mm", "D. 76 mm"], a: 1 },
    { q: "What is the size of the pipe carrying refrigeration waste that is capable of serving 30 m³ refrigeration space?", choices: ["A. 25 mm", "B. 32 mm", "C. 51 mm", "D. 76 mm"], a: 3 },
    { q: "What is the size of the pipe carrying refrigeration waste that is capable of serving 8 m³ refrigeration space?", choices: ["A. 25 mm", "B. 32 mm", "C. 51 mm", "D. 76 mm"], a: 2 },
    { q: "In industrial warehouses workshops, determine the number of water closets for 220 male employees.", choices: ["A. 7", "B. 9", "C. 10", "D. 12"], a: 1 },
    { q: "In industrial warehouses workshops, determine the number of water closets for 200 female employees.", choices: ["A. 7", "B. 9", "C. 10", "D. 12"], a: 1 },
    { q: "In offices or public buildings, determine the number of urinals for 760 male employees.", choices: ["A. 15", "B. 16", "C. 17", "D. 18"], a: 1 },
    { q: "In offices or public buildings, determine the number of lavatories for 760 male employees.", choices: ["A. 15", "B. 16", "C. 18", "D. 19"], a: 3 },
    { q: "In offices or public buildings, determine the number of lavatories for 680 female employees.", choices: ["A. 15", "B. 16", "C. 17", "D. 18"], a: 2 },
    { q: "Which of the following is not part of the wet-pipe sprinkler system?", choices: ["A. water motor alarm", "B. deluge valve", "C. alarm check valve", "D. sprinkler"], a: 1 },
    { q: "What is the minimum size of standpipe for 2-3 storey building according to the National Building Code?", choices: ["A. 25 mm", "B. 50 mm", "C. 64 mm", "D. 102 mm"], a: 1 },
    { q: "A fitting or device designed to provide a liquid seal that will prevent the back passage of air.", choices: ["A. trap", "B. exhaust", "C. vent", "D. water seal"], a: 0 },
    { q: "What is the component of plumbing system that when properly vented will prevent release of foul odor?", choices: ["A. cleanout", "B. vent", "C. trap", "D. water seal"], a: 2 },
    { q: "From Figure 1 (Service Tap), identify the name corresponding to A.", choices: ["A. service pipe", "B. building supply", "C. water main", "D. Gooseneck"], a: 2 },
    { q: "From Figure 1, identify the name corresponding to B.", choices: ["A. saddle clamp", "B. straight coupling", "C. union", "D. Gooseneck"], a: 0 },
    { q: "From Figure 1, identify the name corresponding to I.", choices: ["A. service pipe", "B. building supply", "C. water main", "D. Gooseneck"], a: 0 },
    { q: "From Figure 1, identify the name corresponding to E.", choices: ["A. service pipe", "B. building supply", "C. water main", "D. Gooseneck"], a: 3 },
    { q: "From Figure 1, identify the name corresponding to C.", choices: ["A. corporation stop", "B. curb stop", "C. adapter", "D. straight coupling"], a: 0 },
    { q: "From Figure 1, identify the name corresponding to D.", choices: ["A. corporation stop", "B. curb stop", "C. adapter", "D. straight coupling"], a: 3 },
    { q: "From Figure 1, identify the name corresponding to J.", choices: ["A. corporation stop", "B. curb stop", "C. adapter", "D. straight coupling"], a: 1 },
    { q: "From Figure 1, identify the name corresponding to F.", choices: ["A. corporation stop", "B. curb stop", "C. adapter", "D. straight coupling"], a: 2 },
    { q: "From Figure 1, identify the name corresponding to H.", choices: ["A. manhole", "B. curb box", "C. cover", "D. none of these"], a: 1 },
    { q: "From Figure 2 (Septic Tank), identify the name corresponding to A.", choices: ["A. inlet", "B. outlet", "C. influent", "D. effluent"], a: 0 },
    { q: "From Figure 2, identify the name corresponding to F.", choices: ["A. inlet", "B. outlet", "C. influent", "D. effluent"], a: 1 },
    { q: "From Figure 2, identify the name corresponding to D.", choices: ["A. freeboard", "B. void", "C. airspace", "D. air"], a: 2 },
    { q: "From Figure 2, identify the name corresponding to B.", choices: ["A. access", "B. manhole", "C. cover", "D. concrete"], a: 1 },
    { q: "From Figure 2, identify the name corresponding to E.", choices: ["A. pit", "B. sludge pit", "C. sludge", "D. none of these"], a: 1 },
    { q: "From Figure 2, identify the name corresponding to C.", choices: ["A. water level", "B. waste level", "C. sewage level", "D. liquid level"], a: 3 },
    { q: "The water moving away from, or out of, a septic tank.", choices: ["A. inflow", "B. influent", "C. effluent", "D. outflow"], a: 2 },
    { q: "The liquid moving toward, or into, the septic tank.", choices: ["A. inflow", "B. influent", "C. effluent", "D. outflow"], a: 1 },
    { q: "Determine diameter of horizontal gutter sloped at 1% for 90 m² area (Rainfall 102 mm/hr).", choices: ["A. 4\"", "B. 5\"", "C. 6\"", "D. 7\""], a: 1 },
    { q: "Determine size of downspout for roof area 800 m² with 4\"/hr rainfall intensity.", choices: ["A. 2\"", "B. 3\"", "C. 4\"", "D. 5\""], a: 3 },
    { q: "Determine size of downspout for roof area 500 m² with 3\"/hr rainfall intensity.", choices: ["A. 2\"", "B. 3\"", "C. 4\"", "D. 5\""], a: 2 },
    { q: "Design horizontal rainwater pipe sloped 2% for roof area 325 m² (Rainfall 5\"/hr).", choices: ["A. 3\"", "B. 4\"", "C. 5\"", "D. 6\""], a: 3 },
    { q: "Determine diameter of horizontal gutter sloped at 2% for 1200 m² area (Rainfall 127 mm/hr).", choices: ["A. 5\"", "B. 6\"", "C. 7\"", "D. 8\""], a: 3 },
    { q: "Water-sealed P-trap for normal conditions with 5 cm deep water seal.", choices: ["A. common seal P-trap", "B. deep seal P-trap", "C. drum trap", "D. stand trap"], a: 0 },
    { q: "Classification of water-sealed P-trap that has 7.5-10 cm deep water seal.", choices: ["A. common seal P-trap", "B. deep seal P-trap", "C. drum trap", "D. stand trap"], a: 1 },
    { q: "Situations that require the use of deep seal P-trap.", choices: ["A. extreme heat", "B. pressure changes", "C. limited ventilation", "D. all of these"], a: 3 },
    { q: "The vertical main of a system of soil, waste or vent pipings extending through one or more stories.", choices: ["A. standpipe", "B. main vent", "C. stack", "D. branch"], a: 2 },
    { q: "A vertical pipe that receives discharge from clear water waste from equipment.", choices: ["A. soil stack", "B. stack vent", "C. waste stack", "D. vent stack"], a: 2 },
    { q: "A vertical soil pipe that carries away discharge from water closets and urinals.", choices: ["A. soil stack", "B. stack vent", "C. waste stack", "D. vent stack"], a: 0 },
    { q: "It is defined as sewage or refuse.", choices: ["A. soil", "B. discharge", "C. waste", "D. effluent"], a: 2 },
    { q: "The discharge from any fixture, appliance, or area.", choices: ["A. soil", "B. discharge", "C. waste", "D. effluent"], a: 1 },
    { q: "Any part of a piping system other than a main, riser, or stack.", choices: ["A. vent", "B. leader", "C. sewer", "D. branch"], a: 3 },
    { q: "A process used to make a water- or gas-tight seal in a joint using a mastic compound.", choices: ["A. caulking", "B. sealing", "C. capping", "D. blocking"], a: 0 },
    { q: "Plumbing permit shall expire if work is not commenced within __.", choices: ["A. 120 days", "B. 240 days", "C. 365 days", "D. 720 days"], a: 2 },
    { q: "A return bend of small-sized pipe with one end 30 cm long and the other 7.5 cm long.", choices: ["A. bend", "B. trap", "C. gooseneck", "D. pipe"], a: 2 },
    { q: "A receptacle designed to collect surface water or rainwater from a calculated open area.", choices: ["A. roof drain", "B. scupper drain", "C. catch basin", "D. area drain"], a: 3 },
    { q: "A drain that allows drainage through parapet walls.", choices: ["A. roof drain", "B. scupper drain", "C. catch basin", "D. area drain"], a: 1 },
    { q: "A conduit installed to remove water from a roof.", choices: ["A. roof drain", "B. scupper drain", "C. catch basin", "D. area drain"], a: 0 },
    { q: "Collects storm water runoff and separates debris/sediment.", choices: ["A. roof drain", "B. scupper drain", "C. catch basin", "D. area drain"], a: 2 },
    { q: "Flexible plastic tubing suitable for hot and cold water pressure systems.", choices: ["A. polybutylene (PB)", "B. polyethylene (PE)", "C. polypropylene (PP)", "D. polyvinyl chloride"], a: 0 },
    { q: "What is the Oldest Brand of Porcelain Kitchen Sink?", choices: ["A. HCG", "B. Korean Standard", "C. American Standard", "D. Northern Hill"], a: 2 },
    { q: "Figure 3 (Trench): Minimum required dimension of A (Width) in mm?", choices: ["A. 304.8", "B. 457.2", "C. 508.3", "D. 914.4"], a: 1 },
    { q: "Figure 3: Maximum required dimension of A (Width) in mm?", choices: ["A. 304.8", "B. 457.2", "C. 508.3", "D. 914.4"], a: 3 },
    { q: "Figure 3: Minimum required dimension of E (Depth) in mm?", choices: ["A. 50.8", "B. 76.2", "C. 152.4", "D. 304.8"], a: 3 },
    { q: "Figure 3: Minimum required dimension of B in mm?", choices: ["A. 50.8", "B. 76.2", "C. 152.4", "D. 304.8"], a: 1 },
    { q: "Figure 3: What do you call label A?", choices: ["A. Top width", "B. Average Width", "C. Width of Trench", "D. Bottom width"], a: 2 },
    { q: "Figure 3: What do you call label F?", choices: ["A. Filter Material", "B. Backfill", "C. Disposal Field", "D. Natural Ground"], a: 1 },
    { q: "Figure 3: What do you call label H?", choices: ["A. Filter Material", "B. Backfill", "C. Disposal Field", "D. Natural Ground"], a: 3 },
    { q: "Figure 3: What materials are acceptable for G?", choices: ["A. Straw", "B. Untreated Building Paper", "C. Marsh Hay", "D. All of these"], a: 3 },
    { q: "Who can operate mechanical works of 1500kW?", choices: ["A. CPM only", "B. ME & CPM", "C. ME & PME", "D. PME only"], a: 2 },
    { q: "Who is limited to operate mechanical works up to 300kW?", choices: ["A. CPM", "B. ME", "C. PME", "D. All of them"], a: 0 },
    { q: "What is the hanger rod size to support a 5\" pipe?", choices: ["A. 3/8\"", "B. 1/2\"", "C. 5/8\"", "D. 1\""], a: 1 },
    { q: "Volume of water in a 150x60mm horizontal cylinder at 48mm height?", choices: ["A. 424,115 mm³", "B. 363,730 mm³", "C. 339,292 mm³", "D. 60,385 mm³"], a: 1 },
    { q: "Figure 4: What is the total fixture unit at ground floor?", choices: ["A. 528", "B. 645", "C. 740", "D. 812"], a: 1 },
    { q: "Figure 4: Size of stack between 1st and Ground Floor?", choices: ["A. 75 mm", "B. 100 mm", "C. 127 mm", "D. 152 mm"], a: 3 },
    { q: "Figure 4: Size of stack between 4th and 3rd Floor?", choices: ["A. 75 mm", "B. 100 mm", "C. 127 mm", "D. 152 mm"], a: 3 },
    { q: "Figure 4: Size of house drain sloped at 2%?", choices: ["A. 75 mm", "B. 100 mm", "C. 127 mm", "D. 152 mm"], a: 3 },
    { q: "Branch vent serving 2+ traps extending from last fixture to vent stack.", choices: ["A. Circuit Vent", "B. Loop Vent", "C. Looped Vent", "D. Yoke Vent"], a: 0 },
    { q: "A waste pipe that also serves as a vent.", choices: ["A. Wet vent", "B. Dry vent", "C. Combination vent", "D. Fixture Vent"], a: 0 },
    { q: "Efficiency if 25hp is supplied and 14hp work is accomplished?", choices: ["A. 65%", "B. 56%", "C. 44%", "D. 79%"], a: 1 },
    { q: "Horsepower required to pump 4800 gpm against 80 ft head?", choices: ["A. 69 hp", "B. 1046 hp", "C. 97 hp", "D. 104 hp"], a: 2 },
    { q: "Efficiency of pump if water hp is 15hp and motor supplies 20hp?", choices: ["A. 75%", "B. 80%", "C. 20%", "D. 33%"], a: 0 },
    { q: "Water horsepower requirement for 875 gpm at 73.4 ft head?", choices: ["A. 17.41 hp", "B. 16.22 kW", "C. 12.09 kW", "D. 17.50 hp"], a: 2 },
    { q: "Stack vent shall terminate vertically not less than __ mm above roof.", choices: ["A. 15", "B. 0.3", "C. 300", "D. 150"], a: 2 },
    { q: "Identify 'A' in Fig. 5.", choices: ["A. Grease trap", "B. Floor trap", "C. Drum trap", "D. Interceptor"], a: 1 },
    { q: "In Figure 6, identify label A.", choices: ["A. Main Soil and Waste Vent", "B. Main Soil and Waste Stack", "C. Main Vent", "D. None of these"], a: 0 },
    { q: "In Figure 6, identify label C.", choices: ["A. Main Soil and Waste Vent", "B. Main Soil and Waste Stack", "C. Main Vent", "D. None of these"], a: 2 },
    { q: "In Figure 6, identify label D.", choices: ["A. Main Soil and Waste Vent", "B. Main Soil and Waste Stack", "C. Main Vent", "D. None of these"], a: 1 },
    { q: "In Figure 6, identify label B.", choices: ["A. Soil Branch", "B. Soil Stack", "C. Branch Vent", "D. Waste Branch"], a: 2 },
    { q: "In Figure 6, identify label E.", choices: ["A. Soil Branch", "B. Soil Stack", "C. Branch Vent", "D. Waste Branch"], a: 0 },
    { q: "In Figure 6, identify label F.", choices: ["A. Building sewer", "B. Soil branch", "C. Building drain", "D. House sewer"], a: 2 }
    ],
6: [
        { q: "Shannel’s birthday is 7 weeks and 5 days away. How many days away is her birthday?", choices: ["24 days", "54 days", "65 days", "75 days"], a: 1 },
        { q: "What is the next term of the given sequence of numbers: 1, 2, 6, 24, 120, ...?", choices: ["360", "480", "560", "720"], a: 3 }
    ],
    7: [
        { q: "A sedimentation basin is 60 feet in diameter. What is the surface area?", choices: ["2830 sq. ft", "1200 sq. ft", "1542 sq. ft", "2480 sq. ft"], a: 0 },
        { q: "Which of the following numbers can be divided evenly by 19?", choices: ["54", "63", "76", "82"], a: 2 }
    ],
    8: [
        { q: "Jenny has finished reading 30% of a 340-page novel. How many pages has she read?", choices: ["102", "106", "110", "120"], a: 0 },
        { q: "33 is 12% of what number?", choices: ["410", "330", "275", "910"], a: 2 }
    ],
    9: [
        { q: "What refers to the product of the force and the time during which a force acts?", choices: ["Impulse", "Momentum", "Power", "Energy"], a: 0 },
        { q: "Momentum is the product of:", choices: ["mass and time", "velocity and mass", "force and time", "force and mass"], a: 1 }
    ],
    10: [
        { q: "What is the unit of luminous flux?", choices: ["Candela", "Lumen", "Lux", "Footcandle"], a: 1 },
        { q: "Which of the following is equivalent to the unit 'candela'?", choices: ["lumen/m2", "foot-candle/steradian", "lux/steradian", "lumen/steradian"], a: 3 }
    ],
    11: [
        { q: "Land, buildings, plants and machinery are examples of:", choices: ["Current assets", "Trade investments", "Fixed assets", "Intangible assets"], a: 2 },
        { q: "A currency traded in a foreign exchange market for which the demand is consistently high.", choices: ["Money market", "Hard currency", "Treasury bill", "Certificate of deposit"], a: 1 }
    ],
    12: [
        { q: "What is the eccentricity of a circle?", choices: ["A. 1", "B. 0", "C. <1", "D. >1"], a: 1 },
        { q: "What is the air pressure exerted by 1 meter of water?", choices: ["A. 7.48 kPa", "B. 9.81 kPa", "C. 13.6 kPa", "D. 32.2 kPa"], a: 1 }
    ],
    13: [
        { q: "Additional information issued to prospective bidders prior to bidding date?", choices: ["Depict", "Escalate", "Assessment", "Bid bulletin"], a: 3 },
        { q: "Reduction in national income accompanied by a fall in general price levels?", choices: ["Devaluation", "Deflation", "Inflation", "Depreciation"], a: 1 }
    ],
    14: [
        { q: "This is a point where the concavity of a curve changes.", choices: ["Maximum point", "Minimum point", "Point of inflection", "Darsho's point"], a: 2 },
        { q: "Factoring is the process of expressing a polynomial as a:", choices: ["Rationalization", "Decomposition", "Product", "Darshon"], a: 2 }
    ],
    15: [
        { q: "The paper currency issued by the Central Bank.", choices: ["T-bills", "Bank note", "Check", "Coupon"], a: 1 },
        { q: "A repair job can be done by 7 people in 8.5 hours. How long for 4 people?", choices: ["4 hr 30 min", "14 hr 9 min", "4 hr 51 min", "14 hr 53 min"], a: 3 }
    ]

};


