export const toolsDB = {
     1: [
        { q: "What is a Cordless Drill primarily used for?", choices: ["A. Drilling and driving screws", "B. Measuring pipe", "C. Cutting metal", "D. Bending copper"], a: 0, img: "images/Cordless Drill .png" },
        { q: "What is a Drill Hammer used for?", choices: ["A. Removing nails", "B. Masonry drilling", "C. Cleaning pipes", "D. Threading pipe"], a: 1, img: "images/Drill Hammer.png" },
        { q: "An Angle Grinder is typically used for?", choices: ["A. Grinding and cutting metal", "B. Painting pipes", "C. Measuring angles", "D. Tightening nuts"], a: 0, img: "images/Angle Grinder.png" },
        { q: "What is a Sink Auger designed to clear?", choices: ["A. Main sewer lines", "B. Kitchen sink clogs", "C. Tree roots", "D. Vent pipes"], a: 1, img: "images/Sink Auger.png" },
        { q: "A Drain Machine is used for?", choices: ["A. Heavy-duty pipe clearing", "B. Soldering joints", "C. Measuring water flow", "D. Testing pressure"], a: 0, img: "images/Drain Machine.png" },
        { q: "What is a Toilet Auger used for?", choices: ["A. Clearing toilet blockages", "B. Drilling concrete", "C. Bending pipe", "D. Cutting tiles"], a: 0, img: "images/Toiler Auger.png" },
        { q: "A Flat File is used to?", choices: ["A. Smooth metal edges", "B. Tighten bolts", "C. Cut pipes", "D. Hammer nails"], a: 0, img: "images/Flat File.png" },
        { q: "What is a Cold Chisel used for?", choices: ["A. Cutting hard materials", "B. Measuring", "C. Polishing", "D. Painting"], a: 0, img: "images/Cold Chisel.png" },
        { q: "Plastic Pipe Shears are used for?", choices: ["A. Making square cuts in plastic", "B. Threading plastic", "C. Bending plastic", "D. Cleaning plastic"], a: 0, img: "images/plastic_pipe_shear.png" },
        { q: "What is a Hand Riveter used for?", choices: ["A. Fastening metal sheets", "B. Cutting wire", "C. Measuring", "D. Soldering"], a: 0, img: "images/hand_riveter.png" },
        { q: "Bolt Cutters are used for?", choices: ["A. Cutting bolts and rods", "B. Bending pipe", "C. Tightening nuts", "D. Drilling"], a: 0, img: "images/bolt_cutter.png" },
        { q: "An F-Clamp is used to?", choices: ["A. Hold materials together", "B. Measure length", "C. Cut wood", "D. Hammer"], a: 0, img: "images/f_clamp.png" },
        { q: "A C-Clamp is used to?", choices: ["A. Secure objects firmly", "B. Measure depth", "C. Drill holes", "D. File edges"], a: 0, img: "images/c_clamp.png" },
        { q: "A Ceiling Iron is used for?", choices: ["A. Caulking overhead joints", "B. Drilling ceilings", "C. Measuring heights", "D. Painting"], a: 0, img: "images/Ceiling Iron – square end .png" },
        { q: "What is an S-Type Caulking Iron used for?", choices: ["A. Packing joints in tight spots", "B. Cutting pipes", "C. Bending rods", "D. Drilling"], a: 0, img: "images/S -Type Caulking Iron.png" },
        { q: "A Left Iron is used for?", choices: ["A. Specialized caulking", "B. Cutting metal", "C. Measuring", "D. Hammering"], a: 0, img: "images/Left Iron.png" },
        { q: "A Stub Iron is used for?", choices: ["A. Short-reach caulking", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Stub Iron.png" },
        { q: "A Pick-out Iron is used to?", choices: ["A. Remove old caulking", "B. Hammer nails", "C. Cut wire", "D. File metal"], a: 0, img: "images/Pick-out Iron.png" },
        { q: "A standard Caulking Iron is for?", choices: ["A. Sealing pipe joints", "B. Measuring", "C. Drilling", "D. Bending"], a: 0, img: "images/Caulking Iron.png" },
        { q: "A Long Curved Offset Iron is for?", choices: ["A. Reaching awkward joints", "B. Cutting", "C. Hammering", "D. Filing"], a: 0, img: "images/Long curved offset Iron (square end) .png" },
        { q: "A Curved Offset Iron is used to?", choices: ["A. Seal inside/outside joints", "B. Measure", "C. Cut", "D. Drill"], a: 0, img: "images/Curved offset Iron (inside and outside) .png" },
        { q: "An Offset Yarning Iron is for?", choices: ["A. Packing yarn into joints", "B. Cutting pipe", "C. Drilling", "D. Filing"], a: 0, img: "images/Offset Yarning Iron.png" },
        { q: "A Spring Yarning Iron is used for?", choices: ["A. Flexible yarning", "B. Hammering", "C. Measuring", "D. Cutting"], a: 0, img: "images/Spring Yarning Iron.png" },
        { q: "A Core Drilling Machine is for?", choices: ["A. Making large holes in concrete", "B. Cutting wood", "C. Bending pipe", "D. Painting"], a: 0, img: "images/Core Drilling Machine.png" },
        { q: "A Geared Threader is used to?", choices: ["A. Cut threads on large pipe", "B. Bend pipe", "C. Measure", "D. File"], a: 0, img: "images/Geared Threader.png" },
        { q: "A Portable Cordless Drill is for?", choices: ["A. Mobile drilling tasks", "B. Cutting", "C. Measuring", "D. Hammering"], a: 0, img: "images/Portable Cordless Drill.png" },
        { q: "A Portable Roll Groover is for?", choices: ["A. Grooving pipe ends", "B. Cutting", "C. Threading", "D. Measuring"], a: 0, img: "images/Portable Roll Groover.png" },
        { q: "A Portable Electric Drill is for?", choices: ["A. Standard hole drilling", "B. Cutting", "C. Bending", "D. Filing"], a: 0, img: "images/Portable Electric Drill .png" },
        { q: "A Right Angle Drill is used for?", choices: ["A. Drilling in tight corners", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/Right Angle Drill.png" },
        { q: "A Reciprocating Orbital Saw is for?", choices: ["A. Rough cutting materials", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/Reciprocating Orbital Saw.png" },
        { q: "A Varl-orbit Jigsaw is used for?", choices: ["A. Intricate cutting", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Varl-orbit Jigsaw.png" },
        { q: "Smooth Jawed Pliers are for?", choices: ["A. Gripping without scratching", "B. Cutting wire", "C. Hammering", "D. Drilling"], a: 0, img: "images/Smooth Jawed Pliers .png" },
        { q: "Slip Joint Utility Pliers are for?", choices: ["A. Versatile gripping", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/Slip Joint Utility Pliers .png" },
        { q: "Slim Nose Pliers are for?", choices: ["A. Reaching narrow spaces", "B. Hammering", "C. Cutting pipe", "D. Drilling"], a: 0, img: "images/Slim Nose Pliers.png" },
        { q: "End Cutting Pliers are for?", choices: ["A. Cutting wire ends", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/End Cutting Pliers.png" },
        { q: "Long Reach Pliers are for?", choices: ["A. Deep-reach gripping", "B. Hammering", "C. Cutting", "D. Drilling"], a: 0, img: "images/Long Reach Pliers.png" },
        { q: "Long Reach Duckbill Pliers are for?", choices: ["A. Specialized reaching", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/Long Reach Duckbill Pliers.png" },
        { q: "Heavy Duty Side Cutting Pliers are for?", choices: ["A. Cutting thick wire", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Heavy Duty Side Cutting Pliers.png" },
        { q: "Universal Side Cutting Pliers are for?", choices: ["A. General wire cutting", "B. Drilling", "C. Hammering", "D. Measuring"], a: 0, img: "images/Universal Side Cutting Pliers.png" },
        { q: "Diagonal Cutting Pliers are for?", choices: ["A. Flush cutting wire", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Diagonal Cutting Pliers .png" },
        { q: "Lineman’s Side cutting Pliers are for?", choices: ["A. Electrical and wire work", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Lineman’s Side cutting Pliers.png" },
        { q: "Water Pump Pliers are for?", choices: ["A. Adjusting pipe fittings", "B. Cutting wire", "C. Measuring", "D. Drilling"], a: 0, img: "images/Water Pump Pliers .png" },
        { q: "Tongue and Groove Pliers are for?", choices: ["A. Adjustable gripping", "B. Cutting", "C. Measuring", "D. Drilling"], a: 0, img: "images/Tongue and Groove Pliers.png" },
        { q: "Power Hammers are used for?", choices: ["A. Heavy demolition", "B. Measuring", "C. Cutting", "D. Filing"], a: 0, img: "images/Power Hammers.png" },
        { q: "Long handle Sledge Hammer is for?", choices: ["A. Driving force/demolition", "B. Cutting", "C. Drilling", "D. Filing"], a: 0, img: "images/Long handle Sledge Hammer .png" },
        { q: "Hand Drilling Hammer is for?", choices: ["A. Driving masonry chisels", "B. Cutting pipe", "C. Measuring", "D. Painting"], a: 0, img: "images/Hand Drilling Hammer .png" },
        { q: "Tinner’s Hammer is for?", choices: ["A. Sheet metal work", "B. Drilling", "C. Measuring", "D. Cutting"], a: 0, img: "images/Tinner’s Hammer .png" },
        { q: "Mason’s Hammer is for?", choices: ["A. Breaking brick/stone", "B. Cutting wood", "C. Measuring", "D. Drilling"], a: 0, img: "images/Mason’s Hammer.png" },
        { q: "Curve Claw Hammer is for?", choices: ["A. Nail driving and pulling", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Curve Claw Hammer.png" },
        { q: "Engineers Hammer is for?", choices: ["A. Metalworking tasks", "B. Cutting", "C. Measuring", "D. Painting"], a: 0, img: "images/engineers_hammer.png" },
        { q: "Ripping Claw Hammer is for?", choices: ["A. Prying boards apart", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/Ripping Claw Hammer.png" },
        { q: "Half Hatchet Hammer is for?", choices: ["A. Light chopping/nailing", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Half Hatchet Hammer .png" },
        { q: "Ball Peen Hammer is for?", choices: ["A. Shaping metal/riveting", "B. Cutting", "C. Measuring", "D. Drilling"], a: 0, img: "images/ball_peen_hammer.png" },
        { q: "Pressure Test Pump is for?", choices: ["A. Leak testing pipelines", "B. Cutting pipe", "C. Drilling", "D. Filing"], a: 0, img: "images/Pressure Test Pump .png" },
        { q: "Inflatable Rubber Test Balls are for?", choices: ["A. Plugging pipe for testing", "B. Cutting", "C. Measuring", "D. Hammering"], a: 0, img: "images/Inflatable Rubber Test Balls.png" },
        { q: "Mechanical Test Plug is for?", choices: ["A. Sealing pipe ends", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Mechanical Test Plug .png" },
        { q: "Propane Torch is for?", choices: ["A. Soldering copper joints", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/propane_torch.png" },
        { q: "Blow Torch is for?", choices: ["A. High-heat heating", "B. Cutting", "C. Measuring", "D. Painting"], a: 0, img: "images/blow_torch.png" },
        { q: "Melting Pot Ladle is for?", choices: ["A. Pouring molten lead", "B. Drilling", "C. Measuring", "D. Hammering"], a: 0, img: "images/melting_pot_ladle.png" },
        { q: "Air Operated Plunger is for?", choices: ["A. Force clearing drains", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/air_operated_plunger.png" },
        { q: "Accordion Plunger is for?", choices: ["A. Toilet drain clearing", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/accordion_plunger.png" },
        { q: "Toilet Plunger is for?", choices: ["A. Clearing toilet clogs", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/toilet_plunger.png" },
        { q: "Sink Plunger is for?", choices: ["A. Clearing sink clogs", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/sink_plunger.png" },
        { q: "Drain Rods are for?", choices: ["A. Clearing deep drain lines", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/drain_rods.png" },
        { q: "Flue Brush is for?", choices: ["A. Cleaning flue pipes", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/flue_brush.png" },
        { q: "Chain Knocker is for?", choices: ["A. Scraping inside pipes", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/chain_knocker.png" },
        { q: "Grease C-Cutter is for?", choices: ["A. Cutting grease blockage", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/grease_c_cutter.png" },
        { q: "Shark Tooth Cutter is for?", choices: ["A. Breaking up roots", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/shark_tooth_cutter.png" },
        { q: "Spiral Bar Cutter is for?", choices: ["A. Clearing pipe walls", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/spiral_bar_cutter.png" },
        { q: "Four Blade Saw Tooth Cutter is for?", choices: ["A. Aggressive blockage removal", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/four_blade_saw_tooth_cutter.png" },
        { q: "Saw Tooth Cutter is for?", choices: ["A. Clearing root debris", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/saw_tooth_cutter.png" },
        { q: "Spiral Saw Tooth Cutter is for?", choices: ["A. Clearing heavy debris", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/spiral_saw_tooth_cutter.png" },
        { q: "Grease Cutter is for?", choices: ["A. Removing grease buildup", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/grease_cutter.png" },
        { q: "Spade Cutter is for?", choices: ["A. Cutting blockages", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/spade_cutter.png" },
        { q: "Retrieving Auger is for?", choices: ["A. Recovering lost tools", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/retrieving_auger.png" },
        { q: "Hook Auger is for?", choices: ["A. Snagging debris", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/hook_auger.png" },
        { q: "Funnel Auger is for?", choices: ["A. Clearing initial blockages", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/funnel_auger.png" },
        { q: "Straight Auger is for?", choices: ["A. Standard obstruction clearing", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/straight_auger.png" },
        { q: "Drop Head Auger is for?", choices: ["A. Negotiating drain bends", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/drop_head_auger.png" },
        { q: "Flat Sewer Taps are for?", choices: ["A. Tapping sewer lines", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Flat Sewer Taps.png" },
        { q: "Hand Spinner is for?", choices: ["A. Manual drain clearing", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/Hand Spinner.png" },
        { q: "Angle Pipe Welding Vise is for?", choices: ["A. Holding pipe for welding", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Angle Pipe Welding Vise.png" },
        { q: "Flange Pipe Welding Vise is for?", choices: ["A. Securing flanges for welding", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/Flange Pipe Welding Vise .png" },
        { q: "Elbow Pipe Welding Vise is for?", choices: ["A. Welding pipe elbows", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/Elbow Pipe Welding Vise.png" },
        { q: "Stand Chain Vise is for?", choices: ["A. Portable pipe holding", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/stand_chain_vise.png" },
        { q: "Bench Chain Vise is for?", choices: ["A. Stationary pipe holding", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/bench_chain_vise.png" },
        { q: "Bench Yoke Vise is for?", choices: ["A. Heavy-duty pipe holding", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/bench_yoke_vise.png" },
        { q: "Portable Tristand is for?", choices: ["A. On-site work support", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/portable_tristand.png" },
        { q: "Pipe Vise is for?", choices: ["A. Securing pipe for work", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/pipe_vise.png" },
        { q: "Tube Expander is for?", choices: ["A. Enlarging tube ends", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/tube_expander.png" },
        { q: "Geared-Ratchet Tube Bender is for?", choices: ["A. Bending rigid tubing", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/GEARED-RATCHET TUBE BENDER .png" },
        { q: "Level-Type Tube Bender is for?", choices: ["A. Precise manual bending", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/LEVEL-TYPE TUBE BENDER.png" },
        { q: "Spring-Type Tube Bender is for?", choices: ["A. Preventing tubing kinks", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/SPRING-TYPE TUBE BENDER .png" },
        { q: "Pipe Extractor is for?", choices: ["A. Removing broken pipe ends", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/pipe_extractor.png" },
        { q: "Combination Pipe Reamer is for?", choices: ["A. Removing internal burrs", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/COMBINATION PIPE REAMER.png" },
        { q: "Spiral Ratchet Pipe Reamer is for?", choices: ["A. Removing pipe burrs", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/SPIRAL RATCHET PIPE REAMER.png" },
        { q: "Pipe Tap is for?", choices: ["A. Cutting internal threads", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/pipe_tap.png" },
        { q: "Pipe Threader is for?", choices: ["A. Cutting external threads", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/pipe_threader.png" },
        { q: "Hacksaw is for?", choices: ["A. Manual metal cutting", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/hacksaw.png" },
        { q: "Soil Pipe Cutter is for?", choices: ["A. Cutting heavy soil pipe", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/soil_pipe_cutter.png" },
        { q: "Plastic Pipe Cutter is for?", choices: ["A. Cutting plastic lines", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/plastic_pipe_cutter.png" },
        { q: "Mini Tube Cutter is for?", choices: ["A. Tight-space tube cutting", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/mini_tube_cutter.png" },
        { q: "Ratchet Cutter is for?", choices: ["A. High-leverage cutting", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/ratchet_cutter.png" },
        { q: "Hinged Pipe Cutter is for?", choices: ["A. Cutting installed pipe", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/hinged_pipe_cutter.png" },
        { q: "Wide Roll Pipe Cutter is for?", choices: ["A. Precise square cutting", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/wide_roll_pipe_cutter.png" },
        { q: "4 Wheel Pipe Cutter is for?", choices: ["A. Tight-space rotation cutting", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/4_wheel_pipe_cutter.png" },
        { q: "Single Ended Jaw Chain is for?", choices: ["A. Gripping pipe", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/SIGLE ENDED JAW CHAIN .png" },
        { q: "Reversible Chain Tongs are for?", choices: ["A. Turning pipe in both directions", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/REVERSIBLE CHAIN TONGS .png" },
        { q: "The Hawk Heavy Duty Wrench is for?", choices: ["A. Self-adjusting grip", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/THE HAWK HEAVY DUTY SELF - ADJUSTMENT PIPE WRENCH.png" },
        { q: "Chain Wrench is for?", choices: ["A. Heavy-duty pipe turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/chain_wrench.png" },
        { q: "Bionic Wrench is for?", choices: ["A. Universal nut adjustment", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/bionic_wrench.png" },
        { q: "Basket Strainer Wrench is for?", choices: ["A. Tightening sink strainers", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/basket_strainer_wrench.png" },
        { q: "Curb Box Wrench is for?", choices: ["A. Accessing water curb boxes", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/curb_box_wrench.png" },
        { q: "Packing Nut Socket is for?", choices: ["A. Tightening packing nuts", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/packing_nut_socket.png" },
        { q: "Basin Wrench is for?", choices: ["A. Sink mounting nuts", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/basin_wrench.png" },
        { q: "Crowfoot Wrench is for?", choices: ["A. Hard-to-reach bolts", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/crawfoot’s_wrench.png" },
        { q: "Ratcheting Rotary Wrench is for?", choices: ["A. Fast rotation turning", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/ratcheting_rotary_wrench.png" },
        { q: "Closet Wrench is for?", choices: ["A. Toilet hardware", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/closet_wrench.png" },
        { q: "Valve Seat Wrench is for?", choices: ["A. Removing valve seats", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/valve_seat_wrench.png" },
        { q: "Allen Wrench is for?", choices: ["A. Hex socket screws", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/allen_wrench.png" },
        { q: "Hex Wrench is for?", choices: ["A. Hex head bolts", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/hex_wrench.png" },
        { q: "Internal Wrench is for?", choices: ["A. Nipple extraction", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/internal_wrench.png" },
        { q: "Torque Wrench is for?", choices: ["A. Precise tightening force", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/torque_wrench.png" },
        { q: "Jaw Dropper Wrench is for?", choices: ["A. Specialized gripping", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/jaw_dropper_wrench.png" },
        { q: "Strap Wrench is for?", choices: ["A. Non-marring grip", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/strap_wrench.png" },
        { q: "Monkey Wrench is for?", choices: ["A. Classic flat-jaw turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/monkey_wrench.png" },
        { q: "Pin Wrench is for?", choices: ["A. Adjustable pin turning", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/pin_wrench.png" },
        { q: "Erection Spud Wrench is for?", choices: ["A. Aligning holes/bolts", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/erection_spud_wrench.png" },
        { q: "Adjustable Wrench is for?", choices: ["A. Various nut sizes", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/adjustable_wrench.png" },
        { q: "Locking Wrench is for?", choices: ["A. Vise-grip fastening", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/locking_wrench.png" },
        { q: "Adjustable Spud Wrench is for?", choices: ["A. Spud fittings", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/adjustable_spud_wrench..png" },
        { q: "Offset Pipe Wrench is for?", choices: ["A. Tight-space pipe turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/offset_pipe_wrench.png" },
        { q: "Compound Leverage Wrench is for?", choices: ["A. High-force pipe turning", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/compound_leverage_wrench.png" },
        { q: "Rap Wrench is for?", choices: ["A. Quick-release turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/rap_wrench.png" },
        { q: "End Pipe Wrench is for?", choices: ["A. Pipe against walls", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/end_pipe_wrench.png" },
        { q: "Stillson Wrench is for?", choices: ["A. Classic pipe turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/stillson_wrench.png" },
        { q: "Standard Pipe Wrench is for?", choices: ["A. General pipe installation", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/pipe_wrench.png" },
        { q: "Air Impact is for?", choices: ["A. High-speed bolt removal", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/Air Impact .png" }
    ],
    2: [
        { q: "A tool primarily used for drilling and driving screws.", choices: ["Cordless Drill", "Hammer Drill", "Impact Driver", "Right Angle Drill"], a: 0, img: "images/Cordless Drill .png" },
        { q: "A tool specifically designed for masonry drilling.", choices: ["Drill Hammer", "Impact Driver", "Core Drill", "Rotary Hammer"], a: 0, img: "images/Drill Hammer.png" },
        { q: "A tool typically used for grinding and cutting metal.", choices: ["Angle Grinder", "Die Grinder", "Cut-off Saw", "Reciprocating Saw"], a: 0, img: "images/Angle Grinder.png" },
        { q: "A device designed to clear kitchen sink clogs.", choices: ["Sink Auger", "Toilet Auger", "Drain Snake", "Plunger"], a: 0, img: "images/Sink Auger.png" },
        { q: "A heavy-duty machine used for clearing pipes.", choices: ["Drain Machine", "Pressure Washer", "Pipe Cutter", "Root Cutter"], a: 0, img: "images/Drain Machine.png" },
        { q: "A tool specifically used for clearing toilet blockages.", choices: ["Toiler Auger", "Sink Auger", "Drain Rod", "Plunger"], a: 0, img: "images/Toiler Auger.png" },
        { q: "A hand tool used to smooth metal edges.", choices: ["Flat File", "Rasp", "Cold Chisel", "Grinding Stone"], a: 0, img: "images/Flat File.png" },
        { q: "A tool used for cutting hard materials.", choices: ["Cold Chisel", "Flat File", "Hacksaw", "Bolt Cutter"], a: 0, img: "images/Cold Chisel.png" },
        { q: "A tool used for making square cuts in plastic pipe.", choices: ["Plastic Pipe Shears", "PVC Saw", "Ratchet Cutter", "Hacksaw"], a: 0, img: "images/plastic_pipe_shear.png" },
        { q: "A tool used for fastening metal sheets together.", choices: ["Hand Riveter", "Staple Gun", "Welder", "Soldering Iron"], a: 0, img: "images/hand_riveter.png" },
        { q: "A tool used for cutting bolts and rods.", choices: ["Bolt Cutters", "Hacksaw", "Ratchet Cutter", "Angle Grinder"], a: 0, img: "images/bolt_cutter.png" },
        { q: "A clamp used to hold materials together.", choices: ["F-Clamp", "C-Clamp", "Bar Clamp", "Spring Clamp"], a: 0, img: "images/f_clamp.png" },
        { q: "A clamp used to secure objects firmly.", choices: ["C-Clamp", "F-Clamp", "Quick-Grip Clamp", "Pipe Clamp"], a: 0, img: "images/c_clamp.png" },
        { q: "A tool used for caulking overhead joints.", choices: ["Ceiling Iron", "S-Type Caulking Iron", "Stub Iron", "Offset Iron"], a: 0, img: "images/Ceiling Iron – square end .png" },
        { q: "A tool used for packing joints in tight spots.", choices: ["S-Type Caulking Iron", "Yarning Iron", "Offset Iron", "Stub Iron"], a: 0, img: "images/S -Type Caulking Iron.png" },
        { q: "A specialized caulking tool.", choices: ["Left Iron", "Stub Iron", "Pick-out Iron", "Curved Offset Iron"], a: 0, img: "images/Left Iron.png" },
        { q: "A tool designed for short-reach caulking tasks.", choices: ["Stub Iron", "Left Iron", "Caulking Iron", "Ceiling Iron"], a: 0, img: "images/Stub Iron.png" },
        { q: "A tool used to remove old caulking.", choices: ["Pick-out Iron", "Caulking Iron", "Offset Yarning Iron", "Spring Yarning Iron"], a: 0, img: "images/Pick-out Iron.png" },
        { q: "A standard tool for sealing pipe joints.", choices: ["Caulking Iron", "Pick-out Iron", "Stub Iron", "Yarning Iron"], a: 0, img: "images/Caulking Iron.png" },
        { q: "A tool for reaching awkward joints.", choices: ["Long Curved Offset Iron", "Curved Offset Iron", "Offset Yarning Iron", "Spring Yarning Iron"], a: 0, img: "images/Long curved offset Iron (square end) .png" },
        { q: "A tool for sealing inside and outside joints.", choices: ["Curved Offset Iron", "Long Curved Offset Iron", "Ceiling Iron", "Caulking Iron"], a: 0, img: "images/Curved offset Iron (inside and outside) .png" },
        { q: "A tool for packing yarn into pipe joints.", choices: ["Offset Yarning Iron", "Spring Yarning Iron", "Caulking Iron", "Pick-out Iron"], a: 0, img: "images/Offset Yarning Iron.png" },
        { q: "A flexible tool used for yarning.", choices: ["Spring Yarning Iron", "Offset Yarning Iron", "Stub Iron", "Ceiling Iron"], a: 0, img: "images/Spring Yarning Iron.png" },
        { q: "A machine used for making large holes in concrete.", choices: ["Core Drilling Machine", "Rotary Hammer", "Right Angle Drill", "Hammer Drill"], a: 0, img: "images/Core Drilling Machine.png" },
        { q: "A tool used to cut threads on large pipes.", choices: ["Geared Threader", "Hand Threader", "Pipe Tap", "Roll Groover"], a: 0, img: "images/Geared Threader.png" },
        { q: "A tool designed for mobile drilling tasks.", choices: ["Portable Cordless Drill", "Portable Electric Drill", "Right Angle Drill", "Hammer Drill"], a: 0, img: "images/Portable Cordless Drill.png" },
        { q: "A tool used for grooving pipe ends.", choices: ["Portable Roll Groover", "Geared Threader", "Pipe Threader", "Combination Pipe Reamer"], a: 0, img: "images/Portable Roll Groover.png" },
        { q: "A tool for standard hole drilling.", choices: ["Portable Electric Drill", "Portable Cordless Drill", "Right Angle Drill", "Core Drill"], a: 0, img: "images/Portable Electric Drill .png" },
        { q: "A tool used for drilling in tight corners.", choices: ["Right Angle Drill", "Electric Drill", "Hammer Drill", "Impact Driver"], a: 0, img: "images/Right Angle Drill.png" },
        { q: "A saw used for rough cutting materials.", choices: ["Reciprocating Orbital Saw", "Orbital Jigsaw", "Hacksaw", "Soil Pipe Cutter"], a: 0, img: "images/Reciprocating Orbital Saw.png" },
        { q: "A tool used for intricate cutting.", choices: ["Varl-orbit Jigsaw", "Reciprocating Saw", "Hacksaw", "Plastic Pipe Cutter"], a: 0, img: "images/Varl-orbit Jigsaw.png" },
        { q: "Pliers designed for gripping without scratching.", choices: ["Smooth Jawed Pliers", "Slip Joint Pliers", "Slim Nose Pliers", "Water Pump Pliers"], a: 0, img: "images/Smooth Jawed Pliers .png" },
        { q: "Pliers used for versatile gripping.", choices: ["Slip Joint Utility Pliers", "Smooth Jawed Pliers", "Water Pump Pliers", "Tongue and Groove Pliers"], a: 0, img: "images/Slip Joint Utility Pliers .png" },
        { q: "Pliers used for reaching narrow spaces.", choices: ["Slim Nose Pliers", "Long Reach Pliers", "Duckbill Pliers", "Smooth Jawed Pliers"], a: 0, img: "images/Slim Nose Pliers.png" },
        { q: "Pliers used for cutting wire ends.", choices: ["End Cutting Pliers", "Diagonal Cutting Pliers", "Side Cutting Pliers", "Lineman's Pliers"], a: 0, img: "images/End Cutting Pliers.png" },
        { q: "Pliers used for deep-reach gripping.", choices: ["Long Reach Pliers", "Duckbill Pliers", "Slim Nose Pliers", "Smooth Jawed Pliers"], a: 0, img: "images/Long Reach Pliers.png" },
        { q: "Pliers used for specialized reaching.", choices: ["Long Reach Duckbill Pliers", "Long Reach Pliers", "Slim Nose Pliers", "Smooth Jawed Pliers"], a: 0, img: "images/Long Reach Duckbill Pliers.png" },
        { q: "Pliers used for cutting thick wire.", choices: ["Heavy Duty Side Cutting Pliers", "Universal Side Cutting Pliers", "Diagonal Pliers", "End Cutting Pliers"], a: 0, img: "images/Heavy Duty Side Cutting Pliers.png" },
        { q: "Pliers used for general wire cutting.", choices: ["Universal Side Cutting Pliers", "Lineman’s Side cutting Pliers", "Diagonal Pliers", "Side Cutting Pliers"], a: 0, img: "images/Universal Side Cutting Pliers.png" },
        { q: "Pliers used for flush cutting wire.", choices: ["Diagonal Cutting Pliers", "End Cutting Pliers", "Side Cutting Pliers", "Universal Pliers"], a: 0, img: "images/Diagonal Cutting Pliers .png" },
        { q: "Pliers used for electrical and wire work.", choices: ["Lineman’s Side cutting Pliers", "Universal Pliers", "Diagonal Pliers", "Side Cutting Pliers"], a: 0, img: "images/Lineman’s Side cutting Pliers.png" },
        { q: "Pliers used for adjusting pipe fittings.", choices: ["Water Pump Pliers", "Tongue and Groove Pliers", "Slip Joint Pliers", "Smooth Jawed Pliers"], a: 0, img: "images/Water Pump Pliers .png" },
        { q: "Pliers used for adjustable gripping.", choices: ["Tongue and Groove Pliers", "Water Pump Pliers", "Slip Joint Pliers", "Smooth Jawed Pliers"], a: 0, img: "images/Tongue and Groove Pliers.png" },
        { q: "Hammers used for heavy demolition.", choices: ["Power Hammers", "Sledge Hammer", "Drilling Hammer", "Claw Hammer"], a: 0, img: "images/Power Hammers.png" },
        { q: "A hammer used for driving force and demolition.", choices: ["Long handle Sledge Hammer", "Power Hammer", "Drilling Hammer", "Mason’s Hammer"], a: 0, img: "images/Long handle Sledge Hammer .png" },
        { q: "A hammer used for driving masonry chisels.", choices: ["Hand Drilling Hammer", "Mason’s Hammer", "Tinner’s Hammer", "Ball Peen Hammer"], a: 0, img: "images/Hand Drilling Hammer .png" },
        { q: "A hammer used for sheet metal work.", choices: ["Tinner’s Hammer", "Mason’s Hammer", "Half Hatchet", "Engineer’s Hammer"], a: 0, img: "images/Tinner’s Hammer .png" },
        { q: "A hammer used for breaking brick or stone.", choices: ["Mason’s Hammer", "Tinner’s Hammer", "Drilling Hammer", "Sledge Hammer"], a: 0, img: "images/Mason’s Hammer.png" },
        { q: "A hammer used for driving and pulling nails.", choices: ["Curve Claw Hammer", "Ripping Claw", "Half Hatchet", "Engineer’s Hammer"], a: 0, img: "images/Curve Claw Hammer.png" },
        { q: "A hammer used for metalworking tasks.", choices: ["Engineer’s Hammer", "Ball Peen Hammer", "Tinner’s Hammer", "Half Hatchet"], a: 0, img: "images/engineers_hammer.png" },
        { q: "A hammer used for prying boards apart.", choices: ["Ripping Claw Hammer", "Curve Claw Hammer", "Half Hatchet", "Mason’s Hammer"], a: 0, img: "images/Ripping Claw Hammer.png" },
        { q: "A hammer used for light chopping or nailing.", choices: ["Half Hatchet Hammer", "Tinner’s Hammer", "Curve Claw Hammer", "Ripping Claw Hammer"], a: 0, img: "images/Half Hatchet Hammer .png" },
        { q: "A hammer used for shaping metal or riveting.", choices: ["Ball Peen Hammer", "Engineer’s Hammer", "Tinner’s Hammer", "Drilling Hammer"], a: 0, img: "images/ball_peen_hammer.png" },
        { q: "A pump used for leak testing pipelines.", choices: ["Pressure Test Pump", "Test Plug", "Rubber Test Ball", "Roll Groover"], a: 0, img: "images/Pressure Test Pump .png" },
        { q: "Devices used for plugging pipe during testing.", choices: ["Inflatable Rubber Test Balls", "Mechanical Test Plug", "Pressure Pump", "Drain Rods"], a: 0, img: "images/Inflatable Rubber Test Balls.png" },
        { q: "A plug used for sealing pipe ends.", choices: ["Mechanical Test Plug", "Inflatable Test Ball", "Pressure Pump", "Drain Rods"], a: 0, img: "images/Mechanical Test Plug .png" },
        { q: "A torch used for soldering copper joints.", choices: ["Propane Torch", "Blow Torch", "Melting Ladle", "Pressure Pump"], a: 0, img: "images/propane_torch.png" },
        { q: "A torch used for high-heat applications.", choices: ["Blow Torch", "Propane Torch", "Melting Ladle", "Pressure Pump"], a: 0, img: "images/blow_torch.png" },
        { q: "A tool used for pouring molten lead.", choices: ["Melting Pot Ladle", "Blow Torch", "Propane Torch", "Caulking Iron"], a: 0, img: "images/melting_pot_ladle.png" },
        { q: "A device used for force-clearing drains.", choices: ["Air Operated Plunger", "Toilet Plunger", "Sink Plunger", "Accordion Plunger"], a: 0, img: "images/air_operated_plunger.png" },
        { q: "A plunger designed for toilet drain clearing.", choices: ["Accordion Plunger", "Toilet Plunger", "Sink Plunger", "Air Operated Plunger"], a: 0, img: "images/accordion_plunger.png" },
        { q: "A standard plunger for toilet clogs.", choices: ["Toilet Plunger", "Sink Plunger", "Accordion Plunger", "Air Operated Plunger"], a: 0, img: "images/toilet_plunger.png" },
        { q: "A plunger for clearing sink clogs.", choices: ["Sink Plunger", "Toilet Plunger", "Accordion Plunger", "Air Operated Plunger"], a: 0, img: "images/sink_plunger.png" },
        { q: "Rods used for clearing deep drain lines.", choices: ["Drain Rods", "Flue Brush", "Chain Knocker", "Grease Cutter"], a: 0, img: "images/drain_rods.png" },
        { q: "A brush used for cleaning flue pipes.", choices: ["Flue Brush", "Drain Rods", "Chain Knocker", "Grease Cutter"], a: 0, img: "images/flue_brush.png" },
        { q: "A tool for scraping the inside of pipes.", choices: ["Chain Knocker", "Grease C-Cutter", "Shark Tooth Cutter", "Spiral Bar Cutter"], a: 0, img: "images/chain_knocker.png" },
        { q: "A cutter used for grease blockages.", choices: ["Grease C-Cutter", "Grease Cutter", "Shark Tooth Cutter", "Spiral Bar Cutter"], a: 0, img: "images/grease_c_cutter.png" },
        { q: "A cutter used for breaking up roots.", choices: ["Shark Tooth Cutter", "Saw Tooth Cutter", "Spiral Saw Tooth Cutter", "Four Blade Cutter"], a: 0, img: "images/shark_tooth_cutter.png" },
        { q: "A cutter for clearing pipe walls.", choices: ["Spiral Bar Cutter", "Grease C-Cutter", "Grease Cutter", "Spade Cutter"], a: 0, img: "images/spiral_bar_cutter.png" },
        { q: "A cutter for aggressive blockage removal.", choices: ["Four Blade Saw Tooth Cutter", "Saw Tooth Cutter", "Spiral Saw Tooth", "Shark Tooth Cutter"], a: 0, img: "images/four_blade_saw_tooth_cutter.png" },
        { q: "A cutter used for clearing root debris.", choices: ["Saw Tooth Cutter", "Spiral Saw Tooth Cutter", "Four Blade Cutter", "Shark Tooth Cutter"], a: 0, img: "images/saw_tooth_cutter.png" },
        { q: "A cutter for clearing heavy debris.", choices: ["Spiral Saw Tooth Cutter", "Saw Tooth Cutter", "Four Blade Cutter", "Grease Cutter"], a: 0, img: "images/spiral_saw_tooth_cutter.png" },
        { q: "A tool for removing grease buildup.", choices: ["Grease Cutter", "Grease C-Cutter", "Spade Cutter", "Four Blade Cutter"], a: 0, img: "images/grease_cutter.png" },
        { q: "A cutter used for cutting blockages.", choices: ["Spade Cutter", "Grease Cutter", "Shark Tooth Cutter", "Funnel Auger"], a: 0, img: "images/spade_cutter.png" },
        { q: "A tool used for recovering lost items in pipes.", choices: ["Retrieving Auger", "Hook Auger", "Funnel Auger", "Straight Auger"], a: 0, img: "images/retrieving_auger.png" },
        { q: "An auger used for snagging debris.", choices: ["Hook Auger", "Retrieving Auger", "Funnel Auger", "Straight Auger"], a: 0, img: "images/hook_auger.png" },
        { q: "An auger for clearing initial blockages.", choices: ["Funnel Auger", "Straight Auger", "Drop Head Auger", "Retrieving Auger"], a: 0, img: "images/funnel_auger.png" },
        { q: "An auger for standard obstruction clearing.", choices: ["Straight Auger", "Funnel Auger", "Drop Head Auger", "Retrieving Auger"], a: 0, img: "images/straight_auger.png" },
        { q: "An auger for negotiating drain bends.", choices: ["Drop Head Auger", "Straight Auger", "Funnel Auger", "Hook Auger"], a: 0, img: "images/drop_head_auger.png" },
        { q: "Tools used for tapping sewer lines.", choices: ["Flat Sewer Taps", "Hand Spinner", "Drain Rods", "Grease Cutter"], a: 0, img: "images/Flat Sewer Taps.png" },
        { q: "A tool for manual drain clearing.", choices: ["Hand Spinner", "Flat Sewer Taps", "Drain Rods", "Toilet Plunger"], a: 0, img: "images/Hand Spinner.png" },
        { q: "A vise used for holding pipe for welding.", choices: ["Angle Pipe Welding Vise", "Flange Vise", "Elbow Vise", "Chain Vise"], a: 0, img: "images/Angle Pipe Welding Vise.png" },
        { q: "A vise used for securing flanges for welding.", choices: ["Flange Pipe Welding Vise", "Angle Vise", "Elbow Vise", "Chain Vise"], a: 0, img: "images/Flange Pipe Welding Vise .png" },
        { q: "A vise used for welding pipe elbows.", choices: ["Elbow Pipe Welding Vise", "Angle Vise", "Flange Vise", "Pipe Vise"], a: 0, img: "images/Elbow Pipe Welding Vise.png" },
        { q: "A portable pipe-holding stand.", choices: ["Stand Chain Vise", "Bench Chain Vise", "Bench Yoke Vise", "Tristand"], a: 0, img: "images/stand_chain_vise.png" },
        { q: "A stationary chain vise for holding pipe.", choices: ["Bench Chain Vise", "Stand Chain Vise", "Bench Yoke Vise", "Pipe Vise"], a: 0, img: "images/bench_chain_vise.png" },
        { q: "A heavy-duty vise for holding pipe.", choices: ["Bench Yoke Vise", "Bench Chain Vise", "Stand Chain Vise", "Pipe Vise"], a: 0, img: "images/bench_yoke_vise.png" },
        { q: "A portable stand for on-site work support.", choices: ["Portable Tristand", "Stand Chain Vise", "Bench Chain Vise", "Pipe Vise"], a: 0, img: "images/portable_tristand.png" },
        { q: "A tool for securing pipe during work.", choices: ["Pipe Vise", "Bench Yoke Vise", "Stand Chain Vise", "Bench Chain Vise"], a: 0, img: "images/pipe_vise.png" },
        { q: "A tool for enlarging tube ends.", choices: ["Tube Expander", "Ratchet Bender", "Level Bender", "Spring Bender"], a: 0, img: "images/tube_expander.png" },
        { q: "A tool for bending rigid tubing.", choices: ["Geared-Ratchet Tube Bender", "Level Bender", "Spring Bender", "Tube Expander"], a: 0, img: "images/GEARED-RATCHET TUBE BENDER .png" },
        { q: "A tool for precise manual tube bending.", choices: ["Level-Type Tube Bender", "Ratchet Bender", "Spring Bender", "Tube Expander"], a: 0, img: "images/LEVEL-TYPE TUBE BENDER.png" },
        { q: "A tool used for preventing tubing kinks.", choices: ["Spring-Type Tube Bender", "Ratchet Bender", "Level Bender", "Tube Expander"], a: 0, img: "images/SPRING-TYPE TUBE BENDER .png" },
        { q: "A tool for removing broken pipe ends.", choices: ["Pipe Extractor", "Reamer", "Ratchet Reamer", "Pipe Tap"], a: 0, img: "images/pipe_extractor.png" },
        { q: "A tool for removing internal pipe burrs.", choices: ["Combination Pipe Reamer", "Spiral Ratchet Reamer", "Pipe Tap", "Extractor"], a: 0, img: "images/COMBINATION PIPE REAMER.png" },
        { q: "A tool for removing pipe burrs.", choices: ["Spiral Ratchet Pipe Reamer", "Combination Reamer", "Pipe Tap", "Extractor"], a: 0, img: "images/SPIRAL RATCHET PIPE REAMER.png" },
        { q: "A tool used for cutting internal pipe threads.", choices: ["Pipe Tap", "Pipe Threader", "Geared Threader", "Roll Groover"], a: 0, img: "images/pipe_tap.png" },
        { q: "A tool used for cutting external pipe threads.", choices: ["Pipe Threader", "Pipe Tap", "Geared Threader", "Tube Bender"], a: 0, img: "images/pipe_threader.png" },
        { q: "A tool for manual metal cutting.", choices: ["Hacksaw", "Soil Pipe Cutter", "Plastic Cutter", "Tube Cutter"], a: 0, img: "images/hacksaw.png" },
        { q: "A tool for cutting heavy soil pipe.", choices: ["Soil Pipe Cutter", "Plastic Cutter", "Ratchet Cutter", "Hinged Cutter"], a: 0, img: "images/soil_pipe_cutter.png" },
        { q: "A tool for cutting plastic lines.", choices: ["Plastic Pipe Cutter", "Shears", "Soil Cutter", "Tube Cutter"], a: 0, img: "images/plastic_pipe_cutter.png" },
        { q: "A tool for tube cutting in tight spaces.", choices: ["Mini Tube Cutter", "Ratchet Cutter", "Hinged Cutter", "Wide Roll Cutter"], a: 0, img: "images/mini_tube_cutter.png" },
        { q: "A tool for high-leverage pipe cutting.", choices: ["Ratchet Cutter", "Hinged Cutter", "Wide Roll Cutter", "4 Wheel Cutter"], a: 0, img: "images/ratchet_cutter.png" },
        { q: "A tool for cutting installed pipes.", choices: ["Hinged Pipe Cutter", "Ratchet Cutter", "Wide Roll Cutter", "4 Wheel Cutter"], a: 0, img: "images/hinged_pipe_cutter.png" },
        { q: "A tool for precise square pipe cutting.", choices: ["Wide Roll Pipe Cutter", "4 Wheel Cutter", "Hinged Cutter", "Ratchet Cutter"], a: 0, img: "images/wide_roll_pipe_cutter.png" },
        { q: "A cutter for tight-space pipe rotation.", choices: ["4 Wheel Pipe Cutter", "Wide Roll Cutter", "Hinged Cutter", "Mini Tube Cutter"], a: 0, img: "images/4_wheel_pipe_cutter.png" },
        { q: "A chain tool used for gripping pipe.", choices: ["Single Ended Jaw Chain", "Chain Tongs", "Chain Wrench", "Strap Wrench"], a: 0, img: "images/SIGLE ENDED JAW CHAIN .png" },
        { q: "A tool for turning pipe in both directions.", choices: ["Reversible Chain Tongs", "Chain Wrench", "Jaw Chain", "Monkey Wrench"], a: 0, img: "images/REVERSIBLE CHAIN TONGS .png" },
        { q: "A wrench featuring a self-adjusting grip.", choices: ["The Hawk Heavy Duty Wrench", "Chain Wrench", "Stillson Wrench", "Standard Wrench"], a: 0, img: "images/THE HAWK HEAVY DUTY SELF - ADJUSTMENT PIPE WRENCH.png" },
        { q: "A heavy-duty wrench for pipe turning.", choices: ["Chain Wrench", "Reversible Tongs", "Standard Wrench", "Stillson Wrench"], a: 0, img: "images/chain_wrench.png" },
        { q: "A wrench used for universal nut adjustment.", choices: ["Bionic Wrench", "Adjustable Wrench", "Monkey Wrench", "Strap Wrench"], a: 0, img: "images/bionic_wrench.png" },
        { q: "A tool used for tightening sink strainers.", choices: ["Basket Strainer Wrench", "Basin Wrench", "Packing Socket", "Valve Seat Wrench"], a: 0, img: "images/basket_strainer_wrench.png" },
        { q: "A tool used for accessing water curb boxes.", choices: ["Curb Box Wrench", "Basin Wrench", "Closet Wrench", "Packing Socket"], a: 0, img: "images/curb_box_wrench.png" },
        { q: "A tool used for tightening packing nuts.", choices: ["Packing Nut Socket", "Basin Wrench", "Closet Wrench", "Valve Seat Wrench"], a: 0, img: "images/packing_nut_socket.png" },
        { q: "A tool for reaching sink mounting nuts.", choices: ["Basin Wrench", "Strainer Wrench", "Closet Wrench", "Packing Socket"], a: 0, img: "images/basin_wrench.png" },
        { q: "A wrench designed for hard-to-reach bolts.", choices: ["Crowfoot Wrench", "Rotary Wrench", "Allen Wrench", "Hex Wrench"], a: 0, img: "images/crawfoot’s_wrench.png" },
        { q: "A wrench for fast-rotation turning.", choices: ["Ratcheting Rotary Wrench", "Crowfoot Wrench", "Adjustable Wrench", "Torque Wrench"], a: 0, img: "images/ratcheting_rotary_wrench.png" },
        { q: "A wrench used for toilet hardware.", choices: ["Closet Wrench", "Basin Wrench", "Valve Seat Wrench", "Packing Socket"], a: 0, img: "images/closet_wrench.png" },
        { q: "A tool used for removing valve seats.", choices: ["Valve Seat Wrench", "Closet Wrench", "Basin Wrench", "Packing Socket"], a: 0, img: "images/valve_seat_wrench.png" },
        { q: "A wrench used for hex socket screws.", choices: ["Allen Wrench", "Hex Wrench", "Adjustable Wrench", "Locking Wrench"], a: 0, img: "images/allen_wrench.png" },
        { q: "A wrench used for hex head bolts.", choices: ["Hex Wrench", "Allen Wrench", "Adjustable Wrench", "Locking Wrench"], a: 0, img: "images/hex_wrench.png" },
        { q: "A tool for nipple extraction.", choices: ["Internal Wrench", "Pipe Extractor", "Stillson Wrench", "Standard Wrench"], a: 0, img: "images/internal_wrench.png" },
        { q: "A tool used for applying precise tightening force.", choices: ["Torque Wrench", "Adjustable Wrench", "Locking Wrench", "Stillson Wrench"], a: 0, img: "images/torque_wrench.png" },
        { q: "A wrench with specialized gripping.", choices: ["Jaw Dropper Wrench", "Bionic Wrench", "Stillson Wrench", "Monkey Wrench"], a: 0, img: "images/jaw_dropper_wrench.png" },
        { q: "A wrench that provides a non-marring grip.", choices: ["Strap Wrench", "Chain Wrench", "Monkey Wrench", "Adjustable Wrench"], a: 0, img: "images/strap_wrench.png" },
        { q: "A classic flat-jaw turning wrench.", choices: ["Monkey Wrench", "Adjustable Wrench", "Stillson Wrench", "Standard Wrench"], a: 0, img: "images/monkey_wrench.png" },
        { q: "A tool for adjustable pin turning.", choices: ["Pin Wrench", "Adjustable Wrench", "Monkey Wrench", "Torque Wrench"], a: 0, img: "images/pin_wrench.png" },
        { q: "A wrench for aligning holes and bolts.", choices: ["Erection Spud Wrench", "Adjustable Spud Wrench", "Adjustable Wrench", "Stillson Wrench"], a: 0, img: "images/erection_spud_wrench.png" },
        { q: "A wrench used for various nut sizes.", choices: ["Adjustable Wrench", "Monkey Wrench", "Locking Wrench", "Stillson Wrench"], a: 0, img: "images/adjustable_wrench.png" },
        { q: "A wrench using vise-grip fastening.", choices: ["Locking Wrench", "Monkey Wrench", "Adjustable Wrench", "Stillson Wrench"], a: 0, img: "images/locking_wrench.png" },
        { q: "A wrench designed for spud fittings.", choices: ["Adjustable Spud Wrench", "Erection Spud Wrench", "Adjustable Wrench", "Stillson Wrench"], a: 0, img: "images/adjustable_spud_wrench..png" },
        { q: "A wrench used for tight-space pipe turning.", choices: ["Offset Pipe Wrench", "Standard Pipe Wrench", "End Pipe Wrench", "Stillson Wrench"], a: 0, img: "images/offset_pipe_wrench.png" },
        { q: "A wrench designed for high-force pipe turning.", choices: ["Compound Leverage Wrench", "Chain Wrench", "Stillson Wrench", "Standard Pipe Wrench"], a: 0, img: "images/compound_leverage_wrench.png" },
        { q: "A wrench for quick-release turning.", choices: ["Rap Wrench", "Stillson Wrench", "Standard Pipe Wrench", "Adjustable Wrench"], a: 0, img: "images/rap_wrench.png" },
        { q: "A wrench used for pipe against walls.", choices: ["End Pipe Wrench", "Offset Pipe Wrench", "Stillson Wrench", "Standard Pipe Wrench"], a: 0, img: "images/end_pipe_wrench.png" },
        { q: "A classic wrench for pipe turning.", choices: ["Stillson Wrench", "Standard Pipe Wrench", "Offset Pipe Wrench", "End Pipe Wrench"], a: 0, img: "images/stillson_wrench.png" },
        { q: "A standard tool for pipe installation.", choices: ["Standard Pipe Wrench", "Stillson Wrench", "Offset Pipe Wrench", "End Pipe Wrench"], a: 0, img: "images/pipe_wrench.png" },
        { q: "A tool for high-speed bolt removal.", choices: ["Air Impact", "Ratchet Cutter", "Standard Pipe Wrench", "Torque Wrench"], a: 0, img: "images/Air Impact .png" }
    ],
    3: [
        { q: "What is the weight of 1 cubic foot of water in pounds?", choices: ["32.2 lbs", "62.4 lbs", "8.33 lbs", "7.48 lbs"], a: 1 },
        { q: "How many gallons are there in 1 cubic meter of water?", choices: ["231", "264", "462", "624"], a: 1 },
        { q: "A pipe has an inside diameter of 14 inches. What is the area of the cross-section?", choices: ["153.94 sq in", "73.04 sq in", "220.42 sq in", "38.92 sq in"], a: 0 },
        { q: "Convert 120 feet of static head into PSI (pounds per square inch).", choices: ["42.5 psi", "52.0 psi", "60.2 psi", "277 psi"], a: 1 }
    ],
    4: [
        { q: "What is the weight of 1 cubic foot of water in pounds?", choices: ["32.2 lbs", "62.4 lbs", "8.33 lbs", "7.48 lbs"], a: 1 },
        { q: "How many gallons are there in 1 cubic meter of water?", choices: ["231", "264", "462", "624"], a: 1 },
        { q: "A pipe has an inside diameter of 14 inches. What is the area of the cross-section?", choices: ["153.94 sq in", "73.04 sq in", "220.42 sq in", "38.92 sq in"], a: 0 },
        { q: "Convert 120 feet of static head into PSI (pounds per square inch).", choices: ["42.5 psi", "52.0 psi", "60.2 psi", "277 psi"], a: 1 }
    ]

};




