export const toolsDB = {
     1: [
        { q: "What is a Cordless Drill primarily used for?", choices: ["A. Drilling and driving screws", "B. Measuring pipe", "C. Cutting metal", "D. Bending copper"], a: 0, img: "/images/Cordless Drill .png" },
        { q: "What is a Drill Hammer used for?", choices: ["A. Removing nails", "B. Masonry drilling", "C. Cleaning pipes", "D. Threading pipe"], a: 1, img: "/images/Drill Hammer.png" },
        { q: "An Angle Grinder is typically used for?", choices: ["A. Grinding and cutting metal", "B. Painting pipes", "C. Measuring angles", "D. Tightening nuts"], a: 0, img: "/images/Angle Grinder.png" },
        { q: "What is a Sink Auger designed to clear?", choices: ["A. Main sewer lines", "B. Kitchen sink clogs", "C. Tree roots", "D. Vent pipes"], a: 1, img: "images/Sink Auger.png" },
        { q: "A Drain Machine is used for?", choices: ["A. Heavy-duty pipe clearing", "B. Soldering joints", "C. Measuring water flow", "D. Testing pressure"], a: 0, img: "images/Drain Machine.png" },
        { q: "What is a Toilet Auger used for?", choices: ["A. Clearing toilet blockages", "B. Drilling concrete", "C. Bending pipe", "D. Cutting tiles"], a: 0, img: "images/Toiler Auger.png" },
        { q: "A Flat File is used to?", choices: ["A. Smooth metal edges", "B. Tighten bolts", "C. Cut pipes", "D. Hammer nails"], a: 0, img: "images/Flat File.png" },
        { q: "What is a Cold Chisel used for?", choices: ["A. Cutting hard materials", "B. Measuring", "C. Polishing", "D. Painting"], a: 0, img: "images/Cold Chisel.png" },
        { q: "Plastic Pipe Shears are used for?", choices: ["A. Making square cuts in plastic", "B. Threading plastic", "C. Bending plastic", "D. Cleaning plastic"], a: 0, img: "images/plastic_pipe_shear.png" },
        { q: "What is a Hand Riveter used for?", choices: ["A. Fastening metal sheets", "B. Cutting wire", "C. Measuring", "D. Soldering"], a: 0, img: "images/hand_riveter.png" },
        { q: "Bolt Cutters are used for?", choices: ["A. Cutting bolts and rods", "B. Bending pipe", "C. Tightening nuts", "D. Drilling"], a: 0, img: "images/bolt_cutter.png" },
        { q: "An F-Clamp is used to?", choices: ["A. Hold materials together", "B. Measure length", "C. Cut wood", "D. Hammer"], a: 0, img: "images/f_clamp.png" },
        { q: "A C-Clamp is used to?", choices: ["A. Secure objects firmly", "B. Measure depth", "C. Drill holes", "D. File edges"], a: 0, img: "images/c_clamp.png" },
        { q: "A Ceiling Iron is used for?", choices: ["A. Caulking overhead joints", "B. Drilling ceilings", "C. Measuring heights", "D. Painting"], a: 0, img: "images/Ceiling Iron – square end .png" },
        { q: "What is an S-Type Caulking Iron used for?", choices: ["A. Packing joints in tight spots", "B. Cutting pipes", "C. Bending rods", "D. Drilling"], a: 0, img: "images/S -Type Caulking Iron.png" },
        { q: "A Left Iron is used for?", choices: ["A. Specialized caulking", "B. Cutting metal", "C. Measuring", "D. Hammering"], a: 0, img: "images/Left Iron.png" },
        { q: "A Stub Iron is used for?", choices: ["A. Short-reach caulking", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Stub Iron.png" },
        { q: "A Pick-out Iron is used to?", choices: ["A. Remove old caulking", "B. Hammer nails", "C. Cut wire", "D. File metal"], a: 0, img: "images/Pick-out Iron.png" },
        { q: "A standard Caulking Iron is for?", choices: ["A. Sealing pipe joints", "B. Measuring", "C. Drilling", "D. Bending"], a: 0, img: "images/Caulking Iron.png" },
        { q: "A Long Curved Offset Iron is for?", choices: ["A. Reaching awkward joints", "B. Cutting", "C. Hammering", "D. Filing"], a: 0, img: "images/Long curved offset Iron (square end) .png" },
        { q: "A Curved Offset Iron is used to?", choices: ["A. Seal inside/outside joints", "B. Measure", "C. Cut", "D. Drill"], a: 0, img: "images/Curved offset Iron (inside and outside) .png" },
        { q: "An Offset Yarning Iron is for?", choices: ["A. Packing yarn into joints", "B. Cutting pipe", "C. Drilling", "D. Filing"], a: 0, img: "images/Offset Yarning Iron.png" },
        { q: "A Spring Yarning Iron is used for?", choices: ["A. Flexible yarning", "B. Hammering", "C. Measuring", "D. Cutting"], a: 0, img: "images/Spring Yarning Iron.png" },
        { q: "A Core Drilling Machine is for?", choices: ["A. Making large holes in concrete", "B. Cutting wood", "C. Bending pipe", "D. Painting"], a: 0, img: "images/Core Drilling Machine.png" },
        { q: "A Geared Threader is used to?", choices: ["A. Cut threads on large pipe", "B. Bend pipe", "C. Measure", "D. File"], a: 0, img: "images/Geared Threader.png" },
        { q: "A Portable Cordless Drill is for?", choices: ["A. Mobile drilling tasks", "B. Cutting", "C. Measuring", "D. Hammering"], a: 0, img: "images/Portable Cordless Drill.png" },
        { q: "A Portable Roll Groover is for?", choices: ["A. Grooving pipe ends", "B. Cutting", "C. Threading", "D. Measuring"], a: 0, img: "images/Portable Roll Groover.png" },
        { q: "A Portable Electric Drill is for?", choices: ["A. Standard hole drilling", "B. Cutting", "C. Bending", "D. Filing"], a: 0, img: "images/Portable Electric Drill .png" },
        { q: "A Right Angle Drill is used for?", choices: ["A. Drilling in tight corners", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/Right Angle Drill.png" },
        { q: "A Reciprocating Orbital Saw is for?", choices: ["A. Rough cutting materials", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/Reciprocating Orbital Saw.png" },
        { q: "A Varl-orbit Jigsaw is used for?", choices: ["A. Intricate cutting", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Varl-orbit Jigsaw.png" },
        { q: "Smooth Jawed Pliers are for?", choices: ["A. Gripping without scratching", "B. Cutting wire", "C. Hammering", "D. Drilling"], a: 0, img: "images/Smooth Jawed Pliers .png" },
        { q: "Slip Joint Utility Pliers are for?", choices: ["A. Versatile gripping", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/Slip Joint Utility Pliers .png" },
        { q: "Slim Nose Pliers are for?", choices: ["A. Reaching narrow spaces", "B. Hammering", "C. Cutting pipe", "D. Drilling"], a: 0, img: "images/Slim Nose Pliers.png" },
        { q: "End Cutting Pliers are for?", choices: ["A. Cutting wire ends", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/End Cutting Pliers.png" },
        { q: "Long Reach Pliers are for?", choices: ["A. Deep-reach gripping", "B. Hammering", "C. Cutting", "D. Drilling"], a: 0, img: "images/Long Reach Pliers.png" },
        { q: "Long Reach Duckbill Pliers are for?", choices: ["A. Specialized reaching", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/Long Reach Duckbill Pliers.png" },
        { q: "Heavy Duty Side Cutting Pliers are for?", choices: ["A. Cutting thick wire", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Heavy Duty Side Cutting Pliers.png" },
        { q: "Universal Side Cutting Pliers are for?", choices: ["A. General wire cutting", "B. Drilling", "C. Hammering", "D. Measuring"], a: 0, img: "images/Universal Side Cutting Pliers.png" },
        { q: "Diagonal Cutting Pliers are for?", choices: ["A. Flush cutting wire", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Diagonal Cutting Pliers .png" },
        { q: "Lineman’s Side cutting Pliers are for?", choices: ["A. Electrical and wire work", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Lineman’s Side cutting Pliers.png" },
        { q: "Water Pump Pliers are for?", choices: ["A. Adjusting pipe fittings", "B. Cutting wire", "C. Measuring", "D. Drilling"], a: 0, img: "images/Water Pump Pliers .png" },
        { q: "Tongue and Groove Pliers are for?", choices: ["A. Adjustable gripping", "B. Cutting", "C. Measuring", "D. Drilling"], a: 0, img: "images/Tongue and Groove Pliers.png" },
        { q: "Power Hammers are used for?", choices: ["A. Heavy demolition", "B. Measuring", "C. Cutting", "D. Filing"], a: 0, img: "images/Power Hammers.png" },
        { q: "Long handle Sledge Hammer is for?", choices: ["A. Driving force/demolition", "B. Cutting", "C. Drilling", "D. Filing"], a: 0, img: "images/Long handle Sledge Hammer .png" },
        { q: "Hand Drilling Hammer is for?", choices: ["A. Driving masonry chisels", "B. Cutting pipe", "C. Measuring", "D. Painting"], a: 0, img: "images/Hand Drilling Hammer .png" },
        { q: "Tinner’s Hammer is for?", choices: ["A. Sheet metal work", "B. Drilling", "C. Measuring", "D. Cutting"], a: 0, img: "images/Tinner’s Hammer .png" },
        { q: "Mason’s Hammer is for?", choices: ["A. Breaking brick/stone", "B. Cutting wood", "C. Measuring", "D. Drilling"], a: 0, img: "images/Mason’s Hammer.png" },
        { q: "Curve Claw Hammer is for?", choices: ["A. Nail driving and pulling", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Curve Claw Hammer.png" },
        { q: "Engineers Hammer is for?", choices: ["A. Metalworking tasks", "B. Cutting", "C. Measuring", "D. Painting"], a: 0, img: "images/engineers_hammer.png" },
        { q: "Ripping Claw Hammer is for?", choices: ["A. Prying boards apart", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/Ripping Claw Hammer.png" },
        { q: "Half Hatchet Hammer is for?", choices: ["A. Light chopping/nailing", "B. Drilling", "C. Measuring", "D. Filing"], a: 0, img: "images/Half Hatchet Hammer .png" },
        { q: "Ball Peen Hammer is for?", choices: ["A. Shaping metal/riveting", "B. Cutting", "C. Measuring", "D. Drilling"], a: 0, img: "images/ball_peen_hammer.png" },
        { q: "Pressure Test Pump is for?", choices: ["A. Leak testing pipelines", "B. Cutting pipe", "C. Drilling", "D. Filing"], a: 0, img: "images/Pressure Test Pump .png" },
        { q: "Inflatable Rubber Test Balls are for?", choices: ["A. Plugging pipe for testing", "B. Cutting", "C. Measuring", "D. Hammering"], a: 0, img: "images/Inflatable Rubber Test Balls.png" },
        { q: "Mechanical Test Plug is for?", choices: ["A. Sealing pipe ends", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Mechanical Test Plug .png" },
        { q: "Propane Torch is for?", choices: ["A. Soldering copper joints", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/propane_torch.png" },
        { q: "Blow Torch is for?", choices: ["A. High-heat heating", "B. Cutting", "C. Measuring", "D. Painting"], a: 0, img: "images/blow_torch.png" },
        { q: "Melting Pot Ladle is for?", choices: ["A. Pouring molten lead", "B. Drilling", "C. Measuring", "D. Hammering"], a: 0, img: "images/melting_pot_ladle.png" },
        { q: "Air Operated Plunger is for?", choices: ["A. Force clearing drains", "B. Cutting", "C. Measuring", "D. Filing"], a: 0, img: "images/air_operated_plunger.png" },
        { q: "Accordion Plunger is for?", choices: ["A. Toilet drain clearing", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/accordion_plunger.png" },
        { q: "Toilet Plunger is for?", choices: ["A. Clearing toilet clogs", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/toilet_plunger.png" },
        { q: "Sink Plunger is for?", choices: ["A. Clearing sink clogs", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/sink_plunger.png" },
        { q: "Drain Rods are for?", choices: ["A. Clearing deep drain lines", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/drain_rods.png" },
        { q: "Flue Brush is for?", choices: ["A. Cleaning flue pipes", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/flue_brush.png" },
        { q: "Chain Knocker is for?", choices: ["A. Scraping inside pipes", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/chain_knocker.png" },
        { q: "Grease C-Cutter is for?", choices: ["A. Cutting grease blockage", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/grease_c_cutter.png" },
        { q: "Shark Tooth Cutter is for?", choices: ["A. Breaking up roots", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/shark_tooth_cutter.png" },
        { q: "Spiral Bar Cutter is for?", choices: ["A. Clearing pipe walls", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/spiral_bar_cutter.png" },
        { q: "Four Blade Saw Tooth Cutter is for?", choices: ["A. Aggressive blockage removal", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/four_blade_saw_tooth_cutter.png" },
        { q: "Saw Tooth Cutter is for?", choices: ["A. Clearing root debris", "B. Drilling", "C. Measuring", "D. Painting"], a: 0, img: "images/saw_tooth_cutter.png" },
        { q: "Spiral Saw Tooth Cutter is for?", choices: ["A. Clearing heavy debris", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/spiral_saw_tooth_cutter.png" },
        { q: "Grease Cutter is for?", choices: ["A. Removing grease buildup", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/grease_cutter.png" },
        { q: "Spade Cutter is for?", choices: ["A. Cutting blockages", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/spade_cutter.png" },
        { q: "Retrieving Auger is for?", choices: ["A. Recovering lost tools", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/retrieving_auger.png" },
        { q: "Hook Auger is for?", choices: ["A. Snagging debris", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/hook_auger.png" },
        { q: "Funnel Auger is for?", choices: ["A. Clearing initial blockages", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/funnel_auger.png" },
        { q: "Straight Auger is for?", choices: ["A. Standard obstruction clearing", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/straight_auger.png" },
        { q: "Drop Head Auger is for?", choices: ["A. Negotiating drain bends", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/drop_head_auger.png" },
        { q: "Flat Sewer Taps are for?", choices: ["A. Tapping sewer lines", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Flat Sewer Taps.png" },
        { q: "Hand Spinner is for?", choices: ["A. Manual drain clearing", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/Hand Spinner.png" },
        { q: "Angle Pipe Welding Vise is for?", choices: ["A. Holding pipe for welding", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/Angle Pipe Welding Vise.png" },
        { q: "Flange Pipe Welding Vise is for?", choices: ["A. Securing flanges for welding", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/Flange Pipe Welding Vise .png" },
        { q: "Elbow Pipe Welding Vise is for?", choices: ["A. Welding pipe elbows", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/Elbow Pipe Welding Vise.png" },
        { q: "Stand Chain Vise is for?", choices: ["A. Portable pipe holding", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/stand_chain_vise.png" },
        { q: "Bench Chain Vise is for?", choices: ["A. Stationary pipe holding", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/bench_chain_vise.png" },
        { q: "Bench Yoke Vise is for?", choices: ["A. Heavy-duty pipe holding", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/bench_yoke_vise.png" },
        { q: "Portable Tristand is for?", choices: ["A. On-site work support", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/portable_tristand.png" },
        { q: "Pipe Vise is for?", choices: ["A. Securing pipe for work", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/pipe_vise.png" },
        { q: "Tube Expander is for?", choices: ["A. Enlarging tube ends", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/tube_expander.png" },
        { q: "Geared-Ratchet Tube Bender is for?", choices: ["A. Bending rigid tubing", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/GEARED-RATCHET TUBE BENDER .png" },
        { q: "Level-Type Tube Bender is for?", choices: ["A. Precise manual bending", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/LEVEL-TYPE TUBE BENDER.png" },
        { q: "Spring-Type Tube Bender is for?", choices: ["A. Preventing tubing kinks", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/SPRING-TYPE TUBE BENDER .png" },
        { q: "Pipe Extractor is for?", choices: ["A. Removing broken pipe ends", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/pipe_extractor.png" },
        { q: "Combination Pipe Reamer is for?", choices: ["A. Removing internal burrs", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/COMBINATION PIPE REAMER.png" },
        { q: "Spiral Ratchet Pipe Reamer is for?", choices: ["A. Removing pipe burrs", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/SPIRAL RATCHET PIPE REAMER.png" },
        { q: "Pipe Tap is for?", choices: ["A. Cutting internal threads", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/pipe_tap.png" },
        { q: "Pipe Threader is for?", choices: ["A. Cutting external threads", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/pipe_threader.png" },
        { q: "Hacksaw is for?", choices: ["A. Manual metal cutting", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/hacksaw.png" },
        { q: "Soil Pipe Cutter is for?", choices: ["A. Cutting heavy soil pipe", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/soil_pipe_cutter.png" },
        { q: "Plastic Pipe Cutter is for?", choices: ["A. Cutting plastic lines", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/plastic_pipe_cutter.png" },
        { q: "Mini Tube Cutter is for?", choices: ["A. Tight-space tube cutting", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/mini_tube_cutter.png" },
        { q: "Ratchet Cutter is for?", choices: ["A. High-leverage cutting", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/ratchet_cutter.png" },
        { q: "Hinged Pipe Cutter is for?", choices: ["A. Cutting installed pipe", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/hinged_pipe_cutter.png" },
        { q: "Wide Roll Pipe Cutter is for?", choices: ["A. Precise square cutting", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/wide_roll_pipe_cutter.png" },
        { q: "4 Wheel Pipe Cutter is for?", choices: ["A. Tight-space rotation cutting", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/4_wheel_pipe_cutter.png" },
        { q: "Single Ended Jaw Chain is for?", choices: ["A. Gripping pipe", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/SIGLE ENDED JAW CHAIN .png" },
        { q: "Reversible Chain Tongs are for?", choices: ["A. Turning pipe in both directions", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/REVERSIBLE CHAIN TONGS .png" },
        { q: "The Hawk Heavy Duty Wrench is for?", choices: ["A. Self-adjusting grip", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/THE HAWK HEAVY DUTY SELF - ADJUSTMENT PIPE WRENCH.png" },
        { q: "Chain Wrench is for?", choices: ["A. Heavy-duty pipe turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/chain_wrench.png" },
        { q: "Bionic Wrench is for?", choices: ["A. Universal nut adjustment", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/bionic_wrench.png" },
        { q: "Basket Strainer Wrench is for?", choices: ["A. Tightening sink strainers", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/basket_strainer_wrench.png" },
        { q: "Curb Box Wrench is for?", choices: ["A. Accessing water curb boxes", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/curb_box_wrench.png" },
        { q: "Packing Nut Socket is for?", choices: ["A. Tightening packing nuts", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/packing_nut_socket.png" },
        { q: "Basin Wrench is for?", choices: ["A. Sink mounting nuts", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/basin_wrench.png" },
        { q: "Crowfoot Wrench is for?", choices: ["A. Hard-to-reach bolts", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/crawfoot’s_wrench.png" },
        { q: "Ratcheting Rotary Wrench is for?", choices: ["A. Fast rotation turning", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/ratcheting_rotary_wrench.png" },
        { q: "Closet Wrench is for?", choices: ["A. Toilet hardware", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/closet_wrench.png" },
        { q: "Valve Seat Wrench is for?", choices: ["A. Removing valve seats", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/valve_seat_wrench.png" },
        { q: "Allen Wrench is for?", choices: ["A. Hex socket screws", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/allen_wrench.png" },
        { q: "Hex Wrench is for?", choices: ["A. Hex head bolts", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/hex_wrench.png" },
        { q: "Internal Wrench is for?", choices: ["A. Nipple extraction", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/internal_wrench.png" },
        { q: "Torque Wrench is for?", choices: ["A. Precise tightening force", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/torque_wrench.png" },
        { q: "Jaw Dropper Wrench is for?", choices: ["A. Specialized gripping", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/jaw_dropper_wrench.png" },
        { q: "Strap Wrench is for?", choices: ["A. Non-marring grip", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/strap_wrench.png" },
        { q: "Monkey Wrench is for?", choices: ["A. Classic flat-jaw turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/monkey_wrench.png" },
        { q: "Pin Wrench is for?", choices: ["A. Adjustable pin turning", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/pin_wrench.png" },
        { q: "Erection Spud Wrench is for?", choices: ["A. Aligning holes/bolts", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/erection_spud_wrench.png" },
        { q: "Adjustable Wrench is for?", choices: ["A. Various nut sizes", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/adjustable_wrench.png" },
        { q: "Locking Wrench is for?", choices: ["A. Vise-grip fastening", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/locking_wrench.png" },
        { q: "Adjustable Spud Wrench is for?", choices: ["A. Spud fittings", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/adjustable_spud_wrench..png" },
        { q: "Offset Pipe Wrench is for?", choices: ["A. Tight-space pipe turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/offset_pipe_wrench.png" },
        { q: "Compound Leverage Wrench is for?", choices: ["A. High-force pipe turning", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/compound_leverage_wrench.png" },
        { q: "Rap Wrench is for?", choices: ["A. Quick-release turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/rap_wrench.png" },
        { q: "End Pipe Wrench is for?", choices: ["A. Pipe against walls", "B. Drilling", "C. Cutting", "D. Measuring"], a: 0, img: "images/end_pipe_wrench.png" },
        { q: "Stillson Wrench is for?", choices: ["A. Classic pipe turning", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/stillson_wrench.png" },
        { q: "Standard Pipe Wrench is for?", choices: ["A. General pipe installation", "B. Drilling", "C. Cutting", "D. Painting"], a: 0, img: "images/pipe_wrench.png" },
        { q: "Air Impact is for?", choices: ["A. High-speed bolt removal", "B. Drilling", "C. Cutting", "D. Filing"], a: 0, img: "images/Air Impact .png" }
    ],
    2: [
        { q: "What is the weight of 1 cubic foot of water in pounds?", choices: ["32.2 lbs", "62.4 lbs", "8.33 lbs", "7.48 lbs"], a: 1 },
        { q: "How many gallons are there in 1 cubic meter of water?", choices: ["231", "264", "462", "624"], a: 1 },
        { q: "A pipe has an inside diameter of 14 inches. What is the area of the cross-section?", choices: ["153.94 sq in", "73.04 sq in", "220.42 sq in", "38.92 sq in"], a: 0 },
        { q: "Convert 120 feet of static head into PSI (pounds per square inch).", choices: ["42.5 psi", "52.0 psi", "60.2 psi", "277 psi"], a: 1 }
    ],
    3: [
        { q: "What is the weight of 1 cubic foot of water in pounds?", choices: ["32.2 lbs", "62.4 lbs", "8.33 lbs", "7.48 lbs"], a: 1 },
        { q: "How many gallons are there in 1 cubic meter of water?", choices: ["231", "264", "462", "624"], a: 1 },
        { q: "A pipe has an inside diameter of 14 inches. What is the area of the cross-section?", choices: ["153.94 sq in", "73.04 sq in", "220.42 sq in", "38.92 sq in"], a: 0 },
        { q: "Convert 120 feet of static head into PSI (pounds per square inch).", choices: ["42.5 psi", "52.0 psi", "60.2 psi", "277 psi"], a: 1 }
    ],
    4: [
        { q: "What is the weight of 1 cubic foot of water in pounds?", choices: ["32.2 lbs", "62.4 lbs", "8.33 lbs", "7.48 lbs"], a: 1 },
        { q: "How many gallons are there in 1 cubic meter of water?", choices: ["231", "264", "462", "624"], a: 1 },
        { q: "A pipe has an inside diameter of 14 inches. What is the area of the cross-section?", choices: ["153.94 sq in", "73.04 sq in", "220.42 sq in", "38.92 sq in"], a: 0 },
        { q: "Convert 120 feet of static head into PSI (pounds per square inch).", choices: ["42.5 psi", "52.0 psi", "60.2 psi", "277 psi"], a: 1 }
    ]

};


